### ISSUE TITLE
BookingConfirm->language("CAS")

### ISSUE THREAD

**Issue by pralamo** [hotelbeds-sdk/hotel-api-sdk-php#10]
$rqBookingConfirm = new \hotelbeds\hotel_api_sdk\helpers\Booking();
 $rqBookingConfirm->holder = new \hotelbeds\hotel_api_sdk\model\Holder("name", "surname");
 $rqBookingConfirm->language="CAS";

Realizando la peticion de reserva del modo anterior, cuando seleccionamos language="CAS" se encuentra error:

Es problema de decodificación .

esta es la función donde falla. Recibe el body, pero no le gusta la sintaxis.
devuelve  throw new RuntimeException('Decoding failed');
seguiremos investigando:

Gracias

[JSON][ZEND]
public static function decode($encodedValue, $objectDecodeType = self::TYPE_OBJECT)
    {
        $encodedValue = (string) $encodedValue;
        if (function_exists('json_decode') && static::$useBuiltinEncoderDecoder !== true) {
            $decode = json_decode($encodedValue, $objectDecodeType);

            switch (json_last_error()) {
                case JSON_ERROR_NONE:
                    break;
                case JSON_ERROR_DEPTH:
                    throw new RuntimeException('Decoding failed: Maximum stack depth exceeded');
                case JSON_ERROR_CTRL_CHAR:
                    throw new RuntimeException('Decoding failed: Unexpected control character found');
                case JSON_ERROR_SYNTAX:
                    throw new RuntimeException('Decoding failed: Syntax error');
                default:
                    throw new RuntimeException('Decoding failed');
            }

            return $decode;
        }

**Comment by alvmunoz** [comment]
Esto es continuación de  #5

**Comment by alvmunoz** [comment]
¿Es posible que te de el error de decode cuando la respuesta es vacía?

**Comment by pralamo** [comment]
La respuesta no viene vacía
trae la típica de caracteres codificados.

**Comment by alvmunoz** [comment]
¿Puedes poner el cuerpo del mensaje que tienes justo antes de intentar decodificarlo?

**Comment by pralamo** [comment]
La respuesta no viene vacía

a la funcion del json-decode donde falla le llega esto esto:

"{"auditData":{"processTime":"49733","timestamp":"2016-04-01 
12:27:25.335","requestHost":"127.0.0.1, 
52.49.137.48","serverId":"sa3RKSJACHXE79K.env","environment":"[int]","release":"2cb1bad878d2195c9b508e2007ef96616007dacb","internal":"acrnzhza7n6zq69jwgprbhn2|ES|null|null|null|null|0|0|0|N||null|null|null|null|null||||1"},"booking":{"reference":"1-3129165","clientReference":"CLIENTE 
SPORTROOMS","creationDate":"2016-04-01","status":"CONFIRMED","holder":{"name":"FDFSDA","surname":"FSD"},"hotel":{"checkIn":"2016-06-02","checkOut":"2016-06-03","code":1526,"name":"Amic 
Horizonte","categoryCode":"3EST","categoryName":"3 
ESTRELLAS","destinationCode":"PMI","destinationName":"Mallorca","zoneCode":10,"zoneName":"Palma","latitude":"39.5554","longitude":"2.62155","rooms":[{"status":"CONFIRMED","code":"JSU.ST","name":"JUNIOR 
SUITE 
STANDARD","paxes":[{"roomId":1,"type":"AD","name":"Name","surname":"Surname"}],"rates":[{"rateClass":"NOR","paymentType":"AT_WEB","packaging":false,"boardCode":"RO","boardName":"SOLO 
HABITACI�N","cancellationPolicies":[{"amount":"84.34","from":"2016-05-31T23:59:00+02:00"}],"rooms":1}]}],"totalNet":"84.34","currency":"EUR","supplier":{"name":"HOTELBEDS 
PRODUCT,S.L.U.","vatNumber":"ESB38877676"}},"totalSellingRate":84.34,"totalNet":84.34,"pendingAmount":84.34,"currency":"EUR"}}"


luego da el runtime exception

**Comment by pralamo** [comment]
muchas consultas me devuelve el campo vacío.
La que te he enviado anteriormente sí trae datos.
¿Será el acento en habitaciÓn???

**Comment by alvmunoz** [comment]
¿QUé encoding estás usando? Debería de ser UTF-8

**Comment by pralamo** [comment]
Product Version: NetBeans IDE 8.1 (Build 201510222201)
Updates: NetBeans IDE is updated to version NetBeans 8.1 Patch 1
Java: 1.8.0_60; Java HotSpot(TM) 64-Bit Server VM 25.60-b23
Runtime: Java(TM) SE Runtime Environment 1.8.0_60-b27
System: Linux version 2.6.32-573.22.1.el6.centos.plus.x86_64 running on 
amd64;UTF-8; es_ES (nb)


Si

**Comment by alvmunoz** [comment]
¿lo ejecutas en local ? ¿O en un servidor?

**Comment by pralamo** [comment]
de momento solo en local

**Comment by alvmunoz** [comment]
Vale. Lo estamos mirando a ver qué puede ser.

**Comment by pralamo** [comment]
ok gracias.

Por cierto, estoy intentando reproducir el error de antes, y desde hace 
media hora no recibo nada en el cuerpo del mensaje.
estoy probando diferentes hoteles y sin language="CAS" y todo me 
devuelve vacío. El $Bookinhcomfirm

Casualmente ahora me ha respondido. Este es el cuerpo de una peticion en 
ingles....... me decuelve bien el Booking reference y llego hasta el 
final con el proceso



"{"auditData":{"processTime":"52645","timestamp":"2016-04-01 
13:08:14.184","requestHost":"136.243.62.133","serverId":"sa37AUX3ROLBLIS.env","environment":"[int]","release":"2cb1bad878d2195c9b508e2007ef96616007dacb","internal":"acrnzhza7n6zq69jwgprbhn2|ES|null|null|null|null|0|0|0|N||null|null|null|null|null||||1"},"booking":{"reference":"1-3129179","clientReference":"CLIENTE 
SPORTROOMS","creationDate":"2016-04-01","status":"CONFIRMED","holder":{"name":"NAME","surname":"SURNAME"},"hotel":{"checkIn":"2016-06-02","checkOut":"2016-06-03","code":1526,"name":"Amic 
Horizonte","categoryCode":"3EST","categoryName":"3 
STARS","destinationCode":"PMI","destinationName":"Majorca","zoneCode":10,"zoneName":"Palma","latitude":"39.5554","longitude":"2.62155","rooms":[{"status":"CONFIRMED","code":"SUI.ST","name":"SUITE 
STANDARD","paxes":[{"roomId":1,"type":"AD","name":"Name","surname":"Surname"}],"rates":[{"rateClass":"NOR","paymentType":"AT_WEB","packaging":false,"boardCode":"RO","boardName":"ROOM 
ONLY","cancellationPolicies":[{"amount":"126.51","from":"2016-05-31T23:59:00+02:00"}],"rooms":1}]}],"totalNet":"126.51","currency":"EUR","supplier":{"name":"HOTELBEDS 
PRODUCT,S.L.U.","vatNumber":"ESB38877676"}},"totalSellingRate":126.51,"totalNet":126.51,"pendingAmount":126.51,"currency":"EUR"}}"

**Comment by alvmunoz** [comment]
¿ Nos puedes poner la peticicón que lanzas para que te devuelva una respuesta con acento ?

**Comment by alvmunoz** [comment]
Hemos hecho un cambio forzando la codificación UTF-8, si era por el carácter del acento. 
¿Puedes actualizarte la última versión y volver a probar?

**Comment by pralamo** [comment]
voy con ello

**Comment by pralamo** [comment]
"{"auditData":{"processTime":"52221","timestamp":"2016-04-01 
15:48:24.369","requestHost":"183.82.96.201","serverId":"sa37AUX3ROLBLIS.env","environment":"[int]","release":"2cb1bad878d2195c9b508e2007ef96616007dacb","internal":"acrnzhza7n6zq69jwgprbhn2|ES|null|null|null|null|0|0|0|N||null|null|null|null|null||||1"},"booking":{"reference":"1-3129194","clientReference":"CLIENTE 
SPORTROOMS","creationDate":"2016-04-01","status":"CONFIRMED","holder":{"name":"NAME","surname":"SURNAME"},"hotel":{"checkIn":"2016-06-02","checkOut":"2016-06-03","code":1539,"name":"Hotel 
Isla Mallorca & Spa","categoryCode":"4EST","categoryName":"4 
ESTRELLAS","destinationCode":"PMI","destinationName":"Mallorca","zoneCode":10,"zoneName":"Palma","latitude":"39.569098","longitude":"2.627756","rooms":[{"status":"CONFIRMED","code":"DBT.ST","name":"DOBLE 
1 O 2 CAMAS 
STANDARD","paxes":[{"roomId":1,"type":"AD","name":"Name","surname":"Surname"}],"rates":[{"rateClass":"NOR","paymentType":"AT_WEB","packaging":false,"boardCode":"RO","boardName":"SOLO 
HABITACI�N","cancellationPolicies":[{"amount":"105.42","from":"2016-05-31T23:59:00+02:00"}],"rooms":1}]}],"totalNet":"105.42","currency":"EUR","supplier":{"name":"MIKI 
Travel 
Limited","vatNumber":"ESB38877676"}},"totalSellingRate":105.42,"totalNet":105.42,"pendingAmount":105.42,"currency":"EUR"}}"



Mismo resultado. El "SOLO HABITACION" parece que llega igual

**Comment by pralamo** [comment]
Con el cambio que habéis realizado sigo con el error.
Pero.... vamos por buen camino !!!!!!!!!!!!!!!!!!!!!
El error es el acento de HABITACIÓN..... como nos parecía.

Un poco a lo burro he añadido la siguiente línea en la funcion JSON del ZEND

  public static function decode($encodedValue, $objectDecodeType = 
self::TYPE_OBJECT)
     {
         $encodedValue = (string) $encodedValue;
         if (function_exists('json_decode') && 
static::$useBuiltinEncoderDecoder !== true) {
    $encodedValue= utf8_encode($encodedValue);
             $decode = json_decode($encodedValue, $objectDecodeType);
........

Con esa línea, obtengo correctamente la respuesta y finalizo el 
proceso...... en CASTELLANO!!!!!!!!!!!!!!!!!!!!!!

¿Se os ocurre donde actualizar esto? Al ser una librería exterior, 
cualquier actualización nos machacará el cambio......

Espero vuestra respuesta y continúo con el resto....

Un saludo

**Comment by alvmunoz** [comment]
¿Has actualizado el sdk?

**Comment by pralamo** [comment]
si. tenía el mismo problema.

El viernes a última hora de la tarde, envíe un correo con una solución 
temporal que me funcionaba.
realizo ahora unas pruebas y comento

**Comment by alvmunoz** [comment]
¿Estás usando Apache o el propio PHP en modo server?

**Comment by pralamo** [comment]
Apache/2.2.15 (CentOS)

default_charset    UTF-8    UTF-8
