### ISSUE TITLE
Connection

### ISSUE THREAD

**Issue by baladigitalmakkr** [hotelbeds-sdk/hotel-api-sdk-php#107]
I am new to this api, if you have sample pure php code(no api) can you share with me ? i have used the developers code but i couldn't get

**Comment by vmavromatis** [comment]
Hello @baladigitalmakkr and thank you for your post.

I am trying to understand your question, by 'no API' I assume you mean 'no SDK' right? If so try this:

```php
<?php

// Your API Key and secret from developer.hotelbeds.com
$apiKey = "xxxxxxxxxxxxxxxxxxx";  
$Secret = "xxxxxxxxxxxxx";

// Signature is generated by SHA256 (Api-Key + Secret + Timestamp (in seconds))
$signature = hash("sha256", $apiKey.$Secret.time());

$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => "https://api.test.hotelbeds.com/hotel-api/1.0/hotels",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 30,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "POST",
  CURLOPT_POSTFIELDS => '{
			  "stay": {
				"checkIn": "2017-12-22",
				"checkOut": "2017-12-26"
			  },
			  "occupancies": [{
				"rooms": 1,
				"adults": 1,
				"children": 0
			  }],
			  "hotels": {
				"hotel": [1,
				200,
				300,
				400,
				500]
			  }
			}',
  CURLOPT_HTTPHEADER => array(
    "accept: application/json",
    "accept-encoding: gzip",
    "api-key: ". $apiKey ."",
    "cache-control: no-cache",
    "content-type: application/json",
    "x-signature: ". $signature .""
  ),
));

$response = curl_exec($curl);
$err = curl_error($curl);

curl_close($curl);

if ($err) {
  echo "cURL Error #:" . $err;
} else {
	echo $response;
}
```

The above code will search for Christmas holidays for 1 adult between 5 hotels. Please let me know if this helps.

**Comment by baladigitalmakkr** [comment]
hi
above code i have used but getting following error

cURL Error #:SSL certificate problem: unable to get local issuer certificate

**Comment by vmavromatis** [comment]
@baladigitalmakkr, please make sure you have uncommented these two lines in your php.ini (for example in xampp this is `C:\xampp\php\php.ini`):
```
php_curl
php_openssl
```
and restarted your server. Else, ensure your certificates reside in your server's certificate folder. You might need to point to the path of the .pem file from the php.ini.
There are some very useful replies about this on SO https://stackoverflow.com/questions/28858351/php-ssl-certificate-error-unable-to-get-local-issuer-certificate 

Hope this helps. Let me know if you need any more help.

Regards

**Comment by baladigitalmakkr** [comment]
Hi

i have done above changes in my wamp server but getting same issue

**Comment by vmavromatis** [comment]
For development only, you may add this curl flag:
```CURLOPT_SSL_VERIFYPEER => false,```
However, for production you will eventually need to get https://curl.haxx.se/ca/cacert.pem and point to it from your php.ini file.

**Comment by baladigitalmakkr** [comment]
Hi Again

i tried all the way you have suggest couldn't move next level, any idea or help from your site ? (working code or video tutorial)

thanks

**Comment by vmavromatis** [comment]
@baladigitalmakkr, we will be posting some video tutorials at some point in the future, however I think your problem now is specifically with the SSL certificate for your server. The way to do this with PHP is by writing 'curl.cainfo=c:\path\to\cacert.pem' in your ini (changing the path).

I would suggest looking up some more online tutorials for wamp and SSL and if that doesn't work out, you can try xampp instead. Hope this helps.

**Comment by baladigitalmakkr** [comment]
Hi, connection issue ok now getting result from api, how i can get all the available hotel ? let me know the json request format

**Comment by vmavromatis** [comment]
In order to get a full list of all hotels you will need to use an API of static content called [ContentAPI](https://developer.hotelbeds.com/docs/read/apitude_content/Hotel_Operation). Bear in mind there is more than 170k hotels so you will need to run multiple GET requests (not POST).

Currently there are no ContentAPI models for this SDK but for the time being you may use a bash script to get them all:

```bash
#!/bin/bash 
# APITUDE ContentAPI batch script to download all hotels to a text file
# It may take more than an hour to get all hotels, depending on connection speed. Average time is 15-20sec per GET request

apiKey="xxxxxxxxxxxxxxxxxxxxx"
secret="xxxxxxxxxxxxx"
xSig=$(echo -n ${apiKey}${secret}$(date +%s)|sha256sum|awk '{ print $1}')
CURLOPTS=(-H 'Accept-Encoding: gzip' -H 'Api-key:'$apiKey'' -H 'X-Signature:'$xSig'')
START=1
END=1000

for (( c=1; c<=185; c++ ))
do
	curl --compressed -X GET "${CURLOPTS[@]}" "https://api.test.hotelbeds.com/hotel-content-api/1.0/hotels?fields=all&from=${START}&to=${END}" >> hotels.txt
	START=$((START+1000))
	END=$((END+1000))
done
```

Let me know if this works for you or if you need any more help. This post may help as well: https://github.com/hotelbeds-sdk/hotel-api-sdk-php/issues/90#issuecomment-341495625

**Comment by baladigitalmakkr** [comment]
can i create my own code without your sdk ? can please let me know how to request all the hotels ? below request is limited hotel need full hotel request ? 

'{
			  "stay": {
				"checkIn": "2017-12-22",
				"checkOut": "2017-12-26"
			  },
			  "occupancies": [{
				"rooms": 1,
				"adults": 1,
				"children": 0
			  }],
			  "hotels": {
				"hotel": [1,
				200,
				300,
				400,
				500]
			  }
			}',

**Comment by vmavromatis** [comment]
@baladigitalmakkr There is a maximum limit of 2000 hotels that you can search per request. All hotel ID's are in the ContentAPI which I linked above. We normally recommend to TO's to map the areas they serve into hotel arrays. 

Alternatively you can search by geolocation as such:
```json
{
  "stay": {
    "checkIn": "2017-12-15",
    "checkOut": "2017-12-20",
    "shiftDays": "2"
  },
  "occupancies": [{
    "rooms": 1,
    "adults": 1,
    "children": 0
  }],
  "geolocation": {
    "latitude": 39.57119,
    "longitude": 2.646633999999949,
    "radius": 20,
    "unit": "km"
  }
}
```
Or by destination, but that setting is disabled by default. See more in the documentation: https://developer.hotelbeds.com/docs/read/apitude_booking/Availability

**Comment by baladigitalmakkr** [comment]
thanks and in the response how we can get the hotel images ?

**Comment by vmavromatis** [comment]
No problem. Images are part of the ContentAPI again. It's discouraged to run seperate requests per hotel as it's not efficient, but if you want it only for testing you can try (e.g. for hotel 300): 

```php
<?php

// Your API Key and secret from developer.hotelbeds.com
$apiKey = "xxxxxxxxxxxxxxxxxxx";  
$Secret = "xxxxxxxxxxxxx";

// Signature is generated by SHA256 (Api-Key + Secret + Timestamp (in seconds))
$signature = hash("sha256", $apiKey.$Secret.time());

$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => "https://api.test.hotelbeds.com/hotel-content-api/1.0/hotels/300",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 30,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "GET",
  CURLOPT_HTTPHEADER => array(
    "accept: application/json",
    "accept-encoding: gzip",
    "api-key: ". $apiKey ."",
    "cache-control: no-cache",
    "content-type: application/json",
    "x-signature: ". $signature .""
  ),
));

$response = curl_exec($curl);
$err = curl_error($curl);

curl_close($curl);

if ($err) {
  echo "cURL Error #:" . $err;
} else {
	echo $response;
}
```

Then from the response get ```hotelDetailsRS/hotel/images/image@path``` and append it to http://photos.hotelbeds.com/giata/

**Comment by vmavromatis** [comment]
I will now be closing this issue as it's not related to the SDK and all connection issues were resolved. Please feel free to open a new issue if you have any issues regarding the SDK itself.
