### ISSUE TITLE
Could not checkRate

### ISSUE THREAD

**Issue by nathanphan** [hotelbeds-sdk/hotel-api-sdk-php#108]
> [2017-11-11 19:15:26] local.ERROR: exception 'hotelbeds\hotel_api_sdk\types\HotelSDKException' with message 'Internal Server Error: PRODUCT_ERROR-496f1996-d351-494c-9a79-586bccaad906 ProductException(bb8b8ffd-f75f-4a51-88ae-2c2af6bcb5ec, CHECK_RATE, Request restricted for Ttoo)' in /Users/nathanphan/Work/Innaway/customerapi/vendor/hotelbeds/hotel-api-sdk-php/src/HotelApiClient.php:181
Stack trace:
#0 /Users/nathanphan/Work/Innaway/customerapi/vendor/hotelbeds/hotel-api-sdk-php/src/HotelApiClient.php(150): hotelbeds\hotel_api_sdk\HotelApiClient->callApi(Object(hotelbeds\hotel_api_sdk\messages\CheckRateRQ))
#1 /Users/nathanphan/Work/Innaway/customerapi/app/Business/PropertyBusiness.php(138): hotelbeds\hotel_api_sdk\HotelApiClient->__call('checkRate', Array)
#2 /Users/nathanphan/Work/Innaway/customerapi/app/Business/PropertyBusiness.php(138): hotelbeds\hotel_api_sdk\HotelApiClient->checkRate(Object(hotelbeds\hotel_api_sdk\helpers\CheckRate))
#3 /Users/nathanphan/Work/Innaway/customerapi/app/Business/PropertyBusiness.php(112): App\Business\PropertyBusiness->hotelBedRecheckRate(Array)
#4 /Users/nathanphan/Work/Innaway/customerapi/app/Http/Controllers/API/PropertyController.php(173): App\Business\PropertyBusiness->checkAvailability(Object(Illuminate\Http\Request), Object(App\Property))
#5 [internal function]: App\Http\Controllers\API\PropertyController->details(Object(Illuminate\Http\Request), '8032')
#6 /Users/nathanphan/Work/Innaway/customerapi/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
#7 /Users/nathanphan/Work/Innaway/customerapi/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('details', Array)

the above is the error I had when trying to re-check rate for ratePlan with rateType == 'RECHECK'

I following the workflow:

1.  make availability reques
2. if rateType is RECHECK, then call re-check (I have error here)
3. booking confirmation

I am using LIVE key for this
Please advice me how to fix

Thanks and Best Regard

**Comment by nathanphan** [comment]
this is the availability response which I used to check rate

`array (
      'hotels' => 
      array (
        0 => 
        array (
          'code' => 146278,
          'name' => 'Crowne Plaza West Hanoi',
          'categoryCode' => '5EST',
          'categoryName' => '5 STARS',
          'destinationCode' => 'HAN',
          'destinationName' => 'Hanoi and North',
          'zoneCode' => 1,
          'zoneName' => 'Hanoi',
          'latitude' => '21.02742149',
          'longitude' => '105.767692',
          'rooms' => 
          array (
            0 => 
            array (
              'code' => 'DBL.KG-NM',
              'name' => 'DOUBLE KING BED NON SMOKING',
              'rates' => 
              array (
                0 => 
                array (
                  'rateKey' => '20180530|20180531|W|358|146278|DBL.KG-NM|ID_B2B_26|RO|IWU25|1~1~2|2~3|N@4F8D0A3AB25D4C2E936A8E944DEF7CF81315',
                  'rateClass' => 'NOR',
                  'rateType' => 'RECHECK',
                  'net' => '179.49',
                  'allotment' => 99,
                  'paymentType' => 'AT_WEB',
                  'packaging' => false,
                  'boardCode' => 'RO',
                  'boardName' => 'ROOM ONLY',
                  'rooms' => 1,
                  'adults' => 1,
                  'children' => 2,
                  'childrenAges' => '2,3',
                ),
                1 => 
                array (
                  'rateKey' => '20180530|20180531|W|358|146278|DBL.KG-NM|ID_B2B_26|BB|IWB25|1~1~2|2~3|N@4F8D0A3AB25D4C2E936A8E944DEF7CF81315',
                  'rateClass' => 'NOR',
                  'rateType' => 'RECHECK',
                  'net' => '194.25',
                  'allotment' => 99,
                  'paymentType' => 'AT_WEB',
                  'packaging' => false,
                  'boardCode' => 'BB',
                  'boardName' => 'BED AND BREAKFAST',
                  'rooms' => 1,
                  'adults' => 1,
                  'children' => 2,
                  'childrenAges' => '2,3',
                ),
              ),
            ),
            1 => 
            array (
              'code' => 'DBL.2D',
              'name' => 'DOUBLE TWO DOUBLE BEDS',
              'rates' => 
              array (
                0 => 
                array (
                  'rateKey' => '20180530|20180531|W|358|146278|DBL.2D|ID_B2B_26|RO|IWU25|1~1~2|2~3|N@4F8D0A3AB25D4C2E936A8E944DEF7CF81315',
                  'rateClass' => 'NOR',
                  'rateType' => 'RECHECK',
                  'net' => '179.49',
                  'allotment' => 99,
                  'paymentType' => 'AT_WEB',
                  'packaging' => false,
                  'boardCode' => 'RO',
                  'boardName' => 'ROOM ONLY',
                  'rooms' => 1,
                  'adults' => 1,
                  'children' => 2,
                  'childrenAges' => '2,3',
                ),
                1 => 
                array (
                  'rateKey' => '20180530|20180531|W|358|146278|DBL.2D|ID_B2B_26|BB|IWB25|1~1~2|2~3|N@4F8D0A3AB25D4C2E936A8E944DEF7CF81315',
                  'rateClass' => 'NOR',
                  'rateType' => 'RECHECK',
                  'net' => '194.25',
                  'allotment' => 99,
                  'paymentType' => 'AT_WEB',
                  'packaging' => false,
                  'boardCode' => 'BB',
                  'boardName' => 'BED AND BREAKFAST',
                  'rooms' => 1,
                  'adults' => 1,
                  'children' => 2,
                  'childrenAges' => '2,3',
                ),
              ),
            ),
            2 => 
            array (
              'code' => 'TWN.ST',
              'name' => 'TWIN STANDARD',
              'rates' => 
              array (
                0 => 
                array (
                  'rateKey' => '20180530|20180531|W|358|146278|TWN.ST|ID_B2B_26|RO|IWU25|1~1~2|2~3|N@4F8D0A3AB25D4C2E936A8E944DEF7CF81315',
                  'rateClass' => 'NOR',
                  'rateType' => 'RECHECK',
                  'net' => '194.25',
                  'allotment' => 99,
                  'paymentType' => 'AT_WEB',
                  'packaging' => false,
                  'boardCode' => 'RO',
                  'boardName' => 'ROOM ONLY',
                  'rooms' => 1,
                  'adults' => 1,
                  'children' => 2,
                  'childrenAges' => '2,3',
                ),
                1 => 
                array (
                  'rateKey' => '20180530|20180531|W|358|146278|TWN.ST|ID_B2B_26|BB|IWB25|1~1~2|2~3|N@4F8D0A3AB25D4C2E936A8E944DEF7CF81315',
                  'rateClass' => 'NOR',
                  'rateType' => 'RECHECK',
                  'net' => '209.01',
                  'allotment' => 99,
                  'paymentType' => 'AT_WEB',
                  'packaging' => false,
                  'boardCode' => 'BB',
                  'boardName' => 'BED AND BREAKFAST',
                  'rooms' => 1,
                  'adults' => 1,
                  'children' => 2,
                  'childrenAges' => '2,3',
                ),
              ),
            ),
            3 => 
            array (
              'code' => 'DBL.KG',
              'name' => 'DOUBLE KING SIZE BED',
              'rates' => 
              array (
                0 => 
                array (
                  'rateKey' => '20180530|20180531|W|358|146278|DBL.KG|ID_B2B_26|RO|IWU25|1~1~2|2~3|N@4F8D0A3AB25D4C2E936A8E944DEF7CF81315',
                  'rateClass' => 'NOR',
                  'rateType' => 'RECHECK',
                  'net' => '194.25',
                  'allotment' => 99,
                  'paymentType' => 'AT_WEB',
                  'packaging' => false,
                  'boardCode' => 'RO',
                  'boardName' => 'ROOM ONLY',
                  'rooms' => 1,
                  'adults' => 1,
                  'children' => 2,
                  'childrenAges' => '2,3',
                ),
                1 => 
                array (
                  'rateKey' => '20180530|20180531|W|358|146278|DBL.KG|ID_B2B_26|BB|IWB25|1~1~2|2~3|N@4F8D0A3AB25D4C2E936A8E944DEF7CF81315',
                  'rateClass' => 'NOR',
                  'rateType' => 'RECHECK',
                  'net' => '209.01',
                  'allotment' => 99,
                  'paymentType' => 'AT_WEB',
                  'packaging' => false,
                  'boardCode' => 'BB',
                  'boardName' => 'BED AND BREAKFAST',
                  'rooms' => 1,
                  'adults' => 1,
                  'children' => 2,
                  'childrenAges' => '2,3',
                ),
              ),
            ),
            4 => 
            array (
              'code' => 'DBL.EJ',
              'name' => 'DOUBLE EXECUTIVE',
              'rates' => 
              array (
                0 => 
                array (
                  'rateKey' => '20180530|20180531|W|358|146278|DBL.EJ|ID_B2B_26|RO|IWU25|1~1~2|2~3|N@4F8D0A3AB25D4C2E936A8E944DEF7CF81315',
                  'rateClass' => 'NOR',
                  'rateType' => 'RECHECK',
                  'net' => '228.70',
                  'allotment' => 99,
                  'paymentType' => 'AT_WEB',
                  'packaging' => false,
                  'boardCode' => 'RO',
                  'boardName' => 'ROOM ONLY',
                  'rooms' => 1,
                  'adults' => 1,
                  'children' => 2,
                  'childrenAges' => '2,3',
                ),
                1 => 
                array (
                  'rateKey' => '20180530|20180531|W|358|146278|DBL.EJ|ID_B2B_26|BB|IWB25|1~1~2|2~3|N@4F8D0A3AB25D4C2E936A8E944DEF7CF81315',
                  'rateClass' => 'NOR',
                  'rateType' => 'RECHECK',
                  'net' => '243.47',
                  'allotment' => 99,
                  'paymentType' => 'AT_WEB',
                  'packaging' => false,
                  'boardCode' => 'BB',
                  'boardName' => 'BED AND BREAKFAST',
                  'rooms' => 1,
                  'adults' => 1,
                  'children' => 2,
                  'childrenAges' => '2,3',
                ),
              ),
            ),
          ),
          'minRate' => '179.49',
          'maxRate' => '243.47',
          'currency' => 'USD',
        ),
      ),
      'checkIn' => '2018-05-30',
      'total' => 1,
      'checkOut' => '2018-05-31',
    ),`

**Comment by vmavromatis** [comment]
Hello @nathanphan and thank you for your post.

From a first look your client seems to be working as it prints a response fine, and the error you are getting seems to be server-side related. Normally these errors should get reported to apitude@hotelbeds.com but I can try to assist you.
That said, this error probably has to do with a limitation set by the server.  Can you please tell me how many rateKeys you are sending? [Normally the limit is 10 ratekeys](https://developer.hotelbeds.com/docs/apitude_booking/FAQ#chr_question1) but that could vary AFAIK. Ideally, can you please give me your checkRates request so I can try to reproduce?

Thank you very much in advance.

**Comment by nathanphan** [comment]
It appears to me that only some rates got this problem.

I only used 9 rates at a time

**Comment by vmavromatis** [comment]
>It appears to me that only some rates got this problem.
>I only used 9 rates at a time

Try using one-by-one (for few examples) and see if one them returns an error. Then, try increasing the number of checkRates per request progressively until you find an error (thus limit). I'm aware that this is very non-technical approach but it can work in this case.

**Comment by nathanphan** [comment]
I will try it, thank you very much
