### ISSUE TITLE
Can we have 'allotment' field in rates when recheck with CheckRateRQ

### ISSUE THREAD

**Issue by nathanphan** [hotelbeds-sdk/hotel-api-sdk-php#109]
Please add 'allotment' to CheckRateRS

or just make it response similar as checking availabilty

**Comment by vmavromatis** [comment]
Hotfixed with eedd9c1fed8da6edf0eb97563085cb8caf12decb
Pull the latest version and let me know if it works fine for you. Leaving open waiting for confirmation.

**Comment by nathanphan** [comment]
I checked out but there is no allotment returned

**Comment by vmavromatis** [comment]
Can you please confirm that your model/Rate.php file is updated (contains allotment variable)?
How are you updating? Did you try using `composer update "hotelbeds/hotel-api-sdk-php:dev-master@dev"`?

**Comment by nathanphan** [comment]
yes I am using that

https://snag.gy/iQklwz.jpg

**Comment by vmavromatis** [comment]
Reverted patch due to a duplicate variable, update to make sure; in my system allotment get returned just fine.

Try using some code from the demo to make sure you use iterators properly. For example do this with the response:

```php
   foreach ($availRS->hotels->iterator() as $hotelCode => $hotelData) {
        foreach ($hotelData->iterator() as $roomCode => $roomData) {
            foreach ($roomData->rateIterator() as $rateKey => $rateData) {
                echo $rateData->allotment;
                }
        }
    }
```

**Comment by nathanphan** [comment]
I tried with the iterator, but now allotment

**Comment by vmavromatis** [comment]
@nathanphan Can you please show me the full response? I assume you are requesting hotels which have availability. Thank you in advance.

**Comment by vmavromatis** [comment]
@nathanphan It's expected behavior. You should already have the allotment from the availability request, thus you don't need to check it again in the CheckRates stage. It's only displayed if there is an upselling. Hope that helps.
