### ISSUE TITLE
Geolocation Type Error

### ISSUE THREAD

**Issue by mjsorribas** [hotelbeds-sdk/hotel-api-sdk-php#11]
Hola, estoy probando la API y al crear geolocation de la siguiente manera:
```
//Ingreso destino por ubicación GPS  de Destino
$geolocation = new Geolocation();
$geolocation->latitude = -32.949815300;
$geolocation->longitude= -60.654034800;
$geolocation->radius= 5;
$geolocation->unit= km;
$rqData->geolocation = [ $geolocation ]

```
Me da el siguiente error en la consola:
```
PHP Fatal error:  Uncaught exception 'Exception' with message 'Type error: Field latitude needs float type!' in /var/www/html/api/src/generic/DataContainer.php:58
Stack trace:
#0 /var/www/html/api/test2.php(33): hotelbeds\hotel_api_sdk\generic\DataContainer->__set('latitude', -32.9498153)
#1 {main}
  thrown in /var/www/html/api/src/generic/DataContainer.php on line 58
```

Estoy pasando mal la información o es otro tipo de error?
Como no vi ejemplos con geolocation no se si esta bien como lo he armado.

También he probado convertir a FLOAT de la siguiente manera:
$latitude = floatval('-32.9498153000');
$longitud= floatval('-60.6540348');
Y a pesar de verificar que se forma un tipo de variable FLOAT , no funciona.

**Comment by alvmunoz** [comment]
@mjsorribas hola,
hemos hecho un update para corregir el error del Float. 

De todas formas, tienes un par de cosas mal en la petición que ya te adelanto porque será lo siguiente que te devuelva error: 

1) Radius es un float, así que tendrás que pasarlo como 5.0 en lugar de 5.
$geolocation->radius= 5.0;

2) Tenemos un enumerador para definir los valores de unit, así que lo deberías de pasar así:
 unit= Geolocation::KM ;

3) geolocation no es un array, así que debes de quitar los corchetes: 
$rqData->geolocation = $geolocation;

En general, quedaría así: 

$geolocation = new Geolocation();
$geolocation->latitude = -32.949815300;
$geolocation->longitude= -60.654034800;
$geolocation->radius= 5.0;
$geolocation->unit= Geolocation::KM ;
$rqData->geolocation = $geolocation;

**Comment by mjsorribas** [comment]
Hola, el fix es igual al que yo pushee en mi fork. pasaron a double los parametros en el modelo.  :-/

**Comment by alvmunoz** [comment]
Perdona, no recibimos ningun Pull Request.
