### ISSUE TITLE
Developer Inactive when testing with postman

### ISSUE THREAD

**Issue by slim-hmidi** [hotelbeds-sdk/hotel-api-sdk-php#111]
I'm trying to test hotelbeds api with postman. I edit the enviroment mangement and I change the api_key and secret with my own credentials then I save. But when I tried to send a GET query like this : `https://api.test.hotelbeds.com/hotel-api/1.0/hotels` I got this error message:
```
Developer Inactive
```
However when I access my account in hotelbeds, the status is active.How can I fix that?

**Comment by vmavromatis** [comment]
Hi @slim-hmidi, I am looking into it. I believe it's an issue with the Postman collections not having been properly updated.

**Comment by slim-hmidi** [comment]
@vmavromatis So how can I test the api?

**Comment by vmavromatis** [comment]
Try again please. Try unsubscribing  and re-subscribing, there was an issue with the casing 'secret' was spelled 'Secret' and that was causing the error. Are you on Chrome edition?

**Comment by slim-hmidi** [comment]
I'm using the postman application on ubuntu 17.04

**Comment by slim-hmidi** [comment]
I tried to unsubscribe and subscribe then I changed the 'Secret' with 'secret' and I got the same error.

**Comment by vmavromatis** [comment]
Can you please show me your api-key? (NOT the secret). I can check if it's properly activated. In the meantime I am trying to find where the postman error is coming from. For me, I needed to change the 'Secret' casing, but not sure why this is not working for you.

Double check your system clock is accurate because the time is used for the hash function.

**Comment by slim-hmidi** [comment]
My api-key: '8h2657hv4b3b35na7vm7yy3z'

**Comment by slim-hmidi** [comment]
@vmavromatis I did not the X-Signature to the environment.Should I added it as a key in postman?

**Comment by vmavromatis** [comment]
@slim-hmidi My idea is that you should delete your current collection from left tab [...]->Delete and your environment variables, top right gear [Manage environments]->Trashcan. And then close postman and click this link to re-import everything.

https://app.getpostman.com/run-collection/be1769748a078faef0b1#?env%5BAPItude%20portal%20environment.template%5D=W3siZW5hYmxlZCI6dHJ1ZSwia2V5IjoiZW5kcG9pbnQiLCJ2YWx1ZSI6Imh0dHBzOi8vYXBpLnRlc3QuaG90ZWxiZWRzLmNvbS8iLCJ0eXBlIjoidGV4dCJ9LHsiZW5hYmxlZCI6dHJ1ZSwia2V5IjoiQXBpLWtleSIsInZhbHVlIjoiWFhYWFhYWFhYWFhYWCIsInR5cGUiOiJ0ZXh0In0seyJlbmFibGVkIjp0cnVlLCJrZXkiOiJzZWNyZXQiLCJ2YWx1ZSI6IlhYWFhYWFhYWCIsInR5cGUiOiJ0ZXh0In1d

Then just replace the apikey and secret. Let me know if you run into more issues.

**Comment by slim-hmidi** [comment]
I got this error now : `Not Authorized`. Based to the documentation `Not authorized - The X-Signature parameter is incorrect. Check its creation and server time.`

**Comment by slim-hmidi** [comment]
I resolved the problem by adding X-signature to the postman enviroment.

**Comment by vmavromatis** [comment]
Perfect, glad to know it's resolved, thought I find it strange that the script did not generate the variable with
```javascript
if(environment["X-Signature"] !== undefined){
    postman.setEnvironmentVariable("X-Signature", encryption);
}
else if(globals["X-Signature"] !== undefined){
    postman.setGlobalVariable("X-Signature", encryption);
}
```
Anyway, all good.
