### ISSUE TITLE
Invalid data. Error at property rooms: The distribution of paxes is not correct. The number of children specified in the paxes do not match with the requested ones.

### ISSUE THREAD

**Issue by Tahir-MatrixAMS** [hotelbeds-sdk/hotel-api-sdk-php#113]
Hi Team, 
Current we are implementing hotelbeds-sdk/hotel-api-sdk-php. we are facing the issue on booking api when we are book hotel with one room according to the documentation (https://developer.hotelbeds.com/docs/read/apitude_booking/Booking). it is working fine. but in case of we have two room, 2 adults and 2 child we have getting error. the detail example are below for better understanding. 
Please let know as soon as possible. 
We Do The following steps: This Test Case try on Hotelbed sandbox =========================================================================================================
 1. Step My Request for Availability - hotel - Api1.0 ========================================================================================================
  { "stay": { "checkIn": "2018-01-23", "checkOut": "2018-01-24", "shiftDays": "2" }, "occupancies": [ { "rooms": 2, "adults": 2, "children": 2, "paxes": [ { "type": "AD", "age": 30 }, { "type": "AD", "age": 24 }, { "type": "CH", "age": 4 }, { "type": "CH", "age": 8 } ] } ], "hotels": { "hotel": [ 1067,1070,1075,135813,145214,1506,1508,1526,1533,1539,1550,161032,170542,182125,187939,212167,215417,228671,229318,23476 ] } }
  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ 
 =================================================================== 
  2. Step Target Response for the above Request 
  =================================================================== 
  "hotels": [{ "code": 1070, "name": "Armadams", "categoryCode": "4EST", "categoryName": "4 STARS", "destinationCode": "PMI", "destinationName": "Majorca", "zoneCode": 10, "zoneName": "Palma", "latitude": "39.568861", "longitude": "2.630294", "rooms": [{ "code": "QUA.ST", "name": "QUADRUPLE STANDARD", "rates": [{ "rateKey": "20180123|20180124|W|1|1070|QUA.ST|CG- MERCHANT|RO||2~2~2|4~8|N@54A7D2A81BCD4307B418DF64090F22F60856", "rateClass": "NOR", "rateType": "BOOKABLE", "net": "301.70", "sellingRate": "340.00", "hotelMandatory": true, "allotment": 5, "rateCommentsId": "1|99454|96", "paymentType": "AT_WEB", "packaging": false, "boardCode": "RO", "boardName": "ROOM ONLY", "rooms": 2, "adults": 2, "children": 2, "childrenAges": "4,8", } ===================================================================
   3. Step Request for Booking 
  =================================================================== 
  <bookingRQ xmlns="http://www.hotelbeds.com/schemas/messages" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"> <holder name="HOLDER NAME" surname="HOLDER SURNAME"/> <clientReference>My booking reference</clientReference> <rooms> <room rateKey="20180123|20180124|W|1|1070|QUA.ST|CG- MERCHANT|RO||2~2~2|4~8|N@54A7D2A81BCD4307B418DF64090F22F60856"> <paxes> <pax roomId="1" type="AD" age="30" name="ADULT NAME one" surname="ADULT SURNAME"/> <pax roomId="1" type="CH" age="4" name="CHILDREN NAME one" surname="CHILDREN SURNAME"/> <pax roomId="2" type="AD" age="24" name="ADULT NAME two" surname="ADULT SURNAME"/> <pax roomId="2" type="CH" age="8" name="CHILDREN NAME two" surname="CHILDREN SURNAME"/> </paxes> </room> </rooms> </bookingRQ> 
  =================================================================== 
  4. Step Response against Booking 
  ===================================================================
   { "auditData": { "processTime": "2", "timestamp": "2018-01-22 09:11:24.255", "requestHost": "23.23.79.235", "serverId": "sa37AUX3ROLBLIS.env#PL", "environment": "[int]", "release": "be8bbee54ea6781ecaa959acb3f882f5ec840e7f", "token": "cf7c46de-8b71-4f41-801e-72919e289079", "internal": "0|54A7D2A81BCD4307B418DF64090F22F60856|UK|07|2|29|||||||||||R|5|2|1~2~2~2||0||0|677npfgve4xqdpm97g42eu96|||" }, "error": { "code": "INVALID_DATA-cf7c46de-8b71-4f41-801e-72919e289079", "message": "Invalid data. Error at property rooms: The distribution of paxes is not correct. The number of children specified in the paxes do not match with the requested ones." } }

**Comment by vmavromatis** [comment]
Hi @Tahir-MatrixAMS, thank you for the formatted request, appreciated.
Unfortunately, I am missing you booking request. Can you please post it"? I tried booking using this:

`
{
	"holder": {
		"name": "IntegrationTestFirstName",
		"surname": "IntegrationTestLastName"
	},
	"rooms": [{
		"rateKey": "20180124|20180125|W|1|1070|QUA.ST|CG- MERCHANT|BB||2~2~2|4~8|N@C9D2B360F2BD4D848A1FC728947689A51225",
		"paxes": [{
			"roomId": "1",
			"type": "AD",
			"name": "Adult Name"
		},
		{
			"roomId": "1",
			"type": "AD",
			"name": "Adult Name"
		},
		{
			"roomId": "2",
			"type": "CH",
			"name": "Child Name"
		},
		{
			"roomId": "2",
			"type": "CH",
			"name": "Child Name"
		}]
	}],
	"clientReference": "IntegrationAgency"
}
`

And indeed I am receiving the same error. I will check with backend and let you know.

**Comment by Tahir-MatrixAMS** [comment]
Thank for your kind response. we hope you will resolve it soon. I think at least one adult is mandatory for each room 
eg:( 
"paxes": [{ **"roomId": "1", "type": "AD"**, "name": "Adult Name" }, { **"roomId": "2", "type": "AD"**, "name": "Adult Name" }, { **"roomId": "1", "type": "CH"**, "name": "Child Name" }, { **"roomId": "2", "type": "CH"**, "name": "Child Name" }] }]
)


Kindly ensure that am i doing it in a right way. because I am still facing the error

**Comment by vmavromatis** [comment]
@Tahir-MatrixAMS you are correct, I edited my response. We are waiting for backend to get back to us. I will let you know regarding the progress.

**Comment by Tahir-MatrixAMS** [comment]
we are waiting for your kind reply. i would like to ask you that can we apply for certification process in this condition or we should wait for its solution.

Thanks

**Comment by vmavromatis** [comment]
Hi @Tahir-MatrixAMS, we have looked into this case.  I would like to make sure what you are requesting in the Availability step. If you want to book two rooms (each with 1 adult and 1 child) you need to format it like this:

`{
	"stay": {
		"checkIn": "2018-12-15",
		"checkOut": "2018-12-20"
	},
	"occupancies": [{
		"rooms": 1,
		"adults": 1,
		"children": 1,
		"paxes": [{
				"type":"CH",
				"age":"4"
				}]
	},
	{
		"rooms": 1,
		"adults": 1,
		"children": 1,
		"paxes": [{
				"type":"CH",
				"age":"8"
				}]
	}
	],
	"hotels": {
		"hotel": [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,
		271]
	}
}` and then grab 2 seperate ratekeys and use them in the Booking step. Hope this helps.

**Comment by Tahir-MatrixAMS** [comment]
Dear @vmavromatis ,
As per your solution. we have changed our Application work flow by creating occupancies array. Now we are facing difference in rate of same room type and board code due to a change in rate key as highlighted below. e.g (GAR-FIT 1,GAR-FIT 2,FITRO)

1. In this case we are not getting any valuable information which can differentiate  the change of rate only field allotment is different which not enough for end user. 

2.   the following data is get from contect api type/room. A single room is offering 999 max paxes how can we justify this. 
e.g ( "code": "BUN.DX-GV",
        "type": "BUN",
        "characteristic": "DX-GV",
        "minPax": 0,
        **"maxPax": 999,**
        "maxAdults": 999,
        "maxChildren": 3,
        "minAdults": 1,
        "description": "BUNGALOW DELUXE GARDEN VIEW",
        "typeDescription": {
            "content": "BUNGALOW"
        },
        "characteristicDescription": {
            "content": "DELUXE GARDEN VIEW"
        } 
)
  
 

--------------------------------------------------------------------------------------------------------------
Request According to your suggestion 
--------------------------------------------------------------------------------------------------------------
{ "stay": { "checkIn": "2018-01-31", "checkOut": "2018-02-01" }, "occupancies": [ { "rooms": 1, "adults": 2, "children": 0, "paxes": [ { "type": "AD", "age": 30 }, { "type": "AD", "age": 20 } ] }, { "rooms": 1, "adults": 2, "children": 0, "paxes": [ { "type": "AD", "age": 33 }, { "type": "AD", "age": 31 } ] }, { "rooms": 1, "adults": 1, "children": 0, "paxes": [ { "type": "AD", "age": 37 } ] } ], "hotels": { "hotel": [ 6807, 6808, 6809, 414660 ] } }

--------------------------------------------------------------------------------------------------------------
Response
--------------------------------------------------------------------------------------------------------------
  
  "hotels": {
        "hotels": [{
            "code": 414660,
            "name": "Jannah Marina Bay Suites",
            "categoryCode": "5EST",
            "categoryName": "5 STARS",
            "destinationCode": "DXB",
            "destinationName": "Dubai",
            "zoneCode": 1,
            "zoneName": "Dubai",
            "latitude": "25.068888",
            "longitude": "55.130494",
            "rooms": [{
                "code": "SUI.DX",
                "name": "SUITE DELUXE",
                "rates": [{
                    "rateKey": "20180131|20180201|W|148|414660|SUI.DX|**GAR-FIT 1**|RO||1~2~0||N@F9641F2C2EF44970AE2CAF6BACF57AF10609",
                    "rateClass": "NOR",
                    "rateType": "BOOKABLE",
                    **"net": "187.38"**,
                    "allotment": 19,
                    "paymentType": "AT_WEB",
                    "packaging": false,
                    "boardCode": "RO",
                    "boardName": "ROOM ONLY",
                    "cancellationPolicies": [{
                        "amount": "187.38",
                        "from": "2018-01-30T23:59:00+04:00"
                    }],
                    "rooms": 1,
                    "adults": 2,
                    "children": 0
                }, {
                    "rateKey": "20180131|20180201|W|148|414660|SUI.DX|**GAR-FIT 1**|RO||1~2~0||N@F9641F2C2EF44970AE2CAF6BACF57AF10609",
                    "rateClass": "NOR",
                    "rateType": "BOOKABLE",
                    **"net": "187.38"**,
                    "allotment": 19,
                    "paymentType": "AT_WEB",
                    "packaging": false,
                    "boardCode": "RO",
                    "boardName": "ROOM ONLY",
                    "rooms": 1,
                    "adults": 2,
                    "children": 0
                }, {
                    "rateKey": "20180131|20180201|W|148|414660|SUI.DX|**GAR-FIT 2**|RO||1~2~0||N@F9641F2C2EF44970AE2CAF6BACF57AF10609",
                    "rateClass": "NOR",
                    "rateType": "BOOKABLE",
                    **"net": "194.81"**,
                    "allotment": 19,
                    "paymentType": "AT_WEB",
                    "packaging": false,
                    "boardCode": "RO",
                    "boardName": "ROOM ONLY",
                    "rooms": 1,
                    "adults": 2,
                    "children": 0
                }, {
                    "rateKey": "20180131|20180201|W|148|414660|SUI.DX|**GAR-FIT 2**|RO||1~2~0||N@F9641F2C2EF44970AE2CAF6BACF57AF10609",
                    "rateClass": "NOR",
                    "rateType": "BOOKABLE",
                    **"net": "194.81"**,
                    "allotment": 19,
                    "paymentType": "AT_WEB",
                    "packaging": false,
                    "boardCode": "RO",
                    "boardName": "ROOM ONLY",
                    "rooms": 1,
                    "adults": 2,
                    "children": 0
                }, {
                    "rateKey": "20180131|20180201|W|148|414660|SUI.DX|**GAR-FIT 1**|RO||1~1~0||N@F9641F2C2EF44970AE2CAF6BACF57AF10609",
                    "rateClass": "NOR",
                    "rateType": "BOOKABLE",
                    **"net": "196.30"**,
                    "allotment": 19,
                    "paymentType": "AT_WEB",
                    "packaging": false,
                    "boardCode": "RO",
                    "boardName": "ROOM ONLY",
                    "rooms": 1,
                    "adults": 1,
                    "children": 0
                }, {
                    "rateKey": "20180131|20180201|W|148|414660|SUI.DX|**GAR-FIT 2**|RO||1~1~0||N@F9641F2C2EF44970AE2CAF6BACF57AF10609",
                    "rateClass": "NOR",
                    "rateType": "BOOKABLE",
                    **"net": "203.73"**,
                    "allotment": 19,
                    "paymentType": "AT_WEB",
                    "packaging": false,
                    "boardCode": "RO",
                    "boardName": "ROOM ONLY",
                    "rooms": 1,
                    "adults": 1,
                    "children": 0
                }, {
                    "rateKey": "20180131|20180201|W|148|414660|SUI.DX|**GAR-FIT 1**|BB||1~1~0||N@F9641F2C2EF44970AE2CAF6BACF57AF10609",
                    "rateClass": "NOR",
                    "rateType": "BOOKABLE",
                    **"net": "205.22"**,
                    "allotment": 19,
                    "paymentType": "AT_WEB",
                    "packaging": false,
                    "boardCode": "BB",
                    "boardName": "BED AND BREAKFAST",
                    "rooms": 1,
                    "adults": 1,
                    "children": 0
                }, {
                    "rateKey": "20180131|20180201|W|148|414660|SUI.DX|**GAR-FIT 1**|BB||1~2~0||N@F9641F2C2EF44970AE2CAF6BACF57AF10609",
                    "rateClass": "NOR",
                    "rateType": "BOOKABLE",
                    **"net": "205.22"**,
                    "allotment": 19,
                    "paymentType": "AT_WEB",
                    "packaging": false,
                    "boardCode": "BB",
                    "boardName": "BED AND BREAKFAST",
                    "rooms": 1,
                    "adults": 2,
                    "children": 0
                }, {
                    "rateKey": "20180131|20180201|W|148|414660|SUI.DX|**GAR-FIT 1**|BB||1~2~0||N@F9641F2C2EF44970AE2CAF6BACF57AF10609",
                    "rateClass": "NOR",
                    "rateType": "BOOKABLE",
                    **"net": "205.22"**,
                    "allotment": 19,
                    "paymentType": "AT_WEB",
                    "packaging": false,
                    "boardCode": "BB",
                    "boardName": "BED AND BREAKFAST",
                    "rooms": 1,
                    "adults": 2,
                    "children": 0
                }, {
                    "rateKey": "20180131|20180201|W|148|414660|SUI.DX|**GAR-FIT 2**|BB||1~1~0||N@F9641F2C2EF44970AE2CAF6BACF57AF10609",
                    "rateClass": "NOR",
                    "rateType": "BOOKABLE",
                    **"net": "212.65"**,
                    "allotment": 19,
                    "paymentType": "AT_WEB",
                    "packaging": false,
                    "boardCode": "BB",
                    "boardName": "BED AND BREAKFAST",
                    "rooms": 1,
                    "adults": 1,
                    "children": 0
                }, {
                    "rateKey": "20180131|20180201|W|148|414660|SUI.DX|**GAR-FIT 2**|BB||1~2~0||N@F9641F2C2EF44970AE2CAF6BACF57AF10609",
                    "rateClass": "NOR",
                    "rateType": "BOOKABLE",
                    **"net": "212.65"**,
                    "allotment": 19,
                    "paymentType": "AT_WEB",
                    "packaging": false,
                    "boardCode": "BB",
                    "boardName": "BED AND BREAKFAST",
                    "rooms": 1,
                    "adults": 2,
                    "children": 0
                }, {
                    "rateKey": "20180131|20180201|W|148|414660|SUI.DX|**GAR-FIT 2**|BB||1~2~0||N@F9641F2C2EF44970AE2CAF6BACF57AF10609",
                    "rateClass": "NOR",
                    "rateType": "BOOKABLE",
                    **"net": "212.65"**,
                    "allotment": 19,
                    "paymentType": "AT_WEB",
                    "packaging": false,
                    "boardCode": "BB",
                    "boardName": "BED AND BREAKFAST",
                    "rooms": 1,
                    "adults": 2,
                    "children": 0
                }, {
                    "rateKey": "20180131|20180201|W|148|414660|SUI.DX|**FIT-RO**|RO||1~2~0||N@F9641F2C2EF44970AE2CAF6BACF57AF10609",
                    "rateClass": "NOR",
                    "rateType": "BOOKABLE",
                    **"net": "245.26"**,
                    "allotment": 30,
                    "paymentType": "AT_WEB",
                    "packaging": false,
                    "boardCode": "RO",
                    "boardName": "ROOM ONLY",
                    "rooms": 1,
                    "adults": 2,
                    "children": 0
                }, {
                    "rateKey": "20180131|20180201|W|148|414660|SUI.DX|**FIT-RO**|RO||1~1~0||N@F9641F2C2EF44970AE2CAF6BACF57AF10609",
                    "rateClass": "NOR",
                    "rateType": "BOOKABLE",
                    **"net": "245.26"**,
                    "allotment": 30,
                    "paymentType": "AT_WEB",
                    "packaging": false,
                    "boardCode": "RO",
                    "boardName": "ROOM ONLY",
                    "rooms": 1,
                    "adults": 1,
                    "children": 0
                }, {
                    "rateKey": "20180131|20180201|W|148|414660|SUI.DX|**FIT-RO**|RO||1~2~0||N@F9641F2C2EF44970AE2CAF6BACF57AF10609",
                    "rateClass": "NOR",
                    "rateType": "BOOKABLE",
                    **"net": "245.26"**,
                    "allotment": 30,
                    "paymentType": "AT_WEB",
                    "packaging": false,
                    "boardCode": "RO",
                    "boardName": "ROOM ONLY",
                    "rooms": 1,
                    "adults": 2,
                    "children": 0
                }, {
                    "rateKey": "20180131|20180201|W|148|414660|SUI.DX|**FIT-RO**|BB||1~1~0||N@F9641F2C2EF44970AE2CAF6BACF57AF10609",
                    "rateClass": "NOR",
                    "rateType": "BOOKABLE",
                    **"net": "271.86"**,
                    "allotment": 30,
                    "paymentType": "AT_WEB",
                    "packaging": false,
                    "boardCode": "BB",
                    "boardName": "BED AND BREAKFAST",
                    "rooms": 1,
                    "adults": 1,
                    "children": 0
                }, {
                    "rateKey": "20180131|20180201|W|148|414660|SUI.DX|**FIT-RO**|BB||1~2~0||N@F9641F2C2EF44970AE2CAF6BACF57AF10609",
                    "rateClass": "NOR",
                    "rateType": "BOOKABLE",
                    **"net": "298.46"**,
                    "allotment": 30,
                    "paymentType": "AT_WEB",
                    "packaging": false,
                    "boardCode": "BB",
                    "boardName": "BED AND BREAKFAST",
                    "rooms": 1,
                    "adults": 2,
                    "children": 0
                }, {
                    "rateKey": "20180131|20180201|W|148|414660|SUI.DX|**FIT-RO**|BB||1~2~0||N@F9641F2C2EF44970AE2CAF6BACF57AF10609",
                    "rateClass": "NOR",
                    "rateType": "BOOKABLE",
                    **"net": "298.46"**,
                    "allotment": 30,
                    "paymentType": "AT_WEB",
                    "packaging": false,
                    "boardCode": "BB",
                    "boardName": "BED AND BREAKFAST",
                    "rooms": 1,
                    "adults": 2,
                    "children": 0
                }, {
                    "rateKey": "20180131|20180201|W|148|414660|SUI.DX|**BAR-RO**|RO||1~2~0||N@F9641F2C2EF44970AE2CAF6BACF57AF10609",
                    "rateClass": "NOR",
                    "rateType": "BOOKABLE",
                    **"net": "1241.12"**,
                    "sellingRate": "1286.63",
                    "hotelMandatory": true,
                    "allotment": 10,
                    "paymentType": "AT_WEB",
                    "packaging": false,
                    "boardCode": "RO",
                    "boardName": "ROOM ONLY",
                    "rooms": 1,
                    "adults": 2,
                    "children": 0,
                    }]
                }, {
                    "rateKey": "20180131|20180201|W|148|414660|SUI.DX|**BAR-RO**|RO||1~2~0||N@F9641F2C2EF44970AE2CAF6BACF57AF10609",
                    "rateClass": "NOR",
                    "rateType": "BOOKABLE",
                    **"net": "1241.12"**,
                    "sellingRate": "1286.63",
                    "hotelMandatory": true,
                    "allotment": 10,
                    "paymentType": "AT_WEB",
                    "packaging": false,
                    "boardCode": "RO",
                    "boardName": "ROOM ONLY",
                    "rooms": 1,
                    "adults": 2,
                    "children": 0,
                    }]
                }, {
                    "rateKey": "20180131|20180201|W|148|414660|SUI.DX|**BAR-RO**|RO||1~1~0||N@F9641F2C2EF44970AE2CAF6BACF57AF10609",
                    "rateClass": "NOR",
                    "rateType": "BOOKABLE",
                    **"net": "1241.12"**,
                    "sellingRate": "1286.63",
                    "hotelMandatory": true,
                    "allotment": 10,
                    "paymentType": "AT_WEB",
                    "packaging": false,
                    "boardCode": "RO",
                    "boardName": "ROOM ONLY",
                    "rooms": 1,
                    "adults": 1,
                    "children": 0,
                    }]
                }, {
                    "rateKey": "20180131|20180201|W|148|414660|SUI.DX|**BAR-RO**|BB||1~1~0||N@F9641F2C2EF44970AE2CAF6BACF57AF10609",
                    "rateClass": "NOR",
                    "rateType": "BOOKABLE",
                    **"net": "1263.28"**,
                    "sellingRate": "1309.60",
                    "hotelMandatory": true,
                    "allotment": 10,
                    "paymentType": "AT_WEB",
                    "packaging": false,
                    "boardCode": "BB",
                    "boardName": "BED AND BREAKFAST",
                    "rooms": 1,
                    "adults": 1,
                    "children": 0,
                    }]
                }, {
                    "rateKey": "20180131|20180201|W|148|414660|SUI.DX|**BAR-RO**|BB||1~2~0||N@F9641F2C2EF44970AE2CAF6BACF57AF10609",
                    "rateClass": "NOR",
                    "rateType": "BOOKABLE",
                    **"net": "1285.44"**,
                    "sellingRate": "1332.58",
                    "hotelMandatory": true,
                    "allotment": 10,
                    "paymentType": "AT_WEB",
                    "packaging": false,
                    "boardCode": "BB",
                    "boardName": "BED AND BREAKFAST",
                    "rooms": 1,
                    "adults": 2,
                    "children": 0,
                    }]
                }, {
                    "rateKey": "20180131|20180201|W|148|414660|SUI.DX|**BAR-RO**|BB||1~2~0||N@F9641F2C2EF44970AE2CAF6BACF57AF10609",
                    "rateClass": "NOR",
                    "rateType": "BOOKABLE",
                    **"net": "1285.44"**,
                    "sellingRate": "1332.58",
                    "hotelMandatory": true,
                    "allotment": 10,
                    "paymentType": "AT_WEB",
                    "packaging": false,
                    "boardCode": "BB",
                    "boardName": "BED AND BREAKFAST",
                    "rooms": 1,
                    "adults": 2,
                    "children": 0,
                    }]
                }]
            },

**Comment by Hamza-MatrixAMS** [comment]
Kindly explain us that how we can differentiate a particular room type with the same board code on the basis of difference in rate and allotment is their any facility or any other advantage that the room with a higher rate is containing. If yes than what is that advantage can be found and we can display a reasonable difference for the rate. Waiting for your Kind reply.

**Comment by vmavromatis** [comment]
I will be now closing this issue as the discussion continues in #120.
