### ISSUE TITLE
API really slow

### ISSUE THREAD

**Issue by arryanggaputra** [hotelbeds-sdk/hotel-api-sdk-php#114]
I'm using postman to try hotelbeds API, but it tooks 438953 ms for each request, is that normal?
![screen shot 2018-01-22 at 6 49 21 pm](https://user-images.githubusercontent.com/4743772/35220140-c758eff0-ffa7-11e7-875a-42b6a939c188.jpg)

**Comment by vmavromatis** [comment]
Hi @arryanggaputra, please make sure you are using this header:
`Accept-Encoding: gzip` so that the response becomes compressed.

Please also mind that you are requesting for a lot of hotels, try to check with fewer and see and the response is still slow. Here's my request with 20 hotels that took 530ms.

![image](https://user-images.githubusercontent.com/8668731/35220379-76a8b580-ff76-11e7-9528-2ade719c03b4.png)

Hope this helps.

**Comment by arryanggaputra** [comment]
@vmavromatis i already add `Accept-Encoding: gzip` also i just removed some hotels, this is my body contents 
```json

{"stay":{"checkIn":"2018-01-26","checkOut":"2018-01-28","shiftDays":2},"occupancies":[{"rooms":"1","adults":"1","children":"0"}],"hotels":{"hotel":[85248,85249,85250,85251,85252,85253,85254,85257,88617,97017,97019,97325,97326,97327,97328,97393,101440,101658,101659,102734]}}
```
the result still same, still confuse with this API request time.

**Comment by arryanggaputra** [comment]
@vmavromatis  now `297411 ms` :D

**Comment by vmavromatis** [comment]
I'm running the same RQ as you and getting <1sec for the response. 

![image](https://user-images.githubusercontent.com/8668731/35220847-34fef502-ff78-11e7-8605-6c2e86d8623d.png)

Please ensure you are not experiencing any networking issues. Can you please specify your continent/country? These responses are definitely not normal.

**Comment by arryanggaputra** [comment]
@vmavromatis  i'm in indonesia. Youtube, and another streaming site is normal. bruh...

**Comment by vmavromatis** [comment]
@arryanggaputra I've had a look in our servers responses and everything looks good including Asia. I will try to investigate further and will let you know if I find anything.

**Comment by arryanggaputra** [comment]
@vmavromatis thank you. Maybe this information can help you.
Internet Provider : Telkom Indonesia
IP Address: 180.247.149.85
![screen shot 2018-01-22 at 3 46 04 pm](https://user-images.githubusercontent.com/4743772/35222778-954557f6-ffb1-11e7-8583-6f17b795401f.jpg)

**Comment by vmavromatis** [comment]
@arryanggaputra Could you please give me your apikey? (NOT secret). Thank you in advance!

**Comment by arryanggaputra** [comment]
@vmavromatis rugk8cjhyehw9mswukes88q7 sure...

**Comment by vmavromatis** [comment]
@arryanggaputra for some strange reason your response is being returned as chunked, even though you requsted gzip...

```Access-Control-Allow-Headers:   x-requested-with, Content-Type, Api-Key Date: Mon, 22 Jan 2018 11:56:57 GMT   Connection: keep-alive Access-Control-Allow-Origin: * Transfer-Encoding:   chunked Content-Type: application/json; charset=UTF-8 X-Application-Context:   hotel-booking-api:int:8383 Access-Control-Allow-Methods: POST, GET, OPTIONS,   DELETE Access-Control-Max-Age: 3600```

We will investigate and get back to you.

**Comment by arryanggaputra** [comment]
@vmavromatis thank you man, I wish there's a good news

**Comment by arryanggaputra** [comment]
@vmavromatis hi there, any information about that problem?

**Comment by vmavromatis** [comment]
Hi @arryanggaputra we are still investigating this issue. A workaround is to switch the Accept header from application/json to application/xml. That seems to return gzipped responses, let me know if this works for you, while we are trying to resolve the case.

**Comment by vmavromatis** [comment]
Hi @arryanggaputra I am closing this since it's not related to the SDK. `Accept-encoding gzip` should return gzipped content and make the request faster; if this does not help please email apitude@hotelbeds.com
