### ISSUE TITLE
Availability response pagination

### ISSUE THREAD

**Issue by Defunktt1** [hotelbeds-sdk/hotel-api-sdk-php#115]
Hello. Is any way to get for example only 20 hotels for the one request?

**Comment by vmavromatis** [comment]
Hello @Defunktt1, thank you for your question. 

Neither BookingAPI nor the SDK support pagination out of the box. The hotels in the response always correspond to the ones in the request. You would have to implement this feature yourself.

**Comment by Defunktt1** [comment]
Okay, thank you.
