### ISSUE TITLE
Inability to log API responses

### ISSUE THREAD

**Issue by andrewchak** [hotelbeds-sdk/hotel-api-sdk-php#116]
Our application needs to log raw API responses from our providers as part of audit requirements. However, this is currently unable with the PHP SDK. The only point where raw response is returned is in file `src/HotelApiClient.php` under the private function `callApi()`, specifically the line:

`return \Zend\Json\Json::decode(mb_convert_encoding($response->getBody(),'UTF-8'), \Zend\Json\Json::TYPE_ARRAY);`

This is used by `__call()` in the line:

`return new $sdkClassRS($this->callApi($req));`

so consumers of the SDK can only receive the wrapper class object that is created from the raw response.

Is it possible to add support for injecting a Logger object in the constructor and an option flag to log raw responses? We are currently using Laravel framework and it would be extremely helpful if we can pass in the Logger instance that we already use.

**Comment by vmavromatis** [comment]
He @andrewchak apologies for the delay, I am flagging this as an enhancement. If I understand correctly the part that you want to log is the auditData. You can already do this for errors with 
```
try{
xxxxx
}catch (\hotelbeds\hotel_api_sdk\types\HotelSDKException $e) {
    $auditData = $e->getAuditData();
 }
```
We will look into adding this ASAP.

**Comment by andrewchak** [comment]
While the `$auditData` is important, that seems to be only for cases where there's error with the API. We are in fact interested to log the raw responses even if there are errors, so it's the actual `$response->getBody()` that we're after.

**Comment by vmavromatis** [comment]
Noted @andrewchak, I will let you know when this is pushed to master.

**Comment by vmavromatis** [comment]
Hello @andrewchak we're sorry we have not followed up with you on this one yet. Was the 2418952628c416df2d454008ccba0236b426e090 commit that was pushed 12 days ago able to suit your needs? You can now do:

`echo $apiClient->getLastResponse();`

Please let me know, and if not, we can look into resolving this ASAP.

**Comment by andrewchak** [comment]
Thanks @vmavromatis, I think this should do the trick. Will let you know should we run into any issues.

**Comment by vmavromatis** [comment]
@andrewchak no problem. I will be closing this issue for now, if anything new comes up feel free to comment and we will re-open it.
