### ISSUE TITLE
issue while getting all the destinations

### ISSUE THREAD

**Issue by skabilram** [hotelbeds-sdk/hotel-api-sdk-php#118]
i m following #14 .
after finishing i got this message.
'hotelbeds\hotel_api_sdk\messages\destinationRQ or hotelbeds\hotel_api_sdk\messages\destinationRS not implemented in SDK'

please guide me. how to view all destinations in one page. (group by country)

**Comment by nathanphan** [comment]
there are a lot of missing features.
Does your company need to have more man force :), please pm hihi

**Comment by skabilram** [comment]
@nathanphan Thank you for replying. 
can you help me to solve this. i just want to view all the destinations on a dropdown.

**Comment by vmavromatis** [comment]
Hi @skabilram, apologies for the late reply, ContentAPI (static content like destinations, hotel descriptions etc) is not implemented yet for PHP. 

In the meantime you can use one of these options: 
-You may use the Java SDK which has ContentAPI implemented
-You may try to retrieve them manually with a tool like Postman and save them in your database or alternatively write a simple Bash script with multiple curl GET requests.
-If you only prefer PHP, there is a community implementation in the Pull Requests, if you want to try out however bear in mind that it's unofficial.

I hope this helps, please follow this issue for any developments: https://github.com/hotelbeds-sdk/hotel-api-sdk-php/issues/90

**Comment by skabilram** [comment]
is there any possibility to use google map city names as destination names?
