### ISSUE TITLE
get hotel list by  location name?

### ISSUE THREAD

**Issue by mjsorribas** [hotelbeds-sdk/hotel-api-sdk-php#12]
Hola, existe algún método para buscar Hoteles por "nombre de Destino" (Localidad)?
O la base de destinos esta disponible?
La verdad sería muy útil esta información.
Saludos

**Comment by alvmunoz** [comment]
hola,
Sí, lo puedes hacer de la siguiente manera:
destination = new Destination("PMI");
esto buscará los hoteles en Palma de Mallorca. 

La base de destinos la tienes disponible lanzando una petición de content-api de destinations. 
Tienes la información aquí:  https://developer.hotelbeds.com/docs/read/apitude_content/location_operations

**Comment by mjsorribas** [comment]
No existe alguna forma de poder descargar la tabla completa de destinos para evitar tener que hacer consultas de destinos constantemente y optimizar la consulta para buscar lo que uno necesita?

**Comment by alvmunoz** [comment]
Puedes hacer la consulta 1 vez y grabarlo en una BD local.
