### ISSUE TITLE
Rate difference per contract code

### ISSUE THREAD

**Issue by Hamza-MatrixAMS** [hotelbeds-sdk/hotel-api-sdk-php#120]
Kindly explain us that how we can differentiate a particular room type with the same board code on the basis of difference in rate and allotment is their any facility or any other advantage that the room with a higher rate is containing. If yes than what is that advantage can be found and we can display a reasonable difference for the rate. Waiting for your Kind reply.

**Request** 
{ "stay": { "checkIn": "2018-01-31", "checkOut": "2018-02-01" }, "occupancies": [ { "rooms": 1, "adults": 2, "children": 0, "paxes": [ { "type": "AD", "age": 30 }, { "type": "AD", "age": 20 } ] }, { "rooms": 1, "adults": 2, "children": 0, "paxes": [ { "type": "AD", "age": 33 }, { "type": "AD", "age": 31 } ] }, { "rooms": 1, "adults": 1, "children": 0, "paxes": [ { "type": "AD", "age": 37 } ] } ], "hotels": { "hotel": [ 6807, 6808, 6809, 414660 ] } }

**Response**
"hotels": {
"hotels": [{
"code": 414660,
"name": "Jannah Marina Bay Suites",
"categoryCode": "5EST",
"categoryName": "5 STARS",
"destinationCode": "DXB",
"destinationName": "Dubai",
"zoneCode": 1,
"zoneName": "Dubai",
"latitude": "25.068888",
"longitude": "55.130494",
"rooms": [{
"code": "SUI.DX",
"name": "SUITE DELUXE",
"rates": [{
"rateKey": "20180131|20180201|W|148|414660|SUI.DX|GAR-FIT 1|RO||120||N@F9641F2C2EF44970AE2CAF6BACF57AF10609",
"rateClass": "NOR",
"rateType": "BOOKABLE",
"net": "187.38",
"allotment": 19,
"paymentType": "AT_WEB",
"packaging": false,
"boardCode": "RO",
"boardName": "ROOM ONLY",
"cancellationPolicies": [{
"amount": "187.38",
"from": "2018-01-30T23:59:00+04:00"
}],
"rooms": 1,
"adults": 2,
"children": 0
}, {
"rateKey": "20180131|20180201|W|148|414660|SUI.DX|GAR-FIT 1|RO||120||N@F9641F2C2EF44970AE2CAF6BACF57AF10609",
"rateClass": "NOR",
"rateType": "BOOKABLE",
"net": "187.38",
"allotment": 19,
"paymentType": "AT_WEB",
"packaging": false,
"boardCode": "RO",
"boardName": "ROOM ONLY",
"rooms": 1,
"adults": 2,
"children": 0
}, {
"rateKey": "20180131|20180201|W|148|414660|SUI.DX|GAR-FIT 2|RO||120||N@F9641F2C2EF44970AE2CAF6BACF57AF10609",
"rateClass": "NOR",
"rateType": "BOOKABLE",
"net": "194.81",
"allotment": 19,
"paymentType": "AT_WEB",
"packaging": false,
"boardCode": "RO",
"boardName": "ROOM ONLY",
"rooms": 1,
"adults": 2,
"children": 0
}, {
"rateKey": "20180131|20180201|W|148|414660|SUI.DX|GAR-FIT 2|RO||120||N@F9641F2C2EF44970AE2CAF6BACF57AF10609",
"rateClass": "NOR",
"rateType": "BOOKABLE",
"net": "194.81",
"allotment": 19,
"paymentType": "AT_WEB",
"packaging": false,
"boardCode": "RO",
"boardName": "ROOM ONLY",
"rooms": 1,
"adults": 2,
"children": 0
}, {
"rateKey": "20180131|20180201|W|148|414660|SUI.DX|GAR-FIT 1|RO||110||N@F9641F2C2EF44970AE2CAF6BACF57AF10609",
"rateClass": "NOR",
"rateType": "BOOKABLE",
"net": "196.30",
"allotment": 19,
"paymentType": "AT_WEB",
"packaging": false,
"boardCode": "RO",
"boardName": "ROOM ONLY",
"rooms": 1,
"adults": 1,
"children": 0
}, {
"rateKey": "20180131|20180201|W|148|414660|SUI.DX|GAR-FIT 2|RO||110||N@F9641F2C2EF44970AE2CAF6BACF57AF10609",
"rateClass": "NOR",
"rateType": "BOOKABLE",
"net": "203.73",
"allotment": 19,
"paymentType": "AT_WEB",
"packaging": false,
"boardCode": "RO",
"boardName": "ROOM ONLY",
"rooms": 1,
"adults": 1,
"children": 0
}, {
"rateKey": "20180131|20180201|W|148|414660|SUI.DX|GAR-FIT 1|BB||110||N@F9641F2C2EF44970AE2CAF6BACF57AF10609",
"rateClass": "NOR",
"rateType": "BOOKABLE",
"net": "205.22",
"allotment": 19,
"paymentType": "AT_WEB",
"packaging": false,
"boardCode": "BB",
"boardName": "BED AND BREAKFAST",
"rooms": 1,
"adults": 1,
"children": 0
}, {
"rateKey": "20180131|20180201|W|148|414660|SUI.DX|GAR-FIT 1|BB||120||N@F9641F2C2EF44970AE2CAF6BACF57AF10609",
"rateClass": "NOR",
"rateType": "BOOKABLE",
"net": "205.22",
"allotment": 19,
"paymentType": "AT_WEB",
"packaging": false,
"boardCode": "BB",
"boardName": "BED AND BREAKFAST",
"rooms": 1,
"adults": 2,
"children": 0
}, {
"rateKey": "20180131|20180201|W|148|414660|SUI.DX|GAR-FIT 1|BB||120||N@F9641F2C2EF44970AE2CAF6BACF57AF10609",
"rateClass": "NOR",
"rateType": "BOOKABLE",
"net": "205.22",
"allotment": 19,
"paymentType": "AT_WEB",
"packaging": false,
"boardCode": "BB",
"boardName": "BED AND BREAKFAST",
"rooms": 1,
"adults": 2,
"children": 0
}, {
"rateKey": "20180131|20180201|W|148|414660|SUI.DX|GAR-FIT 2|BB||110||N@F9641F2C2EF44970AE2CAF6BACF57AF10609",
"rateClass": "NOR",
"rateType": "BOOKABLE",
"net": "212.65",
"allotment": 19,
"paymentType": "AT_WEB",
"packaging": false,
"boardCode": "BB",
"boardName": "BED AND BREAKFAST",
"rooms": 1,
"adults": 1,
"children": 0
}, {
"rateKey": "20180131|20180201|W|148|414660|SUI.DX|GAR-FIT 2|BB||120||N@F9641F2C2EF44970AE2CAF6BACF57AF10609",
"rateClass": "NOR",
"rateType": "BOOKABLE",
"net": "212.65",
"allotment": 19,
"paymentType": "AT_WEB",
"packaging": false,
"boardCode": "BB",
"boardName": "BED AND BREAKFAST",
"rooms": 1,
"adults": 2,
"children": 0
}, {
"rateKey": "20180131|20180201|W|148|414660|SUI.DX|GAR-FIT 2|BB||120||N@F9641F2C2EF44970AE2CAF6BACF57AF10609",
"rateClass": "NOR",
"rateType": "BOOKABLE",
"net": "212.65",
"allotment": 19,
"paymentType": "AT_WEB",
"packaging": false,
"boardCode": "BB",
"boardName": "BED AND BREAKFAST",
"rooms": 1,
"adults": 2,
"children": 0
}]
}]
}
 Issue  #113 
Waiting for kind reply

**Comment by vmavromatis** [comment]
Hello @Hamza-MatrixAMS, 
The difference between contract codes (e.g. GAR-FIT1, GAR-FIT2) is more on the business side, and you may see different prices as a result - sometimes elements such as cancellation policies differ, however this is not the case for the example above. 

In the future kindly direct all APItude related questions to apitude@hotelbeds.com so we can keep this more focused on SDK issues; thank you. Please let me know if you need any more help.

**Comment by Hamza-MatrixAMS** [comment]
Hello @vmavromatis 
In the above response we are seeing the difference in allotment which is not enough for us to describe that why this room's rate is different is their any additional facility available in Order to display in an organized manner.
Firstly I had sent the my issue at apitude@hotelbeds.com but I have got the reply to create the issue at github and we are waiting for your reply on this issue #113 since last 7 days.

**Comment by vmavromatis** [comment]
Hi @Hamza-MatrixAMS,
apologies for the delay. Yes, the fact that you are receiving multiple same ratekeys seems to be an issue with the backend. The developers are already looking into it, I will keep you updated.

In the meantime, can you try requesting with **{ "rooms": 2, "adults": 2, "children": 0,**? Are you still getting unclear differences between contracts?

**Comment by Hamza-MatrixAMS** [comment]
Hi @vmavromatis,
You have suggested us to make request for individual room in issue #113 and now we are again on the same situation at which we were 17 days back.  We have done many changes on our application due to your suggestion and now you are telling us to revert them all we are only revolving around the problem and still it is there where it was seriously it is not helping.

**Comment by vmavromatis** [comment]
Hello @Hamza-MatrixAMS I may have misunderstood what you were trying to achieve in #113. Both requests are valid:
`{ "stay": { "checkIn": "2018-12-15", "checkOut": "2018-12-20" }, "occupancies": [{ "rooms": 1, "adults": 1, "children": 1, "paxes": [{ "type":"CH", "age":"4" }] }, { "rooms": 1, "adults": 1, "children": 1, "paxes": [{ "type":"CH", "age":"8" }] } ], "hotels": { "hotel": [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15, 271] } }`
And
`{ "stay": { "checkIn": "2018-12-15", "checkOut": "2018-12-20" }, "occupancies": [{ "rooms": 2, "adults": 1, "children": 1, "paxes": [{ "type":"CH", "age":"4" }] } ], "hotels": { "hotel": [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15, 271] } }`

The difference is that in the first one you are receiving results for 2 seperate rooms and then need to request booking with 2 seperate ratekeys. You would have got the exact same results if you used one 1~1~1 occupancy and then booked for 2 ratekeys. On the other hand the second request asks explicitly for 2 rooms (each 1 adult and 1 child) as a COMBO. That way, you get less results because some hotels don't give allotment for 2 rooms but give allotment for 1 room. It really depends on what you are trying to achieve. 

I apologise for any inconvenience, please bear in mind that in github we focus excusively on the usage of the SDKs. Are you using our PHP SDK library? It has built-in classes/methods for occupancies i.e. see `\hotelbeds\hotel_api_sdk\helpers\Availability();`

**Comment by vmavromatis** [comment]
As there has been no reply on this one, we will close the issue for now. Please feel free to re-open if you are having any more related questions or issues.
