### ISSUE TITLE
Availability boards filter not available 

### ISSUE THREAD

**Issue by spmsupun** [hotelbeds-sdk/hotel-api-sdk-php#122]
In Availability search, cannot filter boards

https://developer.hotelbeds.com/docs/read/apitude_booking/Availability
(Api Json)
```
"boards": {
  "included": true,
  "board": ["RO", "BB"]
},
```

in the availability  helper (hotel-api-sdk-php/src/helpers/Availability.php)  in the valid Fields there is a attribute ( "board" => "string",) but it doesn't work

**Comment by vmavromatis** [comment]
Pushed a fix to master, please try to get the latest version and try with this code:
```php
$rqData = new \hotelbeds\hotel_api_sdk\helpers\Availability();
$boards = new Boards();
$boards->included=true;
$boards->board=["RO","BB"];
$rqData->boards=$boards;
```

**Comment by spmsupun** [comment]
@vmavromatis  okay i'll check 
thanks 👍

**Comment by vmavromatis** [comment]
I will be closing this as it appears to be resolved. If there are any more issues, please feel free to re-open.
