### ISSUE TITLE
HotelSDKException get error code

### ISSUE THREAD

**Issue by Defunktt1** [hotelbeds-sdk/hotel-api-sdk-php#124]
Hello. Sometimes I get this error:
``Internal Server Error: {"timestamp":1519220615665,"status":500,"error":"Internal Server Error","exception":"java.lang.StackOverflowError","message":"Handler processing failed; nested exception is java.lang.StackOverflowError","path":"/1.0/hotels"}`` 
Is any way to get error code from this response? For example $e->getErrorCode() or something else. 
Thanks.

**Comment by vmavromatis** [comment]
Hi @Defunktt1, were you possibly trying to post this in the Java SDK instead? If so, kinldy post it there, and I will close this issue. To answer your question, yes, all SDKs have the `HotelSDKException` class where you can get the error from. I hope this helps.
