### ISSUE TITLE
BookingList not available all the field that api have

### ISSUE THREAD

**Issue by spmsupun** [hotelbeds-sdk/hotel-api-sdk-php#125]
https://github.com/hotelbeds-sdk/hotel-api-sdk-php/blob/2418952628c416df2d454008ccba0236b426e090/src/helpers/BookingList.php#L21

BookingList  class only available few fiel that api has:  https://developer.hotelbeds.com/docs/read/apitude_booking/booking/BookingList#bookinglist-request

**Comment by vmavromatis** [comment]
Hi @spmsupun, yes you are correct we will update all fields accordingly.

**Comment by vmavromatis** [comment]
@spmsupun sorry for the delay on this, we are looking into it

**Comment by vmavromatis** [comment]
Merge done. Let me know if there are any issues and we can re-open. Thanks!
