### ISSUE TITLE
Multiple Booking Error

### ISSUE THREAD

**Issue by RafaelShkembi** [hotelbeds-sdk/hotel-api-sdk-php#126]
I'm trying to book 2 rooms at the same time but i get this error.
"The distribution of paxes is not correct. The number of rooms specified in the paxes do not match with the requested ones."
If i split the 2 bookings to single bookings then the request is successful and the bookings are confirmed.

This is my json request

```
{
  "holder": {
    "name": "xxxxxxxxx",
    "surname": "xxxxxxxxx"
  },
  "rooms": [
    {
      "rateKey": "20180318|20180324|W|164|156203|APT.B1|CG-BAR|RO||1~1~1|5|N@ABE1E0408AD148C4854BFAB37FF741F71155",
      "paxes": [
        {
          "roomId": 1,
          "type": "AD",
          "name": "xxxxxxxxx",
          "surname": "xxxxxxxxx"
        },
        {
          "roomId": 1,
          "type": "CH",
          "name": "xxxxxxxxx",
          "surname": "xxxxxxxxx"
        }
      ]
    },
    {
      "rateKey": "20180318|20180324|W|164|156203|APT.B1|CG-BAR|RO||1~1~2|10~5|N@ABE1E0408AD148C4854BFAB37FF741F71155",
      "paxes": [
        {
          "roomId": 2,
          "type": "AD",
          "name": "xxxxxxxxx",
          "surname": "xxxxxxxxx"
        },
        {
          "roomId": 2,
          "type": "CH",
          "name": "xxxxxxxxx",
          "surname": "xxxxxxxxx"
        },
        {
          "roomId": 2,
          "type": "CH",
          "name": "xxxxxxxxx",
          "surname": "xxxxxxxxx"
        }
      ]
    }
  ],
  "clientReference": 1520420182
}
```

Is this a problem from our development or is this a problem because we are currently on the test environment?

**Comment by RafaelShkembi** [comment]
@hotelbeds-sdk Anyone?

**Comment by vmavromatis** [comment]
Hello @RafaelShkembi, apologies for the delay, we are looking into it and will get back to you ASAP.

In the future, kindly refer to API issues to apitude@hotelbeds.com because this area is reserved for SDK issues.

**Comment by RafaelShkembi** [comment]
The problem was on the roomId parameter. I had increment the roomId by one on each room. Instead the roomId should stay one. and not two
