### ISSUE TITLE
How to enable destination based search?

### ISSUE THREAD

**Issue by teenu12** [hotelbeds-sdk/hotel-api-sdk-php#128]

**Comment by vmavromatis** [comment]
Hi @teenu12, this feature is disabled by default; if you are interested in this feature please send an email to apitude@hotelbeds.com with your apikey and the team will review your request.

Please be reminded that you can search up to 2000 hotels in the same search and that the **recommended** method is mapping your own lists of hotels against destinations. I hope this helps.
