### ISSUE TITLE
Need exceptions for responses

### ISSUE THREAD

**Issue by spmsupun** [hotelbeds-sdk/hotel-api-sdk-php#129]
**This is not a bug but a suggestion.** https://developer.hotelbeds.com/docs/read/API_Errors
In the api, error messages come as very ugly:

` "error": {
        "code": "PRODUCT_ERROR-05b550dd-5ac6-46e0-b11b-3adf60d67462",
        "message": "ProductException(BOOKING_CONFIRM, Price changed during the booking process"
    }`

in the error we cannot identify which error it is since it doesn't have a unique id. there are few status codes but even there are multiple error messages for same status code:

> 
> **500** 
> 
> SYSTEM_ERROR
> PRODUCT_ERROR
> CONFIGURATION_ERROR
> etc..
> 

so if you could create a exception to make error message better look we can show them to directly to client.

Ex:

**Form This:**
```
"error": {
        "code": "PRODUCT_ERROR-05b550dd-5ac6-46e0-b11b-3adf60d67462",
        "message": "ProductException(BOOKING_CONFIRM, Price changed during the booking process"
    }
```
**To This:**
```
"error": {
        "code": "PRODUCT_ERROR-05b550dd-5ac6-46e0-b11b-3adf60d67462",
         "catogory":"BOOKING_CONFIRM",
         "type":"ProductException",
        "message": "Price changed during the booking process!"
    }
```

So in the exception we can get these values like:

```
$e->getCode();
$e->getCatogory();
$e->getType();
$e->getMessage();
```

**Comment by vmavromatis** [comment]
Hi @spmsupun thank you for this suggestion.

This is something that needs to be implemented in the API itself, and we already have it in the backlog. Unfortunately until it's implemented the best thing to do is to parse the above message. I will post any updates I have regarding this issue on this ticket; but for now I will be closing it as it is not SDK-related. Thank you again.
