### ISSUE TITLE
Error parsing body - doesn't seem to be a chunked message

### ISSUE THREAD

**Issue by aqlx86** [hotelbeds-sdk/hotel-api-sdk-php#13]
testing example codes in readme on top of laravel 5.1 framework produces this error

![localhost 8000](https://cloud.githubusercontent.com/assets/282673/14841574/b6da50e0-0c71-11e6-83b9-5b5301f1c012.png)

https://github.com/zendframework/zend-http/pull/10

**Comment by alvmunoz** [comment]
Hi, the sample code in the readme file works correctly in our tests. Maybe it be the framework laravel 5.1 making some difference when running it?

**Comment by picotrain** [comment]
Thanks, am over the limit of 50 requests per day now. Is there any 
chance that can be increased?


On 17/05/2016 16:32, Álvaro wrote:
>
> Hi, the sample code in the readme file works correctly in our tests. 
> Maybe it be the framework laravel 5.1 making some difference when 
> running it?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/hotelbeds-sdk/hotel-api-sdk-php/issues/13#issuecomment-219736587>
>

-- 
Stephane Wegierski
http://www.livesurf.net
+27 (0)76 429 5790

**Comment by aqlx86** [comment]
Hi @alvmunoz , i also tested the sample code without using any framework, still the same error. 

applying the fix found here, https://github.com/zendframework/zend-http/pull/10  fixes the issue on my end.

**Comment by alvmunoz** [comment]
@picotrain , I think you posted in the wrong thread. If you want to increase your limit of request please contact our team at apitude@hotelbeds.com  

@aqlx86  thanks , that will be helful .

**Comment by davidgv88** [comment]
Hi!! I use CodeIgniter 3.0.6  and produce the same error.

I am testing the example code: https://github.com/hotelbeds-sdk/hotel-api-sdk-php/wiki/Step-by-step-guide-to-start-from-scratch#create-a-sample-application

**Comment by globatum** [comment]
checking in to see if anyone has solved this

**Comment by Zavierazo** [comment]
Hi , try with this change on HotelApiClient.php:

https://github.com/hotelbeds-sdk/hotel-api-sdk-php/pull/23/commits/775c11df18881f4547d080ec30b6aa7756ed3313

And tell me if it solve the problem.

**Comment by globatum** [comment]
I believe the issue has been resolved.

**Comment by davidgv88** [comment]
Hi @globatum 

Yes! The issue has been resolved! Now works OK.

**Comment by albertomoreno** [comment]
Hi @Zavierazo 
I have same problem. A example of body is: 
{"auditData":{"processTime":"1395","timestamp":"2016-09-14 09:34:54.085","requestHost":"80.24.185.216","serverId":"sa37AUX3ROLBLIS.env","environment":"[int]","release":"02ffe3b9dbb4009c2c42e592dc58d4ebd03c682e","internal":"uutyg5j76kqvsyznkudu6td2|UK|03|HC|4|7|1|1|1|N||null,null||||||||1"},"booking":{"reference":"149-177352","clientReference":"PHP_TEST_2","creationDate":"2016-09-14","status":"CONFIRMED","modificationPolicies":{"cancellation":true,"modification":true},"holder":{"name":"ALBERTO","surname":"MORENO"},"hotel":{"checkIn":"2016-09-19","checkOut":"2016-09-20","code":92842,"name":"GHM Monte Gorbea","categoryCode":"1LL","categoryName":"1 LLAVE","destinationCode":"SRN","destinationName":"Sierra Nevada","zoneCode":1,"zoneName":"Pradollano","latitude":"37.092608","longitude":"-3.394927","rooms":[{"status":"CONFIRMED","id":1,"code":"STU.C4","name":"ESTUDIO CAPACIDAD 4","paxes":[{"roomId":1,"type":"AD"},{"roomId":1,"type":"AD"}],"rates":[{"rateClass":"NOR","net":"64.34","sellingRate":"75.00","hotelMandatory":true,"rateComments":"Recogida de llaves en la recepci�n del Hotel GHM Monachil. Entrega a partir de las 17.00 horas. Recepci�n 24 horas.\n\n","paymentType":"AT_WEB","packaging":false,"boardCode":"SC","boardName":"SOLO ALOJAMIENTO","cancellationPolicies":[{"amount":"64.34","from":"2016-09-15T23:59:00+02:00"}],"rooms":1}]}],"totalNet":"64.34","currency":"EUR","supplier":{"name":"HOTELBEDS PRODUCT,S.L.U.","vatNumber":"ESB38877676"}},"totalNet":64.34,"pendingAmount":64.34,"currency":"EUR"}}
and codification is utf-8.
I set adapter with the HotelApiClient constructor's param.

Thanks.
