### ISSUE TITLE
Blank screen laravel when installing packagr

### ISSUE THREAD

**Issue by mbenypangestu** [hotelbeds-sdk/hotel-api-sdk-php#130]
I have an issue blank screen when I install the packages. What's the solution ? I use Laravel 5.2 to install it

**Comment by spmsupun** [comment]
what do you mean blank screen? I've used with laravel 5.2 just fine

**Comment by vmavromatis** [comment]
Hello @mbenypangestu, 

Can you please describe where do you see this blank screen? What method are you using in order to install? Can you show me the error you are getting, if any?

Regards

**Comment by Mygetzu** [comment]
this problem has been solved. i try to upgrade the other package in laravel. Thank you all

**Comment by vmavromatis** [comment]
Great to hear - closing.
