### ISSUE TITLE
Internal server Error : System_error

### ISSUE THREAD

**Issue by advacom** [hotelbeds-sdk/hotel-api-sdk-php#131]
Hi there,

I just made the following request on the non-official disney hotels api:

`{  
   "holder":{  
      "name":"TEST",
      "surname":"TEST"
   },
   "rooms":[  
      {  
         "rateKey":"20180823|20180825|W|197|29646|ROO.ST|ID_B2B_53|BB|NOR_EUROPE|1~1~0||N@B41A3FD35D2F4F3CB388C2E66B1485A11003",
         "paxes":[  
            {  
               "age":18,
               "type":"AD",
               "roomId":1,
               "name":"test",
               "surname":"test"
            }
         ]
      }
   ],
   "clientReference":"TEST"
}`

I'm getting a 'false' returned. Anybody has an idea what the problem could be?
@vmavromatis do you maybe have a second to look at this topic? Thanks!

I have the following error log:

`$data =
hotelbeds\hotel_api_sdk\types\HotelSDKException::__set_state(array(
   'auditData' => 
  hotelbeds\hotel_api_sdk\model\AuditData::__set_state(array(
     'validFields' => 
    array (
      'processTime' => 'float',
      'timestamp' => 'string',
      'serverId' => 'string',
      'requestHost' => 'string',
      'environment' => 'string',
      'release' => 'integer',
    ),
     'fields' => 
    array (
      'processTime' => '36',
      'timestamp' => '2018-04-24 10:08:59.269',
      'requestHost' => '85.234.225.102',
      'serverId' => 'sa3RKSJACHXE79K.env#PL',
      'environment' => '[int]',
      'release' => '5c2a98762e8da116cf86a57a17c9db9d2e4d80eb',
      'token' => 'adeba46e-43b0-4a8f-978f-8c04439439e5',
      'internal' => '0|B41A3FD35D2F4F3CB388C2E66B1485A11003|NL|05|1|88|||||||||||R|256|2|1~1~1~0||4|TOURICO|4|qnnv8npksm227vv5nscjwdzs|||',
    ),
  )),
   **'message' => 'Internal Server Error: SYSTEM_ERROR-adeba46e-43b0-4a8f-978f-8c04439439e5 Internal server error',**
   'string' => '',
   'code' => 0,
   'file' => '/home/magicalde/public_html/hotelbeds/api/src/HotelApiClient.php',
   'line' => 184,
   'trace' => 
  array (
    0 => 
    array (
      'file' => '/home/magicalde/public_html/hotelbeds/api/src/HotelApiClient.php',
      'line' => 153,
      'function' => 'callApi',
      'class' => 'hotelbeds\\hotel_api_sdk\\HotelApiClient',
      'type' => '->',
      'args' => 
      array (
        0 => 
        hotelbeds\hotel_api_sdk\messages\BookingConfirmRQ::__set_state(array(
           'request' => 
          Zend\Http\Request::__set_state(array(
             'method' => 'POST',
             'allowCustomMethods' => true,
             'uri' => 
            Zend\Uri\Http::__set_state(array(
               'validHostTypes' => 27,
               'user' => NULL,
               'password' => NULL,
               'scheme' => 'https',
               'userInfo' => NULL,
               'host' => 'api.test.hotelbeds.com',
               'port' => 443,
               'path' => '/hotel-api/1.0/bookings',
               'query' => NULL,
               'fragment' => NULL,
            )),
             'queryParams' => 
            Zend\Stdlib\Parameters::__set_state(array(
            )),
             'postParams' => NULL,
             'fileParams' => NULL,
             'version' => '1.1',
             'headers' => 
            Zend\Http\Headers::__set_state(array(
               'pluginClassLoader' => 
              Zend\Http\HeaderLoader::__set_state(array(
                 'plugins' => 
                array (
                  'accept' => 'Zend\\Http\\Header\\Accept',
                  'acceptcharset' => 'Zend\\Http\\Header\\AcceptCharset',
                  'acceptencoding' => 'Zend\\Http\\Header\\AcceptEncoding',
                  'acceptlanguage' => 'Zend\\Http\\Header\\AcceptLanguage',
                  'acceptranges' => 'Zend\\Http\\Header\\AcceptRanges',
                  'age' => 'Zend\\Http\\Header\\Age',
                  'allow' => 'Zend\\Http\\Header\\Allow',
                  'authenticationinfo' => 'Zend\\Http\\Header\\AuthenticationInfo',
                  'authorization' => 'Zend\\Http\\Header\\Authorization',
                  'cachecontrol' => 'Zend\\Http\\Header\\CacheControl',
                  'connection' => 'Zend\\Http\\Header\\Connection',
                  'contentdisposition' => 'Zend\\Http\\Header\\ContentDisposition',
                  'contentencoding' => 'Zend\\Http\\Header\\ContentEncoding',
                  'contentlanguage' => 'Zend\\Http\\Header\\ContentLanguage',
                  'contentlength' => 'Zend\\Http\\Header\\ContentLength',
                  'contentlocation' => 'Zend\\Http\\Header\\ContentLocation',
                  'contentmd5' => 'Zend\\Http\\Header\\ContentMD5',
                  'contentrange' => 'Zend\\Http\\Header\\ContentRange',
                  'contenttransferencoding' => 'Zend\\Http\\Header\\ContentTransferEncoding',
                  'contenttype' => 'Zend\\Http\\Header\\ContentType',
                  'cookie' => 'Zend\\Http\\Header\\Cookie',
                  'date' => 'Zend\\Http\\Header\\Date',
                  'etag' => 'Zend\\Http\\Header\\Etag',
                  'expect' => 'Zend\\Http\\Header\\Expect',
                  'expires' => 'Zend\\Http\\Header\\Expires',
                  'from' => 'Zend\\Http\\Header\\From',
                  'host' => 'Zend\\Http\\Header\\Host',
                  'ifmatch' => 'Zend\\Http\\Header\\IfMatch',
                  'ifmodifiedsince' => 'Zend\\Http\\Header\\IfModifiedSince',
                  'ifnonematch' => 'Zend\\Http\\Header\\IfNoneMatch',
                  'ifrange' => 'Zend\\Http\\Header\\IfRange',
                  'ifunmodifiedsince' => 'Zend\\Http\\Header\\IfUnmodifiedSince',
                  'keepalive' => 'Zend\\Http\\Header\\KeepAlive',
                  'lastmodified' => 'Zend\\Http\\Header\\LastModified',
                  'location' => 'Zend\\Http\\Header\\Location',
                  'maxforwards' => 'Zend\\Http\\Header\\MaxForwards',
                  'origin' => 'Zend\\Http\\Header\\Origin',
                  'pragma' => 'Zend\\Http\\Header\\Pragma',
                  'proxyauthenticate' => 'Zend\\Http\\Header\\ProxyAuthenticate',
                  'proxyauthorization' => 'Zend\\Http\\Header\\ProxyAuthorization',
                  'range' => 'Zend\\Http\\Header\\Range',
                  'referer' => 'Zend\\Http\\Header\\Referer',
                  'refresh' => 'Zend\\Http\\Header\\Refresh',
                  'retryafter' => 'Zend\\Http\\Header\\RetryAfter',
                  'server' => 'Zend\\Http\\Header\\Server',
                  'setcookie' => 'Zend\\Http\\Header\\SetCookie',
                  'te' => 'Zend\\Http\\Header\\TE',
                  'trailer' => 'Zend\\Http\\Header\\Trailer',
                  'transferencoding' => 'Zend\\Http\\Header\\TransferEncoding',
                  'upgrade' => 'Zend\\Http\\Header\\Upgrade',
                  'useragent' => 'Zend\\Http\\Header\\UserAgent',
                  'vary' => 'Zend\\Http\\Header\\Vary',
                  'via' => 'Zend\\Http\\Header\\Via',
                  'warning' => 'Zend\\Http\\Header\\Warning',
                  'wwwauthenticate' => 'Zend\\Http\\Header\\WWWAuthenticate',
                ),
              )),
               'headersKeys' => 
              array (
                0 => 'apikey',
                1 => 'xsignature',
                2 => 'accept',
                3 => 'acceptcharset',
                4 => 'acceptenconding',
                5 => 'contenttype',
              ),
               'headers' => 
              array (
                0 => 
                Zend\Http\Header\GenericHeader::__set_state(array(
                   'fieldName' => 'Api-Key',
                   'fieldValue' => 'qnnv8npksm227vv5nscjwdzs',
                )),
                1 => 
                Zend\Http\Header\GenericHeader::__set_state(array(
                   'fieldName' => 'X-Signature',
                   'fieldValue' => '88b1a2cc22ba267eacf71ec5f39309832cf9071a3d9a12bd6503d2092c9106a0',
                )),
                2 => 
                Zend\Http\Header\Accept::__set_state(array(
                   'regexAddType' => '#^([a-zA-Z+-]+|\\*)/(\\*|[a-zA-Z0-9+-]+)$#',
                   'fieldValueParts' => 
                  array (
                    0 => 
                    Zend\Http\Header\Accept\FieldValuePart\AcceptFieldValuePart::__set_state(array(
                       'internalValues' => 
                      stdClass::__set_state(array(
                         'typeString' => 'application/json',
                         'type' => 'application',
                         'subtype' => 'json',
                         'subtypeRaw' => 'json',
                         'format' => 'json',
                         'priority' => 1,
                         'params' => 
                        array (
                        ),
                         'raw' => 'application/json',
                      )),
                       'matchedAgainst' => NULL,
                    )),
                  ),
                   'sorted' => false,
                )),
                3 => 
                Zend\Http\Header\AcceptCharset::__set_state(array(
                   'regexAddType' => '#^([a-zA-Z0-9+-]+|\\*)$#',
                   'fieldValueParts' => 
                  array (
                    0 => 
                    Zend\Http\Header\Accept\FieldValuePart\CharsetFieldValuePart::__set_state(array(
                       'internalValues' => 
                      stdClass::__set_state(array(
                         'typeString' => 'utf-8',
                         'type' => 'utf-8',
                         'subtype' => '*',
                         'subtypeRaw' => 'utf-8',
                         'format' => '*',
                         'priority' => 1,
                         'params' => 
                        array (
                        ),
                         'raw' => 'utf-8',
                      )),
                       'matchedAgainst' => NULL,
                    )),
                  ),
                   'sorted' => false,
                )),
                4 => 
                Zend\Http\Header\GenericHeader::__set_state(array(
                   'fieldName' => 'Accept-Enconding',
                   'fieldValue' => 'gzip, deflate',
                )),
                5 => 
                Zend\Http\Header\ContentType::__set_state(array(
                   'mediaType' => 'application/json',
                   'parameters' => 
                  array (
                  ),
                   'value' => 'application/json',
                )),
              ),
            )),
             'metadata' => 
            array (
            ),
             'content' => '{"holder":{"name":"TEST","surname":"TEST"},"rooms":[{"rateKey":"20180823|20180825|W|197|29646|ROO.ST|ID_B2B_53|BB|NOR_EUROPE|1~1~0||N@B41A3FD35D2F4F3CB388C2E66B1485A11003","paxes":[{"age":18,"type":"AD","roomId":1,"name":"lars","surname":"rasmussen"}]}],"clientReference":"TEST"}',
          )),
           'baseUri' => 
          Zend\Uri\Http::__set_state(array(
             'validHostTypes' => 27,
             'user' => NULL,
             'password' => NULL,
             'scheme' => 'https',
             'userInfo' => NULL,
             'host' => 'api.test.hotelbeds.com',
             'port' => 443,
             'path' => '/hotel-api/1.0/bookings',
             'query' => NULL,
             'fragment' => NULL,
          )),
           'dataRQ' => 
          hotelbeds\hotel_api_sdk\helpers\Booking::__set_state(array(
             'validFields' => 
            array (
              'language' => 'string',
              'holder' => 'hotelbeds\\hotel_api_sdk\\model\\Holder',
              'rooms' => 'array',
              'clientReference' => 'string',
              'paymentData' => 'hotelbeds\\hotel_api_sdk\\model\\PaymentData',
              'remark' => 'string',
              'platform' => 'integer',
            ),
             'fields' => 
            array (
              'holder' => 
              hotelbeds\hotel_api_sdk\model\Holder::__set_state(array(
                 'validFields' => 
                array (
                  'name' => 'string',
                  'surname' => 'string',
                ),
                 'fields' => 
                array (
                  'name' => 'TEST',
                  'surname' => 'TEST',
                ),
              )),
              'rooms' => 
              array (
                0 => 
                hotelbeds\hotel_api_sdk\model\BookingRoom::__set_state(array(
                   'validFields' => 
                  array (
                    'rateKey' => 'string',
                    'paxes' => 'array',
                  ),
                   'fields' => 
                  array (
                    'rateKey' => '20180823|20180825|W|197|29646|ROO.ST|ID_B2B_53|BB|NOR_EUROPE|1~1~0||N@B41A3FD35D2F4F3CB388C2E66B1485A11003',
                    'paxes' => 
                    array (
                      0 => 
                      hotelbeds\hotel_api_sdk\model\Pax::__set_state(array(
                         'validFields' => 
                        array (
                          'roomId' => 'integer',
                          'type' => 'string',
                          'age' => 'integer',
                          'name' => 'string',
                          'surname' => 'string',
                        ),
                         'fields' => 
                        array (
                          'age' => 18,
                          'type' => 'AD',
                          'roomId' => 1,
                          'name' => 'lars',
                          'surname' => 'rasmussen',
                        ),
                      )),
                    ),
                  ),
                )),
              ),
              'clientReference' => 'TEST',
            ),
          )),
        )),
      ),
    ),
    1 => 
    array (
      'file' => '/home/magicalde/public_html/hotelbeds/unofficialapi/classes/Booking-unofficial.php',
      'line' => 110,
      'function' => '__call',
      'class' => 'hotelbeds\\hotel_api_sdk\\HotelApiClient',
      'type' => '->',
      'args' => 
      array (
        0 => 'BookingConfirm',
        1 => 
        array (
          0 => 
          hotelbeds\hotel_api_sdk\helpers\Booking::__set_state(array(
             'validFields' => 
            array (
              'language' => 'string',
              'holder' => 'hotelbeds\\hotel_api_sdk\\model\\Holder',
              'rooms' => 'array',
              'clientReference' => 'string',
              'paymentData' => 'hotelbeds\\hotel_api_sdk\\model\\PaymentData',
              'remark' => 'string',
              'platform' => 'integer',
            ),
             'fields' => 
            array (
              'holder' => 
              hotelbeds\hotel_api_sdk\model\Holder::__set_state(array(
                 'validFields' => 
                array (
                  'name' => 'string',
                  'surname' => 'string',
                ),
                 'fields' => 
                array (
                  'name' => 'TEST',
                  'surname' => 'TEST',
                ),
              )),
              'rooms' => 
              array (
                0 => 
                hotelbeds\hotel_api_sdk\model\BookingRoom::__set_state(array(
                   'validFields' => 
                  array (
                    'rateKey' => 'string',
                    'paxes' => 'array',
                  ),
                   'fields' => 
                  array (
                    'rateKey' => '20180823|20180825|W|197|29646|ROO.ST|ID_B2B_53|BB|NOR_EUROPE|1~1~0||N@B41A3FD35D2F4F3CB388C2E66B1485A11003',
                    'paxes' => 
                    array (
                      0 => 
                      hotelbeds\hotel_api_sdk\model\Pax::__set_state(array(
                         'validFields' => 
                        array (
                          'roomId' => 'integer',
                          'type' => 'string',
                          'age' => 'integer',
                          'name' => 'string',
                          'surname' => 'string',
                        ),
                         'fields' => 
                        array (
                          'age' => 18,
                          'type' => 'AD',
                          'roomId' => 1,
                          'name' => 'lars',
                          'surname' => 'rasmussen',
                        ),
                      )),
                    ),
                  ),
                )),
              ),
              'clientReference' => 'TEST',
            ),
          )),
        ),
      ),
    ),
    2 => 
    array (
      'file' => '/home/magicalde/public_html/hotelbeds/unofficialapi/classes/Booking-unofficial.php',
      'line' => 110,
      'function' => 'BookingConfirm',
      'class' => 'hotelbeds\\hotel_api_sdk\\HotelApiClient',
      'type' => '->',
      'args' => 
      array (
        0 => 
        hotelbeds\hotel_api_sdk\helpers\Booking::__set_state(array(
           'validFields' => 
          array (
            'language' => 'string',
            'holder' => 'hotelbeds\\hotel_api_sdk\\model\\Holder',
            'rooms' => 'array',
            'clientReference' => 'string',
            'paymentData' => 'hotelbeds\\hotel_api_sdk\\model\\PaymentData',
            'remark' => 'string',
            'platform' => 'integer',
          ),
           'fields' => 
          array (
            'holder' => 
            hotelbeds\hotel_api_sdk\model\Holder::__set_state(array(
               'validFields' => 
              array (
                'name' => 'string',
                'surname' => 'string',
              ),
               'fields' => 
              array (
                'name' => 'TEST',
                'surname' => 'TEST',
              ),
            )),
            'rooms' => 
            array (
              0 => 
              hotelbeds\hotel_api_sdk\model\BookingRoom::__set_state(array(
                 'validFields' => 
                array (
                  'rateKey' => 'string',
                  'paxes' => 'array',
                ),
                 'fields' => 
                array (
                  'rateKey' => '20180823|20180825|W|197|29646|ROO.ST|ID_B2B_53|BB|NOR_EUROPE|1~1~0||N@B41A3FD35D2F4F3CB388C2E66B1485A11003',
                  'paxes' => 
                  array (
                    0 => 
                    hotelbeds\hotel_api_sdk\model\Pax::__set_state(array(
                       'validFields' => 
                      array (
                        'roomId' => 'integer',
                        'type' => 'string',
                        'age' => 'integer',
                        'name' => 'string',
                        'surname' => 'string',
                      ),
                       'fields' => 
                      array (
                        'age' => 18,
                        'type' => 'AD',
                        'roomId' => 1,
                        'name' => 'lars',
                        'surname' => 'rasmussen',
                      ),
                    )),
                  ),
                ),
              )),
            ),
            'clientReference' => 'TEST',
          ),
        )),
      ),
    ),
    3 => 
    array (
      'file' => '/home/magicalde/public_html/hotelbeds/page_templates/bestatigungun.php',
      'line' => 33,
      'function' => 'hotelbedBookingConfirm',
      'class' => 'Booking',
      'type' => '->',
      'args' => 
      array (
        0 => '20180823|20180825|W|197|29646|ROO.ST|ID_B2B_53|BB|NOR_EUROPE|1~1~0||N@B41A3FD35D2F4F3CB388C2E66B1485A11003',
      ),
    ),
    4 => 
    array (
      'file' => '/home/magicalde/public_html/hotelbeds/pagina.php',
      'line' => 27,
      'args' => 
      array (
        0 => '/home/magicalde/public_html/hotelbeds/page_templates/bestatigungun.php',
      ),
      'function' => 'include',
    ),
    5 => 
    array (
      'file' => '/home/magicalde/public_html/hotelbeds/index.php',
      'line' => 338,
      'args' => 
      array (
        0 => '/home/magicalde/public_html/hotelbeds/pagina.php',
      ),
      'function' => 'include',
    ),
  ),
   'previous' => NULL,
));
`

**Comment by spmsupun** [comment]
Hello @advacom this is not a issue with hotel-api-sdk-php but in the api. i got the same error while confirming a booking with rateType is  recheck (even I do the recheck process) and when i contact the aptitude team they said it because i was in the test api. hopes this helps.

**Comment by advacom** [comment]
Hi There,

Thanks for your quick response. Did hotelbeds offer a solution or a fix? How did you work around it?

Thanks again,

**Comment by spmsupun** [comment]
I had to book only rateType is BOOKABLE rooms, and had to book one room at a time. i mean if you want to book multiple rooms(multiple rateKey) in same hotel you have to confirm multiple time. Their support is very poor and they don't even know lot of things in their own api.

**Comment by vmavromatis** [comment]
Hello @advacom, this is an Internal Server Error and as @spmsupun has said this has to do with the API and not the SDK. There is an issue on INT where you cannot book RECHECK type but only BOOKABLE ratekeys - please try to book BOOKABLE instead. 

INT is meant for experimenting/setting up and is not as stable as LIVE, thus you may notice some odd behavior such as in this case. I will now be closing this as it is not SDK-related. Please let me know if you need any help.

@spmsupun Our support team is trying their best to assist all clients. Can you kindly direct any feedback to the apitude@hotelbeds.com address. Thank you very much in advance.

**Comment by advacom** [comment]
Hi @vmavromatis, Thanks for your quick response. 

Do I understand correctly that I have to skip the RECHECK (isn't this mandatory to proceed to the certification)?

I'm not sure what you mean by INT


Thanks again,

**Comment by vmavromatis** [comment]
Sorry, INT (client INTegration) is just an alias for TEST environment. Do you need to book RECHECK for the certification? The team is currently working on fixing the bug on this environment (it doesn't occur on LIVE). I will keep you updated.
