### ISSUE TITLE
Bookin Confirmation Error

### ISSUE THREAD

**Issue by TheStoker** [hotelbeds-sdk/hotel-api-sdk-php#133]
Hello,

I'm Facing Following Error whenever i try to make a booking while integrating the hotelbeds api. 

`Message: Error while sending request, reason: ProductException(BOOKING_CONFIRM, There are stop sales on the dates indicated)`

I know it means that the hotels have closed bookings on those dates. **Unfortunately I cannot find any date on which any hotels have bookings open. Can you tell me one or 2 hotels on some dates so i can test while coding.** 

Regards.

**Comment by MasoodRehman** [comment]
I am submitting the rateKey of the following room rate object in booking request but every time the api return me the same error response.
Here is the room rateKey object:

{
    "rateKey": "20180510|20180520|W|53|9|DBT.ST|OFE-EB BB|BB||1~2~0||N@9D7047DB244A4A4E823173C9C161B0011025",
     "rateClass": "NOR",
      "rateType": "BOOKABLE",
       "net": "4721.70",
       "allotment": 32,
       "paymentType": "AT_WEB",
       "packaging": false,
       "boardCode": "BB",
       "boardName": "BED AND BREAKFAST",
       "cancellationPolicies": [
           {
               "amount": "472.17",
               "from": "2018-05-08T23:59:00+01:00"
           },
           {
               "amount": "4721.70",
               "from": "2018-05-09T23:59:00+01:00"
           }
       ],
       "rooms": 1,
       "adults": 2,
       "children": 0
}

And here is the final booking request

{
  "holder": {
    "name": "HolderFirstName",
    "surname": "HolderLastName"
  },
  "rooms": [{
    "rateKey": "20180510|20180520|W|53|9|DBT.ST|OFE-EB BB|BB||1~2~0||N@9D7047DB244A4A4E823173C9C161B0011025",
    "paxes": [{
      "roomId": "1",
      "type": "AD",
      "name": "Adult Name",
      "surname": "Surname"
    }]
  }],
  "clientReference": "IntegrationAgency",
  "remark": "Booking remarks are to be written here."
}

The error response I get on every request is given bellow.

{
    "auditData": {
        "processTime": "712",
        "timestamp": "2018-05-05 10:35:29.894",
        "requestHost": "203.99.187.242",
        "serverId": "sa3RKSJACHXE79K.env#PL",
        "environment": "[int]",
        "release": "4e21884df45756e39e474aab3fe4fbc6adfcbcb0",
        "token": "62277b40-8bd6-45c8-bae6-0c6462d30a66",
        "internal": "0|9D7047DB244A4A4E823173C9C161B0011025|TR|07|4|52||HOTEL,HOSTEL|||||||||R|18|10|1~1~2~0||0||0|6e79tsxfyxxvp7qdkfac8kz3|||"
    },
    "error": {
        "code": "PRODUCT_ERROR-62277b40-8bd6-45c8-bae6-0c6462d30a66",
        "message": "ProductException(BOOKING_CONFIRM, There are stop sales on the dates indicated)"
    }
}

Don't know why I facing this issue, no detail mentioned in documentation regarding this error message.

Thank you.

**Comment by MasoodRehman** [comment]
I tried on different rooms but the result is same :(

**Comment by spmsupun** [comment]
I this related to hotelbeds api. i've faced same scenario  and they said it because it's a test api.
try with a ratekey is a BOOKABLE, rate class: NOR and allotments has more than 20

**Comment by vmavromatis** [comment]
Hi all, 

We are aware of this issue and looking into it as we speak.
I will keep you updated - please keep in mind that this is not SDK related but related to the API and specifically only the TEST environment.

Apologies for any inconvenience.

Kind regards,
Vasilis

**Comment by TheStoker** [comment]
Sure, We're Waiting For Your Reply. 

Thanks.

**Comment by TheStoker** [comment]
@vmavromatis Any Updates ?

**Comment by vmavromatis** [comment]
Hi @TheStoker, the team still reviewing the issue - tomorrow 16th of May there will be a refresh of the TEST environment between 12:30-14:00 CET - it might resolve the issue. Please try booking after that time.

Regards

**Comment by TheStoker** [comment]
Sure, Thanks @vmavromatis

**Comment by MasoodRehman** [comment]
@vmavromatis I am facing an issue on booking kindly preview the following request and response.

**Endpoint: https://api.test.hotelbeds.com/hotel-api/1.0/bookings**
**Request Payload**:
```
{
  "holder": {
    "name": "HolderFirstName",
    "surname": "HolderLastName"
  },
  "rooms": [{
    "rateKey": "20180520|20180525|W|53|89321|SGL.ST|CG-TODOS RO|RO||1~1~0||N@4A6CB73760F34D7A907CCEE37AFD81DD1215",
    "paxes": [{
      "roomId": "1",
      "type": "AD",
      "name": "First Adult Name",
      "surname": "Surname"
    },
    {
      "roomId": "1",
      "type": "AD",
      "name": "Second Adult Name",
      "surname": "Surname"
    }]
  }],
  "clientReference": "IntegrationAgency",
  "remark": "Booking remarks are to be written here."
}
```

**Response:**

```
{
    "auditData": {
        "processTime": "4",
        "timestamp": "2018-05-18 12:19:24.013",
        "requestHost": "203.99.187.242",
        "serverId": "sa3RKSJACHXE79K.env",
        "environment": "[int]",
        "release": "4e21884df45756e39e474aab3fe4fbc6adfcbcb0",
        "token": "d3ed5a2a-17a5-45eb-94ce-d8cf9c51944d",
        "internal": "0|4A6CB73760F34D7A907CCEE37AFD81DD1215|TR|05|1|4|||||||||||R|4|5|1~1~1~0||0||0|6e79tsxfyxxvp7qdkfac8kz3|||"
    },
    "error": {
        "code": "INVALID_DATA-d3ed5a2a-17a5-45eb-94ce-d8cf9c51944d",
        "message": "Invalid data. Error at property rooms: The distribution of paxes is not correct. The number of adult specified in the paxes do not match with the requested ones."
    }
}
```

What i guess from the response is that, this error usually occurred when the number of adults does not matched in booking request with the availability request, But my both request has same adults number.

Here is my hotel **Availability Request**:

```
{
  "language": "ENG",
  "stay": {
      "checkIn": "2018-05-20",
      "checkOut": "2018-05-25"
  },
  "occupancies": [{
      "rooms": 1,
      "adults": 2,
      "children": 0
  }],
  "hotels": {
        "hotel": [1,2,3,4,5,6,7,8,9,10]
   },
  "accommodations": ["HOTEL","HOSTEL"],
  "keywords": {
		"keyword": [34,38]
   },
   "filter": {
		"minRate": 100,
		"maxRate": 1700,
		"minCategory": 3
   }
}
```

Kindly @vmavromatis check the above issue.

**Comment by MasoodRehman** [comment]
Suggesion: 
@vmavromatis the following is the net amount value in response of booking request, the value is too long, should it not be round value.

totalNet: 1094.6199999999998908606357872486114501953125
pendingAmount: 1094.6199999999998908606357872486114501953125

Now the booking request is functional after 16 May, it's working now.

**Comment by MasoodRehman** [comment]
Hello @vmavromatis I facing again the old issue in booking request, on each and every type of rate key I am getting the the following response.

> ProductException(BOOKING_CONFIRM, Price changed during the booking process)

Almost on every request with payment type **AT_WEB** and rate type **Bookable** I am receiving back the above error from API.

The endpoint I am using for AT_WEB payment type is the following 
https://api.test.hotelbeds.com/hotel-api/1.2/bookings (Not sending credit card details)

**Comment by MasoodRehman** [comment]
I am not using SDK, it being printing from API.

**Comment by vmavromatis** [comment]
Hi @MasoodRehman apologies for the late reply. Can you please give me the request that caused the erroneous response? I can help but in the future I will kindly urge you to direct API related issues to apitude@hotelbeds.com as this space is reserved for SDK issues. Thank you in advance.

**Comment by vmavromatis** [comment]
Feel free to re-open if you are still facing this issue
