### ISSUE TITLE
API Response empty

### ISSUE THREAD

**Issue by MasoodRehman** [hotelbeds-sdk/hotel-api-sdk-php#137]
Hi @vmavromatis hope my message found you well, I am facing new issue regarding API response, the API stop working today and it returns **Developer Inactive** in response.

**Request**
```
{
  "language": "ENG",
  "stay": {
      "checkIn": "2018-05-25",
      "checkOut": "2018-05-27"
  },
  "occupancies": [{
      "rooms": 1,
      "adults": 2,
      "children": 0
  }],
  "hotels": {
        "hotel": [1,2,3,4,5,6,7,8,9,10]
   },
  "accommodations": ["HOTEL","HOSTEL"],
  "keywords": {
		"keyword": [34,38]
   },
   "filter": {
		"minRate": 100,
		"maxRate": 1700,
		"minCategory": 3
   }
}
```

**Response**
Developer Inactive

**Screen shot**
http://jmp.sh/G02L5R7

**Comment by vmavromatis** [comment]
Hi @MasoodRehman, is this fixed? - I see you closed it. In general, when you get a 403 always check the response headers for more info.
Kind regards

**Comment by MasoodRehman** [comment]
yes i realized later the client inactive the keys, so that why i closed it.

**Comment by Ruan7One5** [comment]
Receiving a developer inactive

Although I have created the application, do I need to get pre-production access before this works?
Response headers:
Connection →keep-alive
Content-Length →27
Content-Type →text/xml
Date →Thu, 20 Jun 2019 11:07:04 GMT
Server →Mashery Proxy
X-Error-Detail-Header →Account Inactive
X-Mashery-Error-Code →ERR_403_DEVELOPER_INACTIVE
X-Mashery-Responder →prod-j-worker-hotelbeds-eu-west-1c-24.mashery.com
