### ISSUE TITLE
Getting all Destinations from Hotelbeds

### ISSUE THREAD

**Issue by picotrain** [hotelbeds-sdk/hotel-api-sdk-php#14]
I've been coding a little bit with the HotelBeds
[cities.txt](https://github.com/hotelbeds-sdk/hotel-api-sdk-php/files/256897/cities.txt)

[Dest.txt](https://github.com/hotelbeds-sdk/hotel-api-sdk-php/files/256900/Dest.txt)
[DestinationRQ.txt](https://github.com/hotelbeds-sdk/hotel-api-sdk-php/files/256902/DestinationRQ.txt)
[DestinationRS.txt](https://github.com/hotelbeds-sdk/hotel-api-sdk-php/files/256904/DestinationRS.txt)
[Destination.txt](https://github.com/hotelbeds-sdk/hotel-api-sdk-php/files/256905/Destination.txt)

 API and the SDK and it's all great. I'm attempting to get a result of all the destinations, countries and cities list.

Using the Availability example from the documentation, I've understood to create a new helper, use the model Destination already listed in the SDK, and created a destinationRQ.php and destinationRS.php file. All the files needed to run what I am doing are attached. Somewhere I am getting lost and confused in the messages, models, helpers and general framework layout. I was hoping you could help me out to get my head around the way all the methods are being used for HotelBeds.

I get to the DestinationRQ.php file where it throws an error saying "Fatal error: Undefined class constant 'DESTINATION' in C:\vendor\hotelbeds\hotel-api-sdk-php\src\messages\DestinationRQ.php on line 23".

I've tried several fixes and amendments without any luck and am puzzled as to what else to try.

**Comment by alvmunoz** [comment]
Hi @picotrain ,  you cannot retrieve the destinations list with the current SDK. This SDK is only for BookingAPI, the part of destinations is in ContentAPI , which is not included in the SDK. 
For more information on this, refer to the documentation: https://developer.hotelbeds.com/docs/read/APITUDE_CONTENT

**Comment by picotrain** [comment]
Aha, right, yes, I got it now. Thanks!

**Comment by roman-briazgalov** [comment]
picotrain, can You share what did You got? Did you get the list of all destinations?

**Comment by skabilram** [comment]
@picotrain can you share your final code? we are getting 'hotelbeds\hotel_api_sdk\messages\destinationRQ or hotelbeds\hotel_api_sdk\messages\destinationRS not implemented in SDK' message.
