### ISSUE TITLE
Availability Request

### ISSUE THREAD

**Issue by MasoodRehman** [hotelbeds-sdk/hotel-api-sdk-php#140]
Hi,
I hope you will be doing good, I tried to contact you through website but they given the github link, Apologies for opening a new issue in SDK channel. I am using sandbox credentials but the response seems my credentials have some issue, Kindly checkout the request and the response return from API.
I am not using the hotel-api-sdk-php but the simple CURL approach.

**Request**

{"language":"ENG","stay":{"checkIn":"2018-07-27","checkOut":"2018-07-29"},"occupancies":[{"rooms":1,"adults":"2","children":"2","paxes":[{"type":"CH","age":2},{"type":"CH","age":2}]}],"hotels":{"hotel":["6807","6808","6809","6810","6811","6812","7650","7651","7652","7654","7655","7656","7657","7658","7659","7660","7661","7662","8919","9234","9487","15994","16027","16037","56315","56317","56318","56319","56320","56323","56324","56327","56329","59241","59245","59246","59247","59248","59249","59250","59259","59260","59261","59262","59263","59264","59267","59268","59269","59270","59271","59272","59273","62119","62344","62917","63839","64219","64221","64240","64759","64761","64763","64765","66528","74699","82130","82131","82381","82382","82383","82390","82653","84558","84561","86526","87136","87972","88082","88317","88934","89035","89250","91256","93664","93665","94714","96760","97074","101140","101656","103293","103296","103297","103299","103300","103301","103303","103304","103305","103306","103307","103308","103311","103314","103317","103318","103319","106234","107054","107138","107751","108599","108600","110036","111819","111842","114016","114238","114239","114898","114997","114998","115398","118213","120483","120496","120553","121054","121056","121057","121058","122042","123448","123580","123717","124962","125231","125334","125335","125336","127440","127442","127557","127884","128324","128423","128503","128618","128620","128621","128622","128624","128626","128627","129672","129799","129800","129802","129813","129849","129850","129851","129855","129856","129857","129858","129955","129956","129957","129958","129984","129987","130003","130004","130006","130008","130010","130012","130031","130032","130034","130123","132586","132588","132590","132592","132597","132598","132665","132769","133321","133322","133342","133344","133437","133982","134194","134691","134767","135642","135647","135648","135649","135650","135812","136069","136071","136602","136682","137180","137514","137955","137956","138030","138866","138867","139099","140159","140160","141490","141491","141536","142287","142292","142488","142489","142644","142645","142659","143182","143705","143962","146651","146652","146653","147870","148612","148613","148670","153409","153967","156391","156556","156652","157093","157250","158740","158747","158748","158822","160837","162334","162369","162731","162868","164259","164418","164765","168924","171155","171156","171157","171186","171246","174547","177907","178208","178871","180031","183407","183568","185069","185104","187727","187892","188108","190955","191315","191420","191435","191488","196852","196877","197849","199054","216744","216982","218363","224014","226549","226696","228646","228647","233409","235328","235795","235858","253859","256721","256722","285465","285491","285497","285638","285698","285834","285920","286246","286837","286857","287070","287667","287713","287747","287777","288041","288191","288201","288366","361306","362819","363143","363289","364378","365260","367283","372446","372447","373000","374413","376670","376854","385066","388539","388551","389169","391213","394138","394565","395560","399180","399303","399978","400141","400142","400779","402919","403186","403638","403649","403854","404909","405040","405298","405679","405925","405928","406907","408199","409599","409618","409619","409632","409643","409651","409657","409670","414660","414678","418078","425078","426779","427441","428238","428622","431721","436599","438060","442381","443421","446721","446722","450307","456421","462621","468921","473581","473603","479662","482521","484321","504371","505062","508281","516101","539281","540961","545301","546301","548061","555522","555901","555941","556101","556161","557501","557502","557506","557507","557508","557509","557510","557511","557513","557930","571081","573141","573142","573143","573144","573145","573146","573147","573148","573149","573150","573151","573152","573153","573154","573155","573156","573157","573158","574401","575909","577721","577841","578241","579101","583182","583484","584362","584363","585705","586256","591298","592226","592227","592271","592273","592275","592277","592278","592279","592280","592281","592282","592284","592287","592289","592290","592294","592378","599724","601561","601562","603113","603114","604121","604786","606223","606224","608424","608782","608982","611741","612342","612581","612909","613081","613642","614203","615856","616969","619901","623391","623422","623423","623424","623888","624341","624342","624346","625437","625723","627802","628262","628398","628403","628908"]}}

**Response**

{
    "auditData": {
        "timestamp": "2018-07-26 18:15:06.144",
        "requestHost": "119.153.227.52",
        "serverId": "sa3RKSJACHXE79K.env",
        "environment": "[int]",
        "release": "4e21884df45756e39e474aab3fe4fbc6adfcbcb0",
        "token": "e9547c09-85f1-4e8d-a181-e0128ca12b45",
        "internal": "0||||0|0||||||||||||0||||0||0|nnj7jfmd55v2nshsbdpmuq3w|||"
    },
    "error": {
        "code": "INVALID_DATA-e9547c09-85f1-4e8d-a181-e0128ca12b45",
        "message": "Incorrect api key: nnj7jfmd55v2nshs********"
    }
}

Thanks.

**Comment by vmavromatis** [comment]
Hello @MasoodRehman can you please share your apikey? (not your secret). Please make sure you are not entering any blank spaces when you are sending it in the header.
Regards,
Vasilis

**Comment by identnticalmedia** [comment]
i just integrated my site with hotelbed but after setup its showing blank

public API: 8hbzec8nwnh66qbjqpzqcmec

am using Phptravels script

**Comment by MasoodRehman** [comment]
Hi @vmavromatis 

I already shared my key in the above message. I am expecting a detail response from your side. Kindly reply me ASAP. 

Thanks.

**Comment by vmavromatis** [comment]
Hello @MasoodRehman apologies for the delayed response. I am unable to reproduce this issue - I have tried using your key and works fine here. Can you please post the full Curl code (minus the secret)? Also are you sure you are spelling the headers fine `Api-key` and `X-Signature`?
