### ISSUE TITLE
Developer Over Rate

### ISSUE THREAD

**Issue by saurabhsinghthakur** [hotelbeds-sdk/hotel-api-sdk-php#144]
Hello Sir Please help me. How to increase Developer Over Rate. I didn't found how to purchase this API.

**Comment by vmavromatis** [comment]
Hi @saurabhsinghthakur apologies for the late reply. Developer over rate means that you have exceeded your daily usage for the test environment - normally ~50 requests /day. Please see here: https://developer.hotelbeds.com/docs/read/API_Errors

To get more info about using the API commercially please contact APItude@hotelbeds.com
