### ISSUE TITLE
 Destination search is not available by default

### ISSUE THREAD

**Issue by sgatrip** [hotelbeds-sdk/hotel-api-sdk-php#147]
We try to search availability by keyword (destination) but it's not enable for our account.

we use apikey "uvm57gdccazq4rxnamj4tjjw"

@vmavromatis can you activate it ?

thanks for your help

```
[
    0 => 'error '
    1 => 'Bad Request: INVALID_DATA-cd47d804-3f5b-4ae0-90fa-c61571332865 Invalid data. Destination search is not available by default: Please contact API Distribution Team apitude@hotelbeds.com'
]
```

**Comment by vmavromatis** [comment]
Hello @sgatrip, please contact the team which is responsible for this feature which is apitude@hotelbeds.com and they will look into your query. Hope this helps.

If needed to re-open the ticket please let me know.

Regards,
Vasilis
