### ISSUE TITLE
Hotel by destination code and zone

### ISSUE THREAD

**Issue by picotrain** [hotelbeds-sdk/hotel-api-sdk-php#15]
Hi,
How do you add in a parameter for the zone on top of the destination code to get a more refined list of hotels from a destination availability search?

I've tried this - 
$destination = ['zone' => ['24']];

Thanks

**Comment by jrossello** [comment]
Hi @picotrain , 

try to set value for zone this way: 
$destination->zone=37; 
Zone is an integer value

a short example:
$destination = new Destination("PMI");
$destination->zone=37; 


Regards
