### ISSUE TITLE
Difference TotalNet between BookingDetailsRS and BookingChangeRS on change paxes names

### ISSUE THREAD

**Issue by yooDesign** [hotelbeds-sdk/hotel-api-sdk-php#150]
Hi team,

I would like to ask you regarding the BookingChange Request. I have attached you a .pdf file with a BookingDetails Response and BookingChange Response with only Paxes names change. In this example the TotalNet is increased on BookingChange response. So, I would like to ask you if it's normal the traveller to pay a cost if he would like to change just his name. For your information, same results if there's no change request.

Please advise.
Thank you
[BooingDetailsRQ-BookingChangeRQ.pdf](https://github.com/hotelbeds-sdk/hotel-api-sdk-php/files/3018381/BooingDetailsRQ-BookingChangeRQ.pdf)

**Comment by vmavromatis** [comment]
Kalispera George :) Looking into your query and will get back to you ASAP.

**Comment by yooDesign** [comment]
Seuharistw Vasilh.. Ekleisa to thema giati yphrxe lathos stis hmeromhnies pou ekana Request.

Na sai kala

**Comment by vmavromatis** [comment]
OK kanena provlima, pes mou an xreiasteis kati - Closing the issue.

Regards,
Vasilis

**Comment by yooDesign** [comment]
Seuharistw poly! Kalh syneheia

**Comment by chandonglee** [comment]
>  Hi team,
> 
> 
> 
> I would like to ask you regarding the BookingChange Request. I have attached you a .pdf file with a BookingDetails Response and BookingChange Response with only Paxes names change. In this example the TotalNet is increased on BookingChange response. So, I would like to ask you if it's normal the traveller to pay a cost if he would like to change just his name. For your information, same results if there's no change request.
> 
> 
> 
> 
> 
> Please advise.
> 
> Thank you
> 
> [BooingDetailsRQ-BookingChangeRQ.pdf](https://github.com/hotelbeds-sdk/hotel-api-sdk-php/files/3018381/BooingDetailsRQ-BookingChangeRQ.pdf)
> 
> 
> 
>

**Comment by chandonglee** [comment]
These daily addresses are shared. I'm yeong!
