### ISSUE TITLE
CreateBooking tolerance field

### ISSUE THREAD

**Issue by yooDesign** [hotelbeds-sdk/hotel-api-sdk-php#159]
Hi team,

Im getting an error on submitting the tolerance field on CreateBooking RQ. The reason i would like to change the tolerance is that all the failed bookings we have are because of that.
I have tried submitting tolerance field by using any type of value type but I always get the following error:

I have tried:
- 2.00 (double)
- 2 (integer)
- '2.00' (string)
- '2' string

and always get an error. So, in what format shall i submit the tolerance value? In your documentation you say 'double' but this is not correct apparently.

```
PHP Fatal error:  Uncaught hotelbeds\hotel_api_sdk\generic\FieldNotValid: tolerance not valid for this model in /hotelgift.com/wp-content/plugins/hg-hotels/admin/vendor/hotelbeds/hotel-api-sdk-php/src/generic/DataContainer.php:44
Stack trace:
#0 hotelgift.com/wp-content/plugins/hg-hotels/admin/class-hg-hotels-admin.php(1039): hotelbeds\hotel_api_sdk\generic\DataContainer->__set('tolerance', 2.00)
```

@vmavromatis Could you please kindly look this?
Looking forward to hearing from you.

Thanks and have a good day

**Comment by davidgv88** [comment]
I have the same problem. Add tolerance to src/helpers/Booking.php

<img width="673" alt="Captura de pantalla 2019-07-14 a las 12 16 58" src="https://user-images.githubusercontent.com/679262/61182307-89fa4780-a631-11e9-867a-271619785384.png">

**Comment by davidgv88** [comment]
I will create a pull request with this

**Comment by yooDesign** [comment]
Thanks a lot dad @davidgv88 
I applied changes and it's now working as expected.
