### ISSUE TITLE
Get Images for each hotel

### ISSUE THREAD

**Issue by ronaldaug** [hotelbeds-sdk/hotel-api-sdk-php#174]
According to [this issue](https://github.com/hotelbeds-sdk/hotel-api-sdk-php/issues/95) , It seems we can't get images via booking API.

Here, I could query to content API and append images to every hotels. But this increases loading time and API is very slow. 

Is there any solution for this?
And is it possible to get all hotels content at once like a zip or json format?

Thanks in advance

**Comment by BrodriguezHbeds** [comment]
Hi @ronaldaug ,

I'm sorry but the static content is not available as a downloadable file. The only way to access this data is though REST requests to Hotel ContentAPI.

The usual method for getting the static content is making a first time download of all data, and then    get only the updated information using the _lastUpdateTime_ parameter. if you haven't, check the recommended use here: https://developer.hotelbeds.com/docs/read/apitude_content/How_to_use

Regards,
Bruno Rodríguez

**Comment by ronaldaug** [comment]
@BrodriguezHbeds Thanks
