### ISSUE TITLE
Internal server error 

### ISSUE THREAD

**Issue by JustinProvab** [hotelbeds-sdk/hotel-api-sdk-php#175]
After getting booked hotel curl is throwing this error where the xml file is also not SAving 
The below  error I'm getting plz revert any one ASAP 

**SYSTEM_ERROR-F1C400B88D2843A6A5976E56228C2ABC Internal server error**

**cURL error (22): HTTP response code said error28510**

**Comment by BrodriguezHbeds** [comment]
Hi @JustinProvab ,

Could you please share the request in cUrl format?

Thank you

**Comment by JustinProvab** [comment]
Hi @BrodriguezHbeds  I was passing wrong room rate key It's fixed tnx for the reply
