### ISSUE TITLE
Not authorized, review your api-key and secret!

### ISSUE THREAD

**Issue by xochilpili** [hotelbeds-sdk/hotel-api-sdk-php#19]
Hola a todos; 

He generado las credenciales desde : https://developer.hotelbeds.com/docs/read/Home
y he intentado usar el php script que se encuentra en la misma página, me he comunicado con uno de los asesores y fue el que me recomendó usar el SDK de hotelbeds, así mismo lo he probado con postman, sin embargo, obtengo el mismo resultado: 

==================================================
**Not authorized, review your api-key and secret!**
==================================================

¿Podría por favor alguien orientarme?

Expongo aquí la configuración de mi php: 

# php --version
PHP 5.6.22 (cli) (built: May 28 2016 10:12:12)

# pecl info pecl_http
About pecl.php.net/pecl_http-2.5.3

# php -m 
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
ereg
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
http
iconv
json
ldap
libxml
mbstring
mcrypt
mhash
mssql
mysql
mysqli
openssl
pcntl
pcre
PDO
pdo_dblib
pdo_mysql
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
propro
raphf
readline
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
zip
zlib

# cat HotelApiClient.ini
apiclient.url          = https://api.test.hotelbeds.com
apiclient.apikey       = **********************
apiclient.sharedsecret = **********
apiclient.timeout      = 120

**Usando el SDK **
# cat test.php

<?php
	require __DIR__.'/framework/vendor/autoload.php';
	
use hotelbeds\hotel_api_sdk\HotelApiClient;
use hotelbeds\hotel_api_sdk\model\Destination;
use hotelbeds\hotel_api_sdk\model\Occupancy;
use hotelbeds\hotel_api_sdk\model\Pax;
use hotelbeds\hotel_api_sdk\model\Rate;
use hotelbeds\hotel_api_sdk\model\Stay;
use hotelbeds\hotel_api_sdk\types\ApiVersion;
use hotelbeds\hotel_api_sdk\types\ApiVersions;
use hotelbeds\hotel_api_sdk\messages\AvailabilityRS;
	
	$reader = new Zend\Config\Reader\Ini();
	$config = $reader->fromFile(__DIR__.'/HotelApiClient.ini');
	$cfgApi = $config['apiclient'];

	$apiClient = new HotelApiClient($cfgApi['url'],$cfgApi['apikey'],$cfgApi['sharedsecret'],new ApiVersion(ApiVersions::V1_0), $cfgApi['timeout']);
	
	$rqData = new \hotelbeds\hotel_api_sdk\helpers\Availability();
	$rqData->stay = new Stay(DateTime::createFromFormat('Y-m-d','2016-07-08'),DateTime::createFromFormat('Y-m-d','2016-07-10'));
	
	$rqData->destination = new Destination('PMI');
	$occupancy = new Occupancy();
	$occupancy->adults=2;
	$occupancy->children=1;
	$occupancy->rooms=1;
	
	$occupancy->paxes = [new Pax(Pax::AD, 30, 'Mike', 'Doe'),  new Pax(Pax::AD, 27,'Jane','Doe'),new Pax(Pax::CH, 8, 'Mack','Doe')];
	$rqData->occupancies = [$occupancy];
	
	try{
		$availRS = $apiClient->availability($rqData);
		
	}catch(\hotelbeds\hotel_api_sdk\types\HotelSDKException $e){
		$auditData = $e->getAuditData();
		error_log($e->getMessage());
		//error_log("Audit remote data = ".json_encode($auditData->toArray()));
		exit();
	}catch(Exception $e){
		error_log($e->getMessage());
		exit();
	}
	
	if(!$availRS->isEmpty()){
		print_r($availRS->hotels->toArray());
	}else{
		echo "No results!\n\n";
	}
?>

#php test.php
Not authorized, review your api-key and secret!

Así mismo, tuve que renombrar AvailabilityRS a availabilityRS en la carpeta messages/
En el hilo del error documentado en este repositorio, dice que habría que actualizar, sin embargo, no tengo ni una hora que lo he instalado, asumo que me ha instalado la última versión.

# cat framework/composer.json 
{
    "require": {
        "hotelbeds/hotel-api-sdk-php": "dev-master@dev"
    }
}

**Usando el siguiente script PHP publicado en la página oficial de la documentación**:
<?php
// Your API Key and secret
$apiKey = "yourApiKey";
$sharedSecret = "yourSharedSecret";
// Signature is generated by SHA256 (Api-Key + Shared Secret + Timestamp (in seconds))
$signature = hash("sha256", $apiKey.$sharedSecret.time());
// Example of call to the API
$endpoint = "https://api.test.hotelbeds.com/hotel-api/1.0/status";
$request = new http\Client\Request("GET",
    $endpoint,
    [ "Api-Key"     => $apiKey,
      "X-Signature" => $signature,
      "Accept"      => "application/xml" ]);
try{
    $client = new http\Client;
    $client->enqueue($request)->send();
    // pop the last retrieved response
   $response = $client->getResponse();
    if ($response->getResponseCode() != 200) {  
       printf("%s returned '%s' (%d)\n",
           $response->getTransferInfo("effective_url"),
           $response->getInfo(),
           $response->getResponseCode()
       );
    } else {
       printf($response->getBody());
    }
} catch (Exception $ex) {
    printf("Error while sending request, reason: %s\n",$ex->getMessage());
}
?>

#php test2.php
https://api.test.hotelbeds.com/hotel-api/1.0/status returned 'HTTP/1.1 403 Forbidden' (403)

Les agradeceré infinitamente su ayuda...

xOCh

**Comment by jrossello** [comment]
Buenas, 
el problema parace estar con tus credenciales, has intentado hacer una petición usando tus credenciales desde el apartado de SandBox https://developer.hotelbeds.com/io-docs. 
Si no sabes como hacerlo puedes compartir tu Apikey y lo revisaremos.

Saludos

**Comment by xochilpili** [comment]
jrossello ; 

Gracias por contestar, el asesor dijo que las credenciales funcionan, pero nunca dijo cómo :P

No sé cómo usar el apartado SandBox, ¿podrás explicarme cómo funciona?
Esta es la Apikey: 

**me827sawcekqhgskqhjnu589**

Gracias

**Comment by jrossello** [comment]
Hi xochilpili,
en la url que te he proporcionado antes, https://developer.hotelbeds.com/io-docs. , seleccionas la api con la que quieres probar (en el selectBox  por defecto viene hotel-api 1.0), seleccionas tu apikey con la que realizr las pruebas y le das a TryIt... y aparecerá la respuesta abajo.
Las fechas por defecto son incorrectas para la petición de hoteles, modifícalas antes de realizar la petición.
![image](https://cloud.githubusercontent.com/assets/16668247/16706853/936f6aee-45bc-11e6-954b-22129ddc5bd9.png)
![image](https://cloud.githubusercontent.com/assets/16668247/16706867/3c5cfc70-45bd-11e6-9726-925925e7c022.png)

**Comment by xochilpili** [comment]
En efecto, está funcionando desde el apartado de Sandbox. 
Entonces, como mi pregunta incial : 
#¿Qué estoy haciendo mal vía PHP?
#¿Falta algo en la configuración del server?

Gracias!

xOCh

**Comment by jrossello** [comment]
La configuración del server es correcta, de hecho es la misma que usa Sandbox . Que te funcione desde Sandbox descarta un error de configuración de tu cuenta. Has revisado que las credenciales en el fichero HotelApiClient.ini sean correctas y no contengan espacios en blanco. Asegúrate que son las mismas que te han funcionado desde sandbox.  El código de prueba de la sdk al nosotros nos funciona bien

**Comment by xochilpili** [comment]
Sí, he revisado que no tenga espacios, aún así en la clase del SDK usa trim($apikey); lo he verificado, pero me da el mismo resultado. 
Lo característico es que en ambos scripts; tanto en el que está en la página de la documentación como en el SDK me devuelve el mismo resultado.

Como es una apikey y shared de prueba; ¿los posteo para que pruebes?

**Comment by Zavierazo** [comment]
Hola @xochilpili, prueba a ejecutar:

Desde linux: `.\vendor\bin\phpunit --testsuite availability`
Desde windows: `./vendor/bin/phpunit.bat --testsuite availability`

Ese es el propio test unitario que viene en el sdk para hacer la prueba de que lo tienes todo bien.

**Comment by xochilpili** [comment]
Zavierazo: 

[xochilpili@labs framework]# .\vendor\bin\phpunit --testsuite availability
-bash: .vendorbinphpunit: no se encontró la orden

He probado ./vendor/bin/phpunit --testsuite availability
pero no tengo carpeta bin dentro de vendor...

**Comment by Zavierazo** [comment]
Ejecuta el siguiente comando

composer require "hotelbeds/hotel-api-sdk-php:dev-master@dev"

Esto te descargara todas las dependencias del proyecto incluyendo el script que te he comentado

**Comment by xochilpili** [comment]
Tengo entendido que composer ha cambiado, entonces estoy siguiendo esto :

"require-dev": {
    "phpunit/phpunit": "3.7.*"
},

composer.phar update --prefer-dist --dev

bin/phpunit -c /app

#edito
Me acaba de llegar tu respuesta Zavierazo, eso mismo hice al principio como lo dicen en su página de "Step by Step"

**Comment by Zavierazo** [comment]
Pues el mismo composer te lo deberia haber descargado todo. Yo lo hice de 0 el pasado jueves y no tuve problemas

**Comment by xochilpili** [comment]
Zavierazo :

Ya tengo instalada la dependencia de phpunit para composer, sin embargo al momento se hacer 
./vendor/bin/phpunit --testsuite availability
No acepta el argumento, muestra la ayuda:
PHPUnit 3.7.38
Usage: php unit [...]

También he intentado esto siguiendo la ayuda de PHPUnit y usando el argument -c :

./vendor/bin/phpunit -c vendor/hotelbeds/hotel-api-sdk-php/phpunit.xml

PHP Warning:  require(hotelbeds/api/framework/vendor/hotelbeds/hotel-api-sdk-php/vendor/autoload.php): failed to open stream: No such file or directory in hotelbeds/api/framework/vendor/hotelbeds/hotel-api-sdk-php/bootstrap.php on line 2

Warning: require(hotelbeds/api/framework/vendor/hotelbeds/hotel-api-sdk-php/vendor/autoload.php): failed to open stream: No such file or directory in hotelbeds/api/framework/vendor/hotelbeds/hotel-api-sdk-php/bootstrap.php on line 2
PHP Fatal error:  require(): Failed opening required 'hotelbeds/api/framework/vendor/hotelbeds/hotel-api-sdk-php/vendor/autoload.php' (include_path='hotelbeds/api/framework/vendor/phpunit/phpunit-mock-objects:hotelbeds/api/framework/vendor/phpunit/php-token-stream:hotelbeds/api/framework/vendor/phpunit/php-code-coverage:hotelbeds/api/framework/vendor/phpunit/phpunit:hotelbeds/api/framework/vendor/symfony/yaml:.:/usr/share/pear:/usr/share/php') in 
hotelbeds/api/framework/vendor/hotelbeds/hotel-api-sdk-php/bootstrap.php on line 2
 [etc...]

# pues no sé qué esté haciendo mal, he seguido los pasos del "Step by Step". 
No me puso la dependencia de phpunit en el composer.json la acabo de agregar y con ello, me ha instalado la carpeta /bin dentro de /vendor.

**Comment by xochilpili** [comment]
¿Alguna idea?

**Comment by Zavierazo** [comment]
Hola @xochilpili . yo creo que estas haciendo todo correctamente pero debe haber algún problema con tus claves. Pásamelas a xortiz@hotelbeds.com y el lunes a primera hora lo reviso.

**Comment by xochilpili** [comment]
Zavierazo: 

Te he enviado las credenciales.

Gracias infinitas.

xOCh

**Comment by Zavierazo** [comment]
Hola @xochilpili, para tus credenciales parece todo correcto, podrías pasar todo tu directorio para ver cual es el problema?

**Comment by xochilpili** [comment]
Zavierazo: 

El directorio ya lo había publicado, te lo mando directamente: 

http://pastebin.com/xdiNBFJk

Gracias

**Comment by Zavierazo** [comment]
Hola @xochilpili, no veo que tengas ni el test.php ni el HotelApiClient.ini en la raiz. Esos dos ficheros deberias tenerlos en la raiz de la siguiente forma:
|-- composer.json
|-- test.php
|-- HotelApiClient.ini
|-- composer.lock
`-- vendor
....
....

Lo que te había pedido es el directorio comprimido directamente para ver todas las clases. Pero al menos deberías tener el árbol como te digo.

**Comment by xochilpili** [comment]
[root@labs api]# ls -lia 
total 24
1704250 drwxr-xr-x 3 root root 4096 jul  9 14:32 framework
1708819 -rw-r--r-- 1 root root 1621 jul  7 17:22 general.php
1706452 -rw-r--r-- 1 root root  171 jul  9 14:09 HotelApiClient.ini
1706449 -rw-r--r-- 1 root root 1713 jul  8 18:33 test.php


* Dentro de la carpeta framework, tengo el SDK y componentes de composer

**Comment by Zavierazo** [comment]
Prueba a meter todo en el mismo directorio. Yo he hecho el step by step usando tus credenciales y me funciona.

**Comment by xochilpili** [comment]
Ok, borraré todo y lo haré nuevamente poniéndolo en un único directorio.
Comienzo con el "Step by Step"

**Comment by xochilpili** [comment]
# composer require "hotelbeds/hotel-api-sdk-php:dev-master@dev"
http://pastebin.com/UJib4zkT

# composer update --prefer-dist --dev
http://pastebin.com/cXMGTpLN

#php test.php
hotelbeds\hotel_api_sdk\messages\availabilityRQ or hotelbeds\hotel_api_sdk\messages\availabilityRS not implemented in SDK
# mv vendor/hotelbeds/hotel-api-sdk-php/src/messages/AvailabilityRS.php vendor/hotelbeds/hotel-api-sdk-php/src/messages/availabilityRS.php (también el ...RQ)

# php test.php
Not authorized, review your api-key and secret!

#ls -lia .
total 68
1705139 drwxr-xr-x  3 root root  4096 jul 11 11:35 .
1705120 drwxr-xr-x  7 root root  4096 jul  8 17:37 ..
1706448 -rw-r--r--  1 root root   139 jul 11 11:35 composer.json
1706430 -rw-r--r--  1 root root 39062 jul 11 11:36 composer.lock
1708819 -rw-r--r--  1 root root  1621 jul  7 17:22 general.php
1706452 -rw-r--r--  1 root root   171 jul  9 14:09 HotelApiClient.ini
1707987 -rw-r--r--  1 root root  1694 jul 11 11:02 test.php
1705266 drwxr-xr-x 10 root root  4096 jul 11 11:36 vendor 

# cat composer.json
{
    "require": {
        "hotelbeds/hotel-api-sdk-php": "dev-master@dev"
    },
    "require-dev": {
	"phpunit/phpunit": "3.7.*"
    }
}

¿Es algo que esté haciendo mal?

**Comment by xochilpili** [comment]
¿Alguna idea?

**Comment by xochilpili** [comment]
Tendrá algo que ver que estoy en un servidor usando !SSLv2 !SSLv3 con apache ?

**Comment by Zavierazo** [comment]
Hola, @xochilpili , pasame el directorio comprimido a xortiz@hotelbeds.com así podre ver si tienes algo mal en el contenido. Ahora mismo no se me ocurre porque puede estar fallando.

**Comment by Zavierazo** [comment]
Hola Xochilpili, he ejecutado tu código tal cual sin tocar y a mi me funciona perfecto (Solo he tenido que cambiar fechas checkin, checkout). Me da la siguiente salida
[output.txt](https://github.com/hotelbeds-sdk/hotel-api-sdk-php/files/359815/output.txt)

**Comment by xochilpili** [comment]
Zavierazo: 

Entonces, déjame hacer un prueba en otro server...
¿Qué puede estar pasando?
¿Es importante tener pecl_http para usar el SDK?

**Comment by Zavierazo** [comment]
Para usar el sdk tienes que tener puestos las extensiones openssl y curl
configuradas en tu php.ini y tener instalado los certificados. Basicamente
una configuracion estandard para conexiones https

**Comment by xochilpili** [comment]
Zavierazo; 
¿Cuáles certificados?
¿Dónde obtenerlos?

**Comment by Zavierazo** [comment]
Hola, puedes obtenerlo desde navegador directamente al entrar en esta url https://api.test.hotelbeds.com . También se puede hacer por comando. Si buscas por internet encontraras mil guías.

**Comment by xochilpili** [comment]
No entiendo nada; 
He copiado el certificado y he corrido el archivo test.php y sigue diciéndome "Not authorized,"
He aquí mi phpinfo()

https://labs.paranoids.us/ninfa.php

PS.- El certificado lo he puesto así: 

ex +'/BEGIN CERTIFICATE/,/END CERTIFICATE/p' <(echo | openssl s_client -showcerts -connect api.test.hotelbeds.com:443) -scq > hotelbeds.crt 

mv hotelbeds.crt /etc/pki/ca-trust/source/anchors/
update-ca-trust -force-enable

# comprobación: 

openssl s_client -connect api.test.hotelbeds.com:443

CONNECTED(00000003)
depth=2 C = US, O = "thawte, Inc.", OU = Certification Services Division, OU = "(c) 2006 thawte, Inc. - For authorized use only", CN = thawte Primary Root CA
verify return:1
depth=1 C = US, O = "thawte, Inc.", CN = thawte SSL CA - G2
verify return:1
depth=0 C = ES, ST = Baleares, L = PALMA, O = "HOTELBEDS SPAIN, S.L.", CN = api.hotelbeds.com
verify return:1
---
Certificate chain
 0 s:/C=ES/ST=Baleares/L=PALMA/O=HOTELBEDS SPAIN, S.L./CN=api.hotelbeds.com
   i:/C=US/O=thawte, Inc./CN=thawte SSL CA - G2
 1 s:/C=US/O=thawte, Inc./CN=thawte SSL CA - G2
   i:/C=US/O=thawte, Inc./OU=Certification Services Division/OU=(c) 2006 thawte, Inc. - For authorized use only/CN=thawte Primary Root CA
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIExDCCA6ygAwIBAgIQemMYERkQQyY5aDrxN5GviDANBgkqhkiG9w0BAQsFADBB
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMdGhhd3RlLCBJbmMuMRswGQYDVQQDExJ0
aGF3dGUgU1NMIENBIC0gRzIwHhcNMTUwOTA0MDAwMDAwWhcNMTcwOTAzMjM1OTU5
WjBsMQswCQYDVQQGEwJFUzERMA8GA1UECAwIQmFsZWFyZXMxDjAMBgNVBAcMBVBB
TE1BMR4wHAYDVQQKDBVIT1RFTEJFRFMgU1BBSU4sIFMuTC4xGjAYBgNVBAMMEWFw
aS5ob3RlbGJlZHMuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
00irMFP7wrOLX5e6J22w7vBnW9Fkz45RjlW6B75fQ2h9Phh+fFNSuzvLUGg5N9t6
N93oO2cRKQgKifwUVnXJzjzn9bdeME7fr66cI1eqk7M5s/UNhaa/Hlt3K6DlnBQY
kXbg79l8/fCwFJKP6GxlGaT7gKlI3hwP4pAvxYzO/W7yYig8KSGoeJHPE+jvBbcu
khwfIFvhHCIKWb3+z7VfA48ZgKZ6H2ko91FdcAss9hxv3Ocz9KA4nGWZ+mt7Z8v3
QWRtcbyl346U//NmdvtAjDLQvRxm6+HxQr3S5mEZzH0X1a7yQLkf8fj/uYDryFrb
5hSZyOz2IKrJG7dVf85/bQIDAQABo4IBizCCAYcwNAYDVR0RBC0wK4IWYXBpLnRl
c3QuaG90ZWxiZWRzLmNvbYIRYXBpLmhvdGVsYmVkcy5jb20wCQYDVR0TBAIwADBu
BgNVHSAEZzBlMGMGBmeBDAECAjBZMCYGCCsGAQUFBwIBFhpodHRwczovL3d3dy50
aGF3dGUuY29tL2NwczAvBggrBgEFBQcCAjAjDCFodHRwczovL3d3dy50aGF3dGUu
Y29tL3JlcG9zaXRvcnkwDgYDVR0PAQH/BAQDAgWgMB8GA1UdIwQYMBaAFMJPSFf8
0U+awF04fQ4F29kutVJgMCsGA1UdHwQkMCIwIKAeoByGGmh0dHA6Ly90ai5zeW1j
Yi5jb20vdGouY3JsMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjBXBggr
BgEFBQcBAQRLMEkwHwYIKwYBBQUHMAGGE2h0dHA6Ly90ai5zeW1jZC5jb20wJgYI
KwYBBQUHMAKGGmh0dHA6Ly90ai5zeW1jYi5jb20vdGouY3J0MA0GCSqGSIb3DQEB
CwUAA4IBAQBh4nOvI7IUPK8dj5FxPFka/V/azHD3ezxs+O7o5C9B3lvdHBcXIgOa
h/5l9ZhnJ2dpw9+bQtQ4oDTcLp4Yc1CmK3DxyQ4qxWsLVeLB8ygpSQvZQZOxC8YN
goN0NeWoQRwlJDmmSKwpW6a+1ig4kAkqb3Amt0ZidupgnXVD79bmyeKmvkA6o6Oo
XtrVQycHr+06N+p0m18tT/dfGuPdSivEQo6ozNPfLdPpswN1WeGwOhfRLxw5yVMe
r9hkAOYTaG8NSCVz0W8R0wwhxdHDdj/5Y13u6OqSB0yebbnE+1pCWCC4nu0OZrWC
6xKe1KBu3pra1Fbfdl9dMB8wshhQbAMN
-----END CERTIFICATE-----
subject=/C=ES/ST=Baleares/L=PALMA/O=HOTELBEDS SPAIN, S.L./CN=api.hotelbeds.com
issuer=/C=US/O=thawte, Inc./CN=thawte SSL CA - G2
---
No client certificate CA names sent
Server Temp Key: ECDH, prime256v1, 256 bits
---
SSL handshake has read 3087 bytes and written 373 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES128-GCM-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-GCM-SHA256
    Session-ID: 5F5AA3D8659B5F1A8E4F7485C5218514E449C8B2E49833507CAD323C56B521AB
    Session-ID-ctx: 
    Master-Key: C45F6980DCD55FFF5F4705170687E87A697E8FA9EA68751E8D72AC9A309A090D76F191F9B5C82B3D35B0303DD15390F4
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    TLS session ticket lifetime hint: 300 (seconds)
    TLS session ticket:
    0000 - ea ac f8 25 9a dc 63 5b-37 e9 d5 d1 cb 25 69 dc   ...%..c[7....%i.
    0010 - 16 26 f9 a8 52 ba 85 05-87 c8 28 cb b4 17 87 00   .&..R.....(.....
    0020 - c0 43 95 3d 3c fa 6f 2e-ea 01 fe bd ab 72 49 de   .C.=<.o......rI.
    0030 - af 92 d2 87 63 19 2d d8-2c 59 55 12 82 36 9a 32   ....c.-.,YU..6.2
    0040 - 1c 7c 93 03 b5 63 85 ab-87 a8 bb c9 e0 fb 4d c8   .|...c........M.
    0050 - f9 7a 03 bb bf 39 3a dd-98 46 86 2e 22 26 8f 59   .z...9:..F.."&.Y
    0060 - c1 6c bb d5 bf b1 4b 00-8d a7 69 95 97 d9 38 0f   .l....K...i...8.
    0070 - 89 aa f1 1e 7d 38 26 55-73 58 f2 e5 c2 50 66 3c   ....}8&UsX...Pf<
    0080 - 78 09 25 2f 99 6f 30 96-8f 97 98 92 53 fd 28 9f   x.%/.o0.....S.(.
    0090 - 9a ba 0d f0 95 0b 5a 4c-ce ae b6 61 5e fa 6f d2   ......ZL...a^.o.

    Start Time: 1468344466
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---

HTTP/1.1 400 BAD_REQUEST
Content-Length: 0
Connection: Close

**Comment by Zavierazo** [comment]
Hola @xochilpili deberias meterte los certificados en etc/ssl/certs

**Comment by alvmunoz** [comment]
@xochilpili , hemos hecho un cambio;  ¿puedes volver a descargarlo y decirnos qué error te da ahora?

**Comment by xochilpili** [comment]
Zavierazo: 

En centos 6.7 con ponerlos en /etc/pki/ca-trust/source/anchors/hotelbeds.crt
y después: update-ca-trust actualiza los certificados. Sin embargo para efectos de demostración; lo he puesto en el directorio que mencionas: /etc/ssl/certs/
Ahora muestra esto: 

> p11-kit: duplicate 'api.hotelbeds.com' certificate found in: hotelbeds.crt

O sea, el certificado está instalado. 

Álvaro: 

He vuelto a rehacer el proceso desde el Step by Step; 
obtengo el mismo resultado: 
#Not authorized, review your api-key and secret!

¿Esto tendrá algo qué ver?
#pecl list-upgrades
WARNING: channel "pear.php.net" has updated its protocols, use "pecl channel-update pear.php.net" to update
Channel pear.php.net: No upgrades available
pecl.php.net Available Upgrades (stable):

pecl.php.net pecl_http 2.5.3 (stable) 3.0.1 (stable) 193kB
pecl.php.net propro    1.0.2 (stable) 2.0.1 (stable) 13.2kB
pecl.php.net raphf     1.1.0 (stable) 2.0.0 (stable) 15.4kB

**Comment by alvmunoz** [comment]
@Zavierazo ,  ¿puedes avisar a xochilpili para que vuelva a probar cuando el código esté actualizado sin ese mensaje de error? 
Gracias

**Comment by Zavierazo** [comment]
Hola @xochilpili, ya esta disponible para descargar la dependencia. Vuelve a descargarla y prueba de nuevo.

**Comment by xochilpili** [comment]
Zavierazo; 
¿A qué dependencia te refieres?
Sigo sin poder acceder.
¿Alguna otra idea?

Gracias.

**Comment by Zavierazo** [comment]
Me refiero a volver a descargar con composer la dependencia de hotelbeds.
Hemos cambiado el mensaje que da de error para que ponga directamente el
contenido de respuesta en vez de un mensaje predefinido.

El 16/7/2016 21:49, "xOCh" <notifications@github.com> escribió:

Zavierazo;
¿A qué dependencia te refieres?
Sigo sin poder acceder.
¿Alguna otra idea?

Gracias.

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/hotelbeds-sdk/hotel-api-sdk-php/issues/19#issuecomment-233147793>,
or mute the thread

**Comment by xochilpili** [comment]
Zavierazo: 

Ok, probando nuevamente.

**Comment by xochilpili** [comment]
#composer require "hotelbeds/hotel-api-sdk-php:dev-master@dev"

Running composer as root/super user is highly discouraged as packages, plugins and scripts cannot always be trusted
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing zendframework/zend-stdlib (2.7.7)
    Loading from cache

  - Installing zendframework/zend-hydrator (1.1.0)
    Loading from cache

  - Installing zendframework/zend-config (2.5.1)
    Loading from cache

  - Installing nicmart/string-template (v0.1.0)
    Loading from cache

  - Installing zendframework/zend-json (2.6.1)
    Loading from cache

  - Installing container-interop/container-interop (1.1.0)
    Loading from cache

  - Installing zendframework/zend-validator (2.8.1)
    Loading from cache

  - Installing zendframework/zend-escaper (2.5.2)
    Loading from cache

  - Installing zendframework/zend-uri (2.5.2)
    Loading from cache

  - Installing zendframework/zend-loader (2.5.1)
    Loading from cache

  - Installing zendframework/zend-http (2.5.4)
    Loading from cache

  - Installing hotelbeds/hotel-api-sdk-php (dev-master ab0ef7c)
    Cloning ab0ef7c690dd2ea27c6bf188afb8947a4b26488b

zendframework/zend-stdlib suggests installing zendframework/zend-eventmanager (To support aggregate hydrator usage)
zendframework/zend-stdlib suggests installing zendframework/zend-serializer (Zend\Serializer component)
zendframework/zend-stdlib suggests installing zendframework/zend-servicemanager (To support hydrator plugin manager usage)
zendframework/zend-stdlib suggests installing zendframework/zend-filter (To support naming strategy hydrator usage)
zendframework/zend-hydrator suggests installing zendframework/zend-eventmanager (^2.6.2 || ^3.0, to support aggregate hydrator usage)
zendframework/zend-hydrator suggests installing zendframework/zend-serializer (^2.6.1, to use the SerializableStrategy)
zendframework/zend-hydrator suggests installing zendframework/zend-servicemanager (^2.7.5 || ^3.0.3, to support hydrator plugin manager usage)
zendframework/zend-hydrator suggests installing zendframework/zend-filter (^2.6, to support naming strategy hydrator usage)
zendframework/zend-config suggests installing zendframework/zend-filter (Zend\Filter component)
zendframework/zend-config suggests installing zendframework/zend-i18n (Zend\I18n component)
zendframework/zend-config suggests installing zendframework/zend-servicemanager (Zend\ServiceManager for use with the Config Factory to retrieve reader and writer instances)
zendframework/zend-json suggests installing zendframework/zend-server (Zend\Server component, required to use Zend\Json\Server)
zendframework/zend-json suggests installing zendframework/zendxml (To support Zend\Json\Json::fromXml() usage)
zendframework/zend-validator suggests installing zendframework/zend-db (Zend\Db component)
zendframework/zend-validator suggests installing zendframework/zend-filter (Zend\Filter component, required by the Digits validator)
zendframework/zend-validator suggests installing zendframework/zend-i18n (Zend\I18n component to allow translation of validation error messages as well as to use the various Date validators)
zendframework/zend-validator suggests installing zendframework/zend-i18n-resources (Translations of validator messages)
zendframework/zend-validator suggests installing zendframework/zend-math (Zend\Math component)
zendframework/zend-validator suggests installing zendframework/zend-servicemanager (Zend\ServiceManager component to allow using the ValidatorPluginManager and validator chains)
zendframework/zend-validator suggests installing zendframework/zend-session (Zend\Session component)
Writing lock file
Generating autoload files

#php test.php
hotelbeds\hotel_api_sdk\messages\availabilityRQ or hotelbeds\hotel_api_sdk\messages\availabilityRS not implemented in SDK

#mv vendor/hotelbeds/hotel-api-sdk-php/src/messages/AvailabilityRS.php vendor/hotelbeds/hotel-api-sdk-php/src/messages/availabilityRS.php 

#mv vendor/hotelbeds/hotel-api-sdk-php/src/messages/AvailabilityRQ.php vendor/hotelbeds/hotel-api-sdk-php/src/messages/availabilityRQ.php 

#php test.php 
Forbidden: <h1>Not Authorized</h1>

**Comment by Zavierazo** [comment]
Hola @xochilpili, por desgracia no encuentro explicación a tu problema, lo único que se me ocurre que la hora de tu maquina no este correctamente sincronizada. En todo caso de no ser eso puedes agregarme a skype a la misma dirección que te pase o darme acceso ssh a tu maquina para ver si encuentro el problema.

**Comment by xochilpili** [comment]
Zavierazo: 

Sí, le he estado dando muchas vueltas, nos han proporcionado los archivos xml y con ellos he podido trabajar. Sin embargo, esta solución es temporal.
Aquí son las 5 am, ya tengo que dormir. Te escribo al despertar a ver si nuestra diferencia horaria nos lo permite. 

Gracias!

**Comment by xochilpili** [comment]
Zavierazo: 

Me puedes agregar al Skype, mi usuario es : xochilpilli
Gracias.

**Comment by xochilpili** [comment]
Zavierazo:
He probado en otro server; éste no tiene instalado pear ni la dependencia pecl_http que mencionan en su documentación. Ahora obtengo lo siguiente: 

"Error parsing body - doesn't seem to be a chunked message"

**Comment by Zavierazo** [comment]
Hola, @xochilpili , puedes probar ir a HotelApiClient.php y modificar esta linea


```
       $this->httpClient->setOptions(
                ["adapter" => "Zend\Http\Client\Adapter\Curl",
                 "timeout" => $timeout]);
```
por
` $this->httpClient->setOptions(["timeout" => $timeout]);`

**Comment by xochilpili** [comment]
Zavierazo: 

Listo, ahora funciona!
Muchas gracias por todo.
¿Los métodos mostrados en la documentación están disponibles en el SDK?

Gracias y Saludos!

**Comment by Zavierazo** [comment]
Hola @xochilpili , los métodos mostrados http://hotelbeds-sdk.github.io/hotel-api-sdk-php/ están todos disponibles en el sdk. Esta documentación se esta generando a partir de los comentarios del propio código.

Procesado a cerrar la incidencia, cualquier otra duda, no dudes en reabrir o crear una nueva issue para que  te podamos ayudar.

**Comment by xochilpili** [comment]
Hola, perdonen, nuevamente...
Ahora me da el siguiente mensaje de error: 

Bad Request: Invalid data. Error at property occupancies: property is mandatory
Audit remote data = {"timestamp":"2016-07-25 19:40:51.041","requestHost":"209.126.127.139","serverId":"sa37AUX3ROLBLIS.env","environment":"[int, ignite]","release":"8f8516c469363d54ffa94ee260b468578804460f"}

Mismo código, aún no he podido experimentar con el SDK.
¿Tendrán algún manual de cómo hacer la conexión correctamente sin usar el SDK o por qué está pasando esto?
El asesor me ha dicho: "necesito saber la petición XML o JSON que envías" y para poder responderle esto, tendría que conocer más a fondo el SDK. Debido a la falta de tiempo y a la presión por mostrar avances, no tengo el tiempo suficiente como para comenzar a estudiar el SDK. Por ello la pregunta: ¿Tendrán algún manual de cómo hacer la conexión correctamente sin usar el SDK?

Gracias y una vez más disculpen las molestias.

**Comment by Zavierazo** [comment]
Hola @xochilpili, el error que te da es porque no estas rellenando la estructura de occupancies

```
$occupancy = new Occupancy();
$occupancy->adults = 2;
$occupancy->children = 1;
$occupancy->rooms = 1;

$occupancy->paxes = [ new Pax(Pax::AD, 30, "Mike", "Doe"), new Pax(Pax::AD, 27, "Jane", "Doe"), new Pax(Pax::CH, 8, "Mack", "Doe") ];
$rqData->occupancies = [ $occupancy ];
```

**Comment by xochilpili** [comment]
Zavierazo: 

Perfecto! me faltaba  : $rqData->occupancies = [ $occupancy ];

Tendrán algún manual para el SDK?
¿Cómo puedo obtener todos los destinos o zonas? 

Gracias

**Comment by Zavierazo** [comment]
Hola @xochilpili, todo ese tipo de informacion estatica la puedes sacar de el content-api https://developer.hotelbeds.com/docs/read/APITUDE_CONTENT . No tiene sdk.
