### ISSUE TITLE
How to use PHP SDK?

### ISSUE THREAD

**Issue by chonguyenvan** [hotelbeds-sdk/hotel-api-sdk-php#2]
Hello,

I have downloaded PHP SDK, but I don't found the document that detail to use to get hotels, hotel detail, booking and checkout.

Can we please give the detail document to tell to how to use SDK?

Thanks!

**Comment by hotelbeds-sdk** [comment]
Hi,
You can find all the documentation at https://developer.hotelbeds.com

Carlos Franco Capó

**Comment by tomeucapo** [comment]
Hi

We are working even in the SDK documentation specifies. However the response of availability can be obtained as an array using PHP or iterators system that builds objects Hotel, Room, Rate ... You can look at the examples in tests as HotelApiClientTest.php BookingApiTest.php and they can be useful. As my partner says, you can also use developer.hotelbeds.com documentation.
