### ISSUE TITLE
BadMethodCallException in Controller.php line 107: Method [assertNotEmpty] does not exist.

### ISSUE THREAD

**Issue by globatum** [hotelbeds-sdk/hotel-api-sdk-php#24]
> BadMethodCallException in Controller.php line 107:
> Method [assertNotEmpty] does not exist.

I'm using Laravel 5.2 and it's not clear what we should do with a room's "rate key".

In my route I have 

`Route::get('/checkRate/{firstRate}', 'RatesController@testCheckRate');`

which points to a function in my controller

```
    public function testCheckRate(Rate $firstRate)
    {
        $this->assertNotEmpty($firstRate->rateKey);
        $this->assertRegExp("/^[0-9]{8}|[0-9]{8}/", $firstRate->rateKey);

        $rqCheck = new \hotelbeds\hotel_api_sdk\helpers\CheckRate();
        $rqCheck->rooms = [ ["rateKey" => $firstRate->rateKey] ];

        return $this->apiClient->checkRate($rqCheck);
    }
```

but I get an error? This function is given in HotelAPIClientTest.php

Could someone walk me through what I'm supposed to do with a room's rate key after 

https://github.com/hotelbeds-sdk/hotel-api-sdk-php/wiki/Step-by-step-guide-to-start-from-scratch

**Comment by Zavierazo** [comment]
Hi @globatum, i think you don't fill correctly $fistRate parameter. 

The checkrates method can complement the booking process, as it returns additional information to the availability request, like cancellation policies. However, when the rateType value is "RECHECK", the checkrates method is mandatory.

You will need to fill $firstRate->rateKey with the desired rateKey from availability. For example line 132 of https://github.com/hotelbeds-sdk/hotel-api-sdk-php/blob/master/tests/HotelApiClientTest.php

**Comment by globatum** [comment]
question has been rephrased
