### ISSUE TITLE
hotelbeds\hotel_api_sdk\messages\availabilityRQ or hotelbeds\hotel_api_sdk\messages\availabilityRS not implemented in SDK

### ISSUE THREAD

**Issue by globatum** [hotelbeds-sdk/hotel-api-sdk-php#26]
Not sure why I'm getting this error.

I'm using the following

```
use hotelbeds\hotel_api_sdk\HotelApiClient;
use hotelbeds\hotel_api_sdk\messages\BookingConfirmRS;
use hotelbeds\hotel_api_sdk\messages\CheckRateRS;
use hotelbeds\hotel_api_sdk\messages\CheckRateRQ;
use hotelbeds\hotel_api_sdk\model\Geolocation;
use hotelbeds\hotel_api_sdk\model\Hotels;
use hotelbeds\hotel_api_sdk\model\Destination;
use hotelbeds\hotel_api_sdk\model\Occupancy;
use hotelbeds\hotel_api_sdk\model\Pax;
use hotelbeds\hotel_api_sdk\model\Rate;
use hotelbeds\hotel_api_sdk\model\Stay;
use hotelbeds\hotel_api_sdk\types\ApiVersion;
use hotelbeds\hotel_api_sdk\types\ApiVersions;
use hotelbeds\hotel_api_sdk\messages\AvailabilityRS;
use hotelbeds\hotel_api_sdk\messages\AvailabilityRQ;
use hotelbeds\hotel_api_sdk\messages\BookingListRS;

```

a previous github conversation mentioned that the letters should start with capital...but the error shows lowercase...and it doesn't work when I try either or.

I'm running Laravel 5.2 on Forge Server. The SDK works locally, but not when deployed to a production server.

**Comment by globatum** [comment]
My solution for this was to modfiy HotelApiClient.php

```
$sdkMethod = ucfirst($sdkMethod);
        $sdkClassRQ = "hotelbeds\\hotel_api_sdk\\messages\\".$sdkMethod."RQ";
        $sdkClassRS = "hotelbeds\\hotel_api_sdk\\messages\\".$sdkMethod."RS";
```

This fixed the problem, but now I think it is creating other issues

**Comment by Zavierazo** [comment]
Hi @globatum, try with this call:

` $availRS = $apiClient->Availability($rqData);`

Method call must be Uppercased. This is because Linux is case sensitive and Windows not, that's why a class name could not be found. 

Tell me if it work and i will changue the step by step guide to avoid future problems. https://github.com/hotelbeds-sdk/hotel-api-sdk-php/wiki/Step-by-step-guide-to-start-from-scratch

**Comment by globatum** [comment]
@Zavierazo this was the solution! It also fixed the other issue I had with Paxes 👍
