### ISSUE TITLE
Bad Request: Invalid data. Error at property occupancies: The number of children is wrong

### ISSUE THREAD

**Issue by globatum** [hotelbeds-sdk/hotel-api-sdk-php#27]
I consistently get this error when trying to run this occupancy

```
$occupancy = new Occupancy();
$occupancy->adults = 2;
$occupancy->children = 1;
$occupancy->rooms = 1;
$rqData->occupancies = [ $occupancy ];
```

`Bad Request: Invalid data. Error at property occupancies: The number of children is wrong`

It's not clear why I'm getting this error

```
$rqData = new \hotelbeds\hotel_api_sdk\helpers\Availability();
		$rqData->stay = new Stay(DateTime::createFromFormat("Y-m-d", $checkin),
		                         DateTime::createFromFormat("Y-m-d", $checkout));
		$geolocation = new Geolocation();
        $geolocation->latitude = (double)$lat;
        $geolocation->longitude= (double)$long;
        $geolocation->radius= (double)1;
        $geolocation->unit= Geolocation::KM;

        $rqData->geolocation = $geolocation;
		
		$occupancy = new Occupancy();
		$occupancy->adults = 2;
		$occupancy->children = 1;
		$occupancy->rooms = 1;

		$rqData->occupancies = [ $occupancy ];

		try {
    		$availRS = $apiClient->availability($rqData);
		} catch (\hotelbeds\hotel_api_sdk\types\HotelSDKException $e) {
		    $auditData = $e->getAuditData();
		    error_log( $e->getMessage() );
		    error_log( "Audit remote data = ".json_encode((array)$auditData));
		    print_r($e->getMessage());
		    exit();
		} catch (Exception $e) {
		    error_log( $e->getMessage() );
		    print_r($e->getMessage());
		    exit();
		}
```

**Comment by Zavierazo** [comment]
Hi @globatum , this error is because you dont fill the pax info por children. For children is mandatory.

`
$occupancy->paxes = [ new Pax(Pax::AD, 30, "Mike", "Doe"), new Pax(Pax::AD, 27, "Jane", "Doe"), new Pax(Pax::CH, 8, "Mack", "Doe") ];
`

**Comment by globatum** [comment]
@Zavierazo I do this, but when I push onto a production server (non-localhost) it does not recognize that occupancy data.

Example Rate Keys:

On production Server:

`20160831|20160903|W|255|13569|TWN.SU|ID_B2B_20|RO|RA1BB2BHB|1~1~0||N@978494795`

on Localhost:

20160831|20160903|W|255|13569|TWN.SU|ID_B2B_20|RO|RA1BB2BHB|1~1~2|12~14|N@-1894808292

and the queries are the exact same in terms of code use

the error `Bad Request: Invalid data. Error at property occupancies: The number of children is wrong` shows up on localhost but not on my production server

**Comment by Zavierazo** [comment]
Hi, @globatum, can you put this line before execute the availability and tell me the output on both environments?

`echo \Zend\Json\Json::encode($rqData);`

**Comment by globatum** [comment]
Local response:

```{"stay":{"checkIn":"2016-08-31","checkOut":"2016-09-03"},"geolocation":{"latitude":38.897930145264,"longitude":-77.036430358887,"radius":1,"unit":"km"},"occupancies":[{"rooms":2,"children":2,"adults":2,"paxes":[{"age":12,"type":"CH"},{"age":14,"type":"CH"}]}]}```

The response is empty on my production server

**Comment by globatum** [comment]
Issue #26 addressed this problem
