### ISSUE TITLE
Service Unavailable: ProductException(5f61fb52-b67d-4212-bfe7-8759b015d1c0, CHECK_RATE, Hotel not Available):

### ISSUE THREAD

**Issue by globatum** [hotelbeds-sdk/hotel-api-sdk-php#28]
Not sure why I keep getting this error when trying to book rooms for X number of children

This is the rateKey
`20160824|20160826|W|255|13569|JSU.KG|ID_B2B_20|RO|RA1B2BHB|2~2~2|12~14|N@-549551370`

**Comment by Zavierazo** [comment]
Hi @globatum, this error occurs when the product is still not available. When this happens , it is because someone while you were doing the booking process has reserved the last quota of the rate.
