### ISSUE TITLE
How to dynamically add PAX to booking search?

### ISSUE THREAD

**Issue by globatum** [hotelbeds-sdk/hotel-api-sdk-php#29]
It's not clear how I can create a PAX array based on user input. 
```
if($children == 1){
$occupancy->paxes = [ new Pax(PAX::CH, $age) ];
}
if($children == 2){
$occupancy->paxes = [ new Pax(PAX::CH, $age), new Pax(PAX::CH, $age) ];
}
```

The above is not scalable. How can I take a responsive approach because it does not accept string?

(the code below does not work)

```
$paxes = "new Pax(PAX::CH, $age)";
$occupancy->paxes = "[ $paxes ]";
```

Using new Pax multiple times does not work either

```
$occupancy->paxes = [ new Pax(PAX::CH, $age)];
$occupancy->paxes = [ new Pax(PAX::CH, $age)];
$occupancy->paxes = [ new Pax(PAX::CH, $age)];
```

because they just overwrite each other.
Can you add an insert feature?

```
$occupancy->paxes->insert = [ new Pax(PAX::CH, $age)];
$occupancy->paxes->insert = [ new Pax(PAX::CH, $age)];
$occupancy->paxes->insert = [ new Pax(PAX::CH, $age)];
```

so that we can use the Pax code in a for or foreach loop?

**Comment by Zavierazo** [comment]
Hi @globatum, there is an example

`$childAges= [2];
$adultAges=[30,33];

$occupancy->adults = count($adultAges);
$occupancy->children = count($childAges);
$occupancy->rooms = 1;
$guests=array_fill(0, $occupancy->adults+$occupancy->children, NULL);
$pos=0;
for ($x=0;$x<$occupancy->adults; $x++){
    $guests[$pos]= new Pax(Pax::AD, $adultAges[$x], "Test", "ts");
    $pos++;
}
for ($y=0;$y<$occupancy->children; $y++) {
    $guests[$pos]= new Pax(Pax::CH, $childAges[$y], "Test", "ts");
    $pos++;
}
$occupancy->paxes =$guests;
$rqData->occupancies = [ $occupancy ];`

**Comment by mcorderoaraya** [comment]
Si eso es lo trataré de implementar, muchas gracias
