### ISSUE TITLE
Error 500 while trying to execute the test code

### ISSUE THREAD

**Issue by dfriasruiz** [hotelbeds-sdk/hotel-api-sdk-php#3]
Hi!

I've installed the SDK for PHP without any problem but, when I try to test the test code, I have a 500 error. It's seem like if some class crash but I haven't found any check list of the needed classes. Any idea?

Regards and thanks,

Daniel

**Comment by tomeucapo** [comment]
Hi

We need more info about 500, like a error_log of Apache. For example?

Thanks

**Comment by sangdao-dirox** [comment]
Hi, Hi got a Exception
Error accessing API: Unable to enable crypto on TCP connection api.test.hotelbeds.com: make sure the "sslcafile" or "sslcapath" option are properly set for the environment.

And then I have to add $this->httpClient->setOptions( array( 'sslcapath' => '/etc/ssl/certs' )); into HotelApiClient::__construct after line "$this->httpClient = new Client();"

Can you check please?

**Comment by dfriasruiz** [comment]
Here is the error_log:

[Fri Mar 04 11:22:01.184641 2016] [proxy_fcgi:error] [pid 13646] [client 212.97.161.142:54033] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught exception 'Exception' with message 'hotelbeds\\hotel_api_sdk\\messages\\availabilityRQ or hotelbeds\\hotel_api_sdk\\messages\\availabilityRS not implemented in SDK' in /var/www/vhosts/dev.yupiketing.com/httpdocs/hotelbeds/src/HotelApiClient.php:87\nStack trace:\n#0 /var/www/vhosts/dev.yupiketing.com/httpdocs/hotelbeds/index.php(37): hotelbeds\\hotel_api_sdk\\HotelApiClient->__call('availability', Array)\n#1 /var/www/vhosts/dev.yupiketing.com/httpdocs/hotelbeds/index.php(37): hotelbeds\\hotel_api_sdk\\HotelApiClient->availability(Object(hotelbeds\\hotel_api_sdk\\helpers\\Availability))\n#2 {main}\n  thrown in /var/www/vhosts/dev.yupiketing.com/httpdocs/hotelbeds/src/HotelApiClient.php on line 87\n'

Thanks!

**Comment by tomeucapo** [comment]
Hola

Primeramente deberías usar un try/catch similar al del ejemplo para poder pintar de manera correcta el error. Luego lo que tendrías que mirar si realmente usas correctamente el SDK, o sea como lo cargas? Sólo hay una manera de hacerlo que es la que hay en el ejemplo usando autoloader, si lo llamas con include/requires no te funcionarà.

P.D.: El error que te da es que no puede cargar ni la clase AvailabilityRQ ni AvailabilityRS debido a que no las encuentra, y eso puede ser debido a lo que te explico de que o bién usas includes/requires para cargar la libreria y no usas el autoloader como especifica el PSR-0 http://www.php-fig.org/psr/psr-0/, asi mismo el proyecto dispone del autoloader si sigues los pasos de usarlo con composer.

Saludos

**Comment by dfriasruiz** [comment]
Buenos días.

Gracias por la respuesta.

El log que he reportado es del ejemplo que se da en la documentación, no se ha cambiado ni una coma (por eso creo que puede ser problema de la configuración del servidor).

Voy a ver si consigo más información como me propones.

Un saludo y gracias,

Daniel

**Comment by dfriasruiz** [comment]
Buenos días.

No logramos avanzar con este tema, ¿podría daros acceso al servidor para que podáis hacer alguna prueba rápida? Sería de mucha ayuda porque estamos que ni para adelante ni para atrás.

Un saludo,

Daniel

**Comment by dfriasruiz** [comment]
Hola / Hi.

Alguien sabe algún servidor donde probar la sdk? Estamos intentandolo en una VPS de Strato pero es imposible. / Does anybody know any server to try the sdk? We are trying in Strato VPS but is impossible.

Gracias / Thanks

**Comment by alvmunoz** [comment]
Lo mejor es que las pruebes en local antes de ponerlo en ningún servidor. Y una vez consigas que te funcione en local ya lo subas a cualquier servidor que soporte PHP.

**Comment by pralamo** [comment]
yo soluvioné ese error renombrando el fichero /messages/AvailabilityRQ.php  a availabilityRQ.php.

Al hacer el load file, se busca un fichero que comienza en minusculas. Lo mismo pasa con con BookingRQ, BookingRS, CheckRQ y CheckRS. Todos los ficheros del directorio messages. Deben comenzar en minúscula.
saludos

**Comment by mjsorribas** [comment]
A mi también se me corrigió el problema cambiando a minúsculas los archivos, lo que no pude encontrar es donde corregir esto para que no haya que realizar este cambio.

**Comment by alvmunoz** [comment]
Subiremos una versión que tenga esto corregido.

**Comment by alvmunoz** [comment]
Ya está subido. Si actualizáis ahora todas las llamadas deberían de ser en mayúsculas.

**Comment by onursonmez** [comment]
replace 
$availRS = $apiClient->availability($rqData);
to
$availRS = $apiClient->Availability($rqData);
