### ISSUE TITLE
Multi pax for multiple room

### ISSUE THREAD

**Issue by amitras** [hotelbeds-sdk/hotel-api-sdk-php#30]
Hi All,
We are facing some issue when searching with multiple room with multi pax. We didn't understand how to combine price with different-different ratekey. We attached request and response. Kindly provide solution how to solve this problem.

[hotelsRQ.txt](https://github.com/hotelbeds-sdk/hotel-api-sdk-php/files/411088/hotelsRQ.txt)
[hotelsRS.txt](https://github.com/hotelbeds-sdk/hotel-api-sdk-php/files/411089/hotelsRS.txt)

Regards,
Amit

**Comment by Zavierazo** [comment]
Hi @amitras , yo can relate occupancy with price with the fields rooms, adults, children and childrenAges. For example:

rq.rooms==price.rooms
rq.adults==price.adults
rq.children==price.children
rq.paxes(Age of childrens)==price.childrenAges

```
 "occupancies": [{
		"rooms": 1,
		"adults": 1,
		"children": 2,
		"paxes": [{
			"age": 30,
			"type": "AD"
		},
		{
			"age": 3,
			"type": "CH"
		},
		{
			"age": 6,
			"type": "CH"
		}]
	},
```

```
"rateKey": "20161202|20161203|W|1|6914|DBL.ST|ID_B2B_22|RO|NETRANRF|1~1~2|3~6|N@-657866394",
"rateClass": "NRF",
"rateType": "RECHECK",
"net": "109.20",
"allotment": 99,
"paymentType": "AT_WEB",
"packaging": false,
"boardCode": "RO",
"boardName": "SOLO HABITACIÓN",
"rooms": 1,
"adults": 1,
"children": 2,
"childrenAges": "3,6"
```

**Comment by amitras** [comment]
Hi All,

This is correct  for one room but when we select two or more room with different children age how to calculate price for both room because there are many room for one hotel with different children age.

For the given example request (send by you for 2 rooms)  the response has got different prices for each room individually. Now how do we sum the prices for both the room? Can you help us in understanding the response i.e how do we take out cost of 2 rooms of same room type?

**Comment by Zavierazo** [comment]
Hi @amitras, you can sum the prices of the combinations of prices with different occupancy. 

Price of occupancy 1 + Price of occupancy 2 = Total price of both

**Comment by amitras** [comment]
Hi,
   There are many combinations according to occupancy type i.e consider one of the sample response for following occupancy of 2 rooms with 2 adult and 1 child each (6 and 9 years of age)


Response is

`Array
(
    [0] => Array
        (
            [code] => APT.1B-1
            [name] => APARTMENT ONE BED
            [rates] => Array
                (
                    [0] => Array
                        (
                            [rateKey] => 20161214|20161217|W|1|146536|APT.1B-1|CG-BRIT|SC||1~2~1|9|N@DE34871B99F94A2798E6D5CD3AF10986
                            [rateClass] => NOR
                            [rateType] => BOOKABLE
                            [net] => 130.16
                            [allotment] => 2
                            [rateCommentsId] => 1|95327|3
                            [paymentType] => AT_WEB
                            [packaging] => 
                            [boardCode] => SC
                            [boardName] => SELF CATERING
                            [cancellationPolicies] => Array
                                (
                                    [0] => Array
                                        (
                                            [amount] => 38.97
                                            [from] => 2016-12-11T23:59:00+01:00
                                        )

                                )

                            [rooms] => 1
                            [adults] => 2
                            [children] => 1
                            [childrenAges] => 9
                            [offers] => Array
                                (
                                    [0] => Array
                                        (
                                            [code] => 9002
                                            [name] => Early Booking discount
                                            [amount] => -22.97
                                        )

                                    [1] => Array
                                        (
                                            [code] => 9001
                                            [name] => Child discount
                                            [amount] => -30.63
                                        )

                                )

                        )

                    [1] => Array
                        (
                            [rateKey] => 20161214|20161217|W|1|146536|APT.1B-1|CG-BRIT|BB||1~2~1|9|N@DE34871B99F94A2798E6D5CD3AF10986
                            [rateClass] => NOR
                            [rateType] => BOOKABLE
                            [net] => 176.00
                            [allotment] => 2
                            [rateCommentsId] => 1|95327|3
                            [paymentType] => AT_WEB
                            [packaging] => 
                            [boardCode] => BB
                            [boardName] => BED AND BREAKFAST
                            [cancellationPolicies] => Array
                                (
                                    [0] => Array
                                        (
                                            [amount] => 54.25
                                            [from] => 2016-12-11T23:59:00+01:00
                                        )

                                )

                            [rooms] => 1
                            [adults] => 2
                            [children] => 1
                            [childrenAges] => 9
                            [offers] => Array
                                (
                                    [0] => Array
                                        (
                                            [code] => 9002
                                            [name] => Early Booking discount
                                            [amount] => -31.07
                                        )

                                    [1] => Array
                                        (
                                            [code] => 9001
                                            [name] => Child discount
                                            [amount] => -41.43
                                        )

                                )

                        )

                    [2] => Array
                        (
                            [rateKey] => 20161214|20161217|W|1|146536|APT.1B-1|CG-BRIT|HB||1~2~1|9|N@DE34871B99F94A2798E6D5CD3AF10986
                            [rateClass] => NOR
                            [rateType] => BOOKABLE
                            [net] => 206.63
                            [allotment] => 2
                            [rateCommentsId] => 1|95327|3
                            [paymentType] => AT_WEB
                            [packaging] => 
                            [boardCode] => HB
                            [boardName] => HALF BOARD
                            [cancellationPolicies] => Array
                                (
                                    [0] => Array
                                        (
                                            [amount] => 64.46
                                            [from] => 2016-12-11T23:59:00+01:00
                                        )

                                )

                            [rooms] => 1
                            [adults] => 2
                            [children] => 1
                            [childrenAges] => 9
                            [offers] => Array
                                (
                                    [0] => Array
                                        (
                                            [code] => 9002
                                            [name] => Early Booking discount
                                            [amount] => -36.41
                                        )

                                    [1] => Array
                                        (
                                            [code] => 9001
                                            [name] => Child discount
                                            [amount] => -48.60
                                        )

                                )

                        )

                    [3] => Array
                        (
                            [rateKey] => 20161214|20161217|W|1|146536|APT.1B-1|CG-BRIT|AI||1~2~1|9|N@DE34871B99F94A2798E6D5CD3AF10986
                            [rateClass] => NOR
                            [rateType] => BOOKABLE
                            [net] => 250.11
                            [allotment] => 2
                            [rateCommentsId] => 1|95327|3
                            [paymentType] => AT_WEB
                            [packaging] => 
                            [boardCode] => AI
                            [boardName] => ALL INCLUSIVE
                            [cancellationPolicies] => Array
                                (
                                    [0] => Array
                                        (
                                            [amount] => 75.89
                                            [from] => 2016-12-11T23:59:00+01:00
                                        )

                                )

                            [rooms] => 1
                            [adults] => 2
                            [children] => 1
                            [childrenAges] => 9
                            [offers] => Array
                                (
                                    [0] => Array
                                        (
                                            [code] => 9002
                                            [name] => Early Booking discount
                                            [amount] => -44.17
                                        )

                                    [1] => Array
                                        (
                                            [code] => 9001
                                            [name] => Child discount
                                            [amount] => -58.86
                                        )

                                )

                        )

                )

        )

    [1] => Array
        (
            [code] => APT.SS
            [name] => APARTMENT SIDE SEA VIEW
            [rates] => Array
                (
                    [0] => Array
                        (
                            [rateKey] => 20161214|20161217|W|1|146536|APT.SS|CG-BRIT|SC||1~2~1|9|N@DE34871B99F94A2798E6D5CD3AF10986
                            [rateClass] => NOR
                            [rateType] => BOOKABLE
                            [net] => 139.71
                            [allotment] => 4
                            [rateCommentsId] => 1|95327|3
                            [paymentType] => AT_WEB
                            [packaging] => 
                            [boardCode] => SC
                            [boardName] => SELF CATERING
                            [cancellationPolicies] => Array
                                (
                                    [0] => Array
                                        (
                                            [amount] => 42.15
                                            [from] => 2016-12-11T23:59:00+01:00
                                        )

                                )

                            [rooms] => 1
                            [adults] => 2
                            [children] => 1
                            [childrenAges] => 9
                            [offers] => Array
                                (
                                    [0] => Array
                                        (
                                            [code] => 9002
                                            [name] => Early Booking discount
                                            [amount] => -24.69
                                        )

                                    [1] => Array
                                        (
                                            [code] => 9001
                                            [name] => Child discount
                                            [amount] => -32.88
                                        )

                                )

                        )

                    [1] => Array
                        (
                            [rateKey] => 20161214|20161217|W|1|146536|APT.SS|CG-BRIT|BB||1~2~1|9|N@DE34871B99F94A2798E6D5CD3AF10986
                            [rateClass] => NOR
                            [rateType] => BOOKABLE
                            [net] => 185.55
                            [allotment] => 4
                            [rateCommentsId] => 1|95327|3
                            [paymentType] => AT_WEB
                            [packaging] => 
                            [boardCode] => BB
                            [boardName] => BED AND BREAKFAST
                            [cancellationPolicies] => Array
                                (
                                    [0] => Array
                                        (
                                            [amount] => 57.43
                                            [from] => 2016-12-11T23:59:00+01:00
                                        )

                                )

                            [rooms] => 1
                            [adults] => 2
                            [children] => 1
                            [childrenAges] => 9
                            [offers] => Array
                                (
                                    [0] => Array
                                        (
                                            [code] => 9002
                                            [name] => Early Booking discount
                                            [amount] => -32.79
                                        )

                                    [1] => Array
                                        (
                                            [code] => 9001
                                            [name] => Child discount
                                            [amount] => -43.68
                                        )

                                )

                        )

                    [2] => Array
                        (
                            [rateKey] => 20161214|20161217|W|1|146536|APT.SS|CG-BRIT|HB||1~2~1|9|N@DE34871B99F94A2798E6D5CD3AF10986
                            [rateClass] => NOR
                            [rateType] => BOOKABLE
                            [net] => 216.18
                            [allotment] => 4
                            [rateCommentsId] => 1|95327|3
                            [paymentType] => AT_WEB
                            [packaging] => 
                            [boardCode] => HB
                            [boardName] => HALF BOARD
                            [cancellationPolicies] => Array
                                (
                                    [0] => Array
                                        (
                                            [amount] => 67.64
                                            [from] => 2016-12-11T23:59:00+01:00
                                        )

                                )

                            [rooms] => 1
                            [adults] => 2
                            [children] => 1
                            [childrenAges] => 9
                            [offers] => Array
                                (
                                    [0] => Array
                                        (
                                            [code] => 9002
                                            [name] => Early Booking discount
                                            [amount] => -38.13
                                        )

                                    [1] => Array
                                        (
                                            [code] => 9001
                                            [name] => Child discount
                                            [amount] => -50.85
                                        )

                                )

                        )

                    [3] => Array
                        (
                            [rateKey] => 20161214|20161217|W|1|146536|APT.SS|CG-BRIT|AI||1~2~1|9|N@DE34871B99F94A2798E6D5CD3AF10986
                            [rateClass] => NOR
                            [rateType] => BOOKABLE
                            [net] => 259.66
                            [allotment] => 4
                            [rateCommentsId] => 1|95327|3
                            [paymentType] => AT_WEB
                            [packaging] => 
                            [boardCode] => AI
                            [boardName] => ALL INCLUSIVE
                            [cancellationPolicies] => Array
                                (
                                    [0] => Array
                                        (
                                            [amount] => 79.07
                                            [from] => 2016-12-11T23:59:00+01:00
                                        )

                                )

                            [rooms] => 1
                            [adults] => 2
                            [children] => 1
                            [childrenAges] => 9
                            [offers] => Array
                                (
                                    [0] => Array
                                        (
                                            [code] => 9002
                                            [name] => Early Booking discount
                                            [amount] => -45.89
                                        )

                                    [1] => Array
                                        (
                                            [code] => 9001
                                            [name] => Child discount
                                            [amount] => -61.11
                                        )

                                )

                        )

                )

        )

    [2] => Array
        (
            [code] => APT.VM
            [name] => APARTMENT SEA VIEW
            [rates] => Array
                (
                    [0] => Array
                        (
                            [rateKey] => 20161214|20161217|W|1|146536|APT.VM|CG-BRIT|SC||1~2~1|9|N@DE34871B99F94A2798E6D5CD3AF10986
                            [rateClass] => NOR
                            [rateType] => BOOKABLE
                            [net] => 149.27
                            [allotment] => 5
                            [rateCommentsId] => 1|95327|3
                            [paymentType] => AT_WEB
                            [packaging] => 
                            [boardCode] => SC
                            [boardName] => SELF CATERING
                            [cancellationPolicies] => Array
                                (
                                    [0] => Array
                                        (
                                            [amount] => 45.35
                                            [from] => 2016-12-11T23:59:00+01:00
                                        )

                                )

                            [rooms] => 1
                            [adults] => 2
                            [children] => 1
                            [childrenAges] => 9
                            [offers] => Array
                                (
                                    [0] => Array
                                        (
                                            [code] => 9002
                                            [name] => Early Booking discount
                                            [amount] => -26.35
                                        )

                                    [1] => Array
                                        (
                                            [code] => 9001
                                            [name] => Child discount
                                            [amount] => -35.12
                                        )

                                )

                        )

                    [1] => Array
                        (
                            [rateKey] => 20161214|20161217|W|1|146536|APT.VM|CG-BRIT|BB||1~2~1|9|N@DE34871B99F94A2798E6D5CD3AF10986
                            [rateClass] => NOR
                            [rateType] => BOOKABLE
                            [net] => 195.11
                            [allotment] => 5
                            [rateCommentsId] => 1|95327|3
                            [paymentType] => AT_WEB
                            [packaging] => 
                            [boardCode] => BB
                            [boardName] => BED AND BREAKFAST
                            [cancellationPolicies] => Array
                                (
                                    [0] => Array
                                        (
                                            [amount] => 60.63
                                            [from] => 2016-12-11T23:59:00+01:00
                                        )

                                )

                            [rooms] => 1
                            [adults] => 2
                            [children] => 1
                            [childrenAges] => 9
                            [offers] => Array
                                (
                                    [0] => Array
                                        (
                                            [code] => 9002
                                            [name] => Early Booking discount
                                            [amount] => -34.45
                                        )

                                    [1] => Array
                                        (
                                            [code] => 9001
                                            [name] => Child discount
                                            [amount] => -45.92
                                        )

                                )

                        )

                    [2] => Array
                        (
                            [rateKey] => 20161214|20161217|W|1|146536|APT.VM|CG-BRIT|HB||1~2~1|9|N@DE34871B99F94A2798E6D5CD3AF10986
                            [rateClass] => NOR
                            [rateType] => BOOKABLE
                            [net] => 225.74
                            [allotment] => 5
                            [rateCommentsId] => 1|95327|3
                            [paymentType] => AT_WEB
                            [packaging] => 
                            [boardCode] => HB
                            [boardName] => HALF BOARD
                            [cancellationPolicies] => Array
                                (
                                    [0] => Array
                                        (
                                            [amount] => 70.84
                                            [from] => 2016-12-11T23:59:00+01:00
                                        )

                                )

                            [rooms] => 1
                            [adults] => 2
                            [children] => 1
                            [childrenAges] => 9
                            [offers] => Array
                                (
                                    [0] => Array
                                        (
                                            [code] => 9002
                                            [name] => Early Booking discount
                                            [amount] => -39.79
                                        )

                                    [1] => Array
                                        (
                                            [code] => 9001
                                            [name] => Child discount
                                            [amount] => -53.09
                                        )

                                )

                        )

                    [3] => Array
                        (
                            [rateKey] => 20161214|20161217|W|1|146536|APT.VM|CG-BRIT|AI||1~2~1|9|N@DE34871B99F94A2798E6D5CD3AF10986
                            [rateClass] => NOR
                            [rateType] => BOOKABLE
                            [net] => 269.22
                            [allotment] => 5
                            [rateCommentsId] => 1|95327|3
                            [paymentType] => AT_WEB
                            [packaging] => 
                            [boardCode] => AI
                            [boardName] => ALL INCLUSIVE
                            [cancellationPolicies] => Array
                                (
                                    [0] => Array
                                        (
                                            [amount] => 82.27
                                            [from] => 2016-12-11T23:59:00+01:00
                                        )

                                )

                            [rooms] => 1
                            [adults] => 2
                            [children] => 1
                            [childrenAges] => 9
                            [offers] => Array
                                (
                                    [0] => Array
                                        (
                                            [code] => 9002
                                            [name] => Early Booking discount
                                            [amount] => -47.55
                                        )

                                    [1] => Array
                                        (
                                            [code] => 9001
                                            [name] => Child discount
                                            [amount] => -63.35
                                        )

                                )

                        )

                )

        )

)

Here if we do permutation of all the options then its going to be huge price list. Please suggest on how we can do meaningful combination of rooms and prices

**Comment by alvmunoz** [comment]
Hi @amitras ,
If you request 2 rooms, the price shown includes both rooms, you don't need to make any combinations.

**Comment by amitras** [comment]
Hi,

Is it true for all cases ? For Example: If I selected two rooms. In one room  2 adult ,1 children and child age is 9 and another room 2adult , 2 children and child age is 11,13 respectively.

Response like:


Array
(
    [0] => Array
        (
            [code] => APT.B1-1
            [name] => APARTMENT ONE BEDROOM
            [rates] => Array
                (
                    [0] => Array
                        (
                            [rateKey] => 20161214|20161217|W|1|29319|APT.B1-1|CG-TODOS1|SC||1~2~1|9|N@261A853DDB7349BBBF38888BE69A35F1
                            [rateClass] => NOR
                            [rateType] => BOOKABLE
                            [net] => 96.27
                            [allotment] => 3
                            [rateCommentsId] => 1|95424|3
                            [paymentType] => AT_WEB
                            [packaging] => 
                            [boardCode] => SC
                            [boardName] => SELF CATERING
                            [cancellationPolicies] => Array
                                (
                                    [0] => Array
                                        (
                                            [amount] => 32.09
                                            [from] => 2016-12-11T23:59:00+01:00
                                        )

                                )

                            [rooms] => 1
                            [adults] => 2
                            [children] => 1
                            [childrenAges] => 9
                            [offers] => Array
                                (
                                    [0] => Array
                                        (
                                            [code] => 9002
                                            [name] => Early Booking discount
                                            [amount] => -17.01
                                        )

                                )

                        )

                    [1] => Array
                        (
                            [rateKey] => 20161214|20161217|W|1|29319|APT.B1-1|CG-TODOS1|SC||1~2~2|13~9|N@261A853DDB7349BBBF38888BE69A35F1
                            [rateClass] => NOR
                            [rateType] => BOOKABLE
                            [net] => 96.27
                            [allotment] => 3
                            [rateCommentsId] => 1|95424|3
                            [paymentType] => AT_WEB
                            [packaging] => 
                            [boardCode] => SC
                            [boardName] => SELF CATERING
                            [cancellationPolicies] => Array
                                (
                                    [0] => Array
                                        (
                                            [amount] => 32.09
                                            [from] => 2016-12-11T23:59:00+01:00
                                        )

                                )

                            [rooms] => 1
                            [adults] => 2
                            [children] => 2
                            [childrenAges] => 13,9
                            [offers] => Array
                                (
                                    [0] => Array
                                        (
                                            [code] => 9002
                                            [name] => Early Booking discount
                                            [amount] => -17.01
                                        )

                                )

                        )

                )

        )

    [1] => Array
        (
            [code] => APT.B2-1
            [name] => APARTMENT TWO BEDROOMS
            [rates] => Array
                (
                    [0] => Array
                        (
                            [rateKey] => 20161214|20161217|W|1|29319|APT.B2-1|CG-TODOS1|SC||1~2~1|9|N@261A853DDB7349BBBF38888BE69A35F1
                            [rateClass] => NOR
                            [rateType] => BOOKABLE
                            [net] => 149.79
                            [allotment] => 1
                            [rateCommentsId] => 1|95424|3
                            [paymentType] => AT_WEB
                            [packaging] => 
                            [boardCode] => SC
                            [boardName] => SELF CATERING
                            [cancellationPolicies] => Array
                                (
                                    [0] => Array
                                        (
                                            [amount] => 49.93
                                            [from] => 2016-12-11T23:59:00+01:00
                                        )

                                )

                            [rooms] => 1
                            [adults] => 2
                            [children] => 1
                            [childrenAges] => 9
                            [offers] => Array
                                (
                                    [0] => Array
                                        (
                                            [code] => 9002
                                            [name] => Early Booking discount
                                            [amount] => -26.46
                                        )

                                )

                        )

                )

        )

) 

Please suggest on how we can do meaningful combination of rooms and prices.

**Comment by alvmunoz** [comment]
How do you display this information to the customer is up to you. For example, you can filter by board or price in the request and then you can combine prices with the same board or only combine the cheapest rates.

**Comment by amitras** [comment]
Hi All,

I have attached request and response for search with 2 room and 2 adults each  but booking is not confirm because of only one rate-key we found. So please tell us how to solve this problem.

[response_19aug16.txt](https://github.com/hotelbeds-sdk/hotel-api-sdk-php/files/427525/response_19aug16.txt)
[request_19aug16.txt](https://github.com/hotelbeds-sdk/hotel-api-sdk-php/files/427526/request_19aug16.txt)

**Comment by alvmunoz** [comment]
Hi @amitras ,  use this only for issues related to the SDK.  Any questions about the API, please contact to apitude@hotelbeds.com 
Thanks,

**Comment by amitras** [comment]
Hi All,

I have created one booking for french or turkey name but booking response give an error. I have attached request and response.

Kindly tell us how to fix this problem.

[booking_request.txt](https://github.com/hotelbeds-sdk/hotel-api-sdk-php/files/429792/booking_request.txt)
[booking_response.txt](https://github.com/hotelbeds-sdk/hotel-api-sdk-php/files/429793/booking_response.txt)
