### ISSUE TITLE
Destination search is not available by default

### ISSUE THREAD

**Issue by shiyukun** [hotelbeds-sdk/hotel-api-sdk-php#35]
Hi Team, 
I test the sample code, and get exception
"Bad Request: Invalid data. Destination search is not available by default. Please contact with API Distribution Team"

$apiClient = new HotelApiClient("https://api.test.hotelbeds.com",
                                "xxxxxx",
                                "xxxx",
                                new ApiVersion(ApiVersion::V1_0),
                                120);

$rqData = new \hotelbeds\hotel_api_sdk\helpers\Availability();
$rqData->stay = new Stay(DateTime::createFromFormat("Y-m-d", "2017-03-01"),
                         DateTime::createFromFormat("Y-m-d", "2017-03-10"));

$rqData->destination = new Destination("PMI");

**Comment by alvmunoz** [comment]
Hi @shiyukun  ,  yes, that's correct.
We will change the sample code to use a hotel search instead. 
Thank you

**Comment by shiyukun** [comment]
thanks for your reply, I think it is apikey level problem. I use another apikey, it works well.

**Comment by Zavierazo** [comment]
Sample changed!
