### ISSUE TITLE
Don't see "creditCards" information in availabilityRS

### ISSUE THREAD

**Issue by CoreJADeveloper** [hotelbeds-sdk/hotel-api-sdk-php#36]
Hi team!

I am trying to retrieve `creditCards` information from availability response. But I don't see any `creditCards` information. I get available rooms from my searched hotels codes.

Even I don't see any availability request parameter to make it identify that the request should send back `creditCards` information.

I added following request parameters -

```
$rqData->hotels = ["hotel" => [$hotel_id,]];
                    
                    $occupancy = new Occupancy();
                    $occupancy->adults = 2;
                    $occupancy->children = 0;
                    $occupancy->rooms = 1;

                    $occupancy->paxes = [new Pax(Pax::AD, 30, "Mike", "Doe"), new Pax(Pax::AD, 27, "Jane", "Doe")];
                    $rqData->occupancies = [$occupancy];

                    $rqData->dailyRate = true;
```

Thanks for your help!

**Comment by alvmunoz** [comment]
Hi @CoreJADeveloper , may I know what dates and hotelID are you searching for?

**Comment by CoreJADeveloper** [comment]
Hi,

This is the date 

```
$rqData->stay = new Stay(DateTime::createFromFormat("Y-m-d", "2016-09-01"),
                        DateTime::createFromFormat("Y-m-d", "2016-09-10"));
```

and here is the code - 1070

Thanks!

**Comment by alvmunoz** [comment]
Hi @CoreJADeveloper , 
You don't need to request the creditCards, they are returned inside the node ONLY IF this specific hotel has rates which "**paymentType**" value is "**AT_HOTEL**".

In the search you are doing, you should receive this: 

        "creditCards": [
          {
            "code": "VI",
            "name": "VISA-SSL",
            "paymentType": "AT_HOTEL"
          },
          {
            "code": "AE",
            "name": "AMEX-SSL",
            "paymentType": "AT_HOTEL"
          },
          {
            "code": "MC",
            "name": "ECMC-SSL",
            "paymentType": "AT_HOTEL"
          },
          {
            "code": "DC",
            "name": "DINERS-SSL",
            "paymentType": "AT_HOTEL"
          }
        ]

**Comment by CoreJADeveloper** [comment]
Hi!

I get it now, the data should be in specific hotel where `paymentType` is `AT_HOTEL`

Get another problem accessing the attribute `creditCards`

Here is the loop where I can retrieve data of a hotel -

```
foreach ($availRS->hotels->iterator() as $hotelCode => $hotelData) {
.......
}
```

I am trying to get the data through accessing `creditCards`. Here is the code -

`$hotelData->creditCards`

But i get the following error -

> Fatal error:  Uncaught hotelbeds\hotel_api_sdk\generic\FieldNotValid: creditCards not valid for this model

Even I see no iterator for the `creditCards` like `room` or `rate` iterator.

Which is the correct way to retrieve `creditCards` information?

Thanks for your help!

**Comment by davidgv88** [comment]
Hi @CoreJADeveloper 

The iterator() method no return the creditCards Information.  I Think that this function has not been implemented yet.

In src/model/Hotel.php must add creditCards in validFields array and works ok.

This solutions works for me:
#### Important: Sometimes the creditCards array is not available.

```php
$availRS = $apiClient->Availability($rqData);
// Check availability is empty or not!
if (!$availRS->isEmpty()) {
     foreach ($availRS->hotels->toArray()['hotels'] as $key => $hotel) {
                    var_dump($hotel['creditCards']);
      }
}
```

**Comment by CoreJADeveloper** [comment]
Hi @davidgv88 

In Hotel.php there is no `validFields` name `creditCards`

```
$this->validFields =
            ["code" => "integer",
             "name" => "string",
             "address" => "string",
             "categoryCode" => "string",
             "categoryName" => "string",
             "destinationCode" => "string",
             "destinationName" => "string",
             "zoneCode" => "integer",
             "zoneName" => "string",
             "latitude" => "float",
             "longitude" => "float",
             "rooms" => "array",
             "totalSellingRate" => "float",
             "totalNet" => "float",
             "currency" => "string",
             "maxRate" => "float",
             "minRate" => "float",
             "giata" => "integer"
            ];
```

But converting hotels object to array using `toArray()` method solves the issue.

Thanks!

**Comment by davidgv88** [comment]
You can add manually "creditCards" => "array" in Hotel.php

But Is better not modify the library. 

For the moment use toArray() method.

@alvmunoz is correct that iterator method no return creditCards?

**Comment by Zavierazo** [comment]
Fixed with https://github.com/hotelbeds-sdk/hotel-api-sdk-php/pull/41 

Now you can get all creditCards info like this:


```
    foreach ($availRS->hotels->iterator() as $hotelCode => $hotelData){
        foreach ($hotelData->creditCardsIterator() as $creditCardCode => $creditCardData){
            echo $creditCardData->code.' '.$creditCardData->name.' '.$creditCardData->paymentType;
        }
    }
```
