### ISSUE TITLE
Base URL images

### ISSUE THREAD

**Issue by davidgv88** [hotelbeds-sdk/hotel-api-sdk-php#37]
Hi!

What is the base URL for the images?

The CONTENTAPI returns for example:
"00/000001/000001a_hb_r_001.jpg"

**Comment by davidgv88** [comment]
The solution: https://developer.hotelbeds.com/docs/read/apitude_content/hotel_operation/Hotel_Operation_Response

**Comment by alvmunoz** [comment]
that's correct, thanks @davidgv88
