### ISSUE TITLE
Exception with "sslcafile" or "sslcapath"

### ISSUE THREAD

**Issue by sangdao-dirox** [hotelbeds-sdk/hotel-api-sdk-php#4]
Hi, I got an Exception
Error accessing API: Unable to enable crypto on TCP connection api.test.hotelbeds.com: make sure the "sslcafile" or "sslcapath" option are properly set for the environment.

And then I have to add $this->httpClient->setOptions( array( 'sslcapath' => '/etc/ssl/certs' )); into HotelApiClient::__construct after line "$this->httpClient = new Client();"

Can you check please?
Maybe you can fix the bug that I don't need to do it manually, thanks

**Comment by tomeucapo** [comment]
Hi!

1) It has been proved that does not pass through a proxy? Sometimes proxys have SSL protocol restricted. 

2) I think, you have openssl and php_openssl extensions are loaded in your system.

Thanks for advance.

**Comment by mjsorribas** [comment]
I have the same problem. I use Debian 8 + php 5.6.x when i running tests, unittest  returns some errors
Output:
```
There was 1 error:

1) HotelApiClientTest::testStatus
hotelbeds\hotel_api_sdk\types\HotelSDKException: Error accessing API: Unable to enable crypto on TCP connection api.test.hotelbeds.com: make sure the "sslcafile" or "sslcapath" option are properly set for the environment.

/var/www/html/api/src/HotelApiClient.php:147
/var/www/html/api/src/HotelApiClient.php:130
/var/www/html/api/tests/HotelApiClientTest.php:65
/var/www/html/api/tests/HotelApiClientTest.php:65

FAILURES!
Tests: 1, Assertions: 0, Errors: 1, Skipped: 6.

```

**Comment by alvmunoz** [comment]
@sangdao-dirox , were you able to fix it??? 

@mjsorribas , did you follow the steps that tomeucapo advised ?

**Comment by alvmunoz** [comment]
@sangdao-dirox & @mjsorribas ,  we have just made an update to fix it. 
We changed it to use curl, so make sure you have installed and enabled the following modules: 
php_curl
php_openssl

Also, make sure you have the certificates in:    etc/ssl/certs 

Let us know if it works for you now.

**Comment by Zavierazo** [comment]
Close , if you still need help reopen please

**Comment by albertomoreno** [comment]
@alvmunoz @Zavierazo You changed adapter to use curl, but in this pull request (https://github.com/hotelbeds-sdk/hotel-api-sdk-php/commit/b3210c75a4107d217f57d691523d8653485e398d) you revert this change and now, we can't use it.
Thanks.

**Comment by Zavierazo** [comment]
Hi @albertomoreno, we revert this change because our customers have problems with this change. https://github.com/hotelbeds-sdk/hotel-api-sdk-php/issues/13 https://github.com/hotelbeds-sdk/hotel-api-sdk-php/issues/19 https://github.com/hotelbeds-sdk/hotel-api-sdk-php/issues/22

By default Zend httpclient use Zend\Http\Client\Adapter\Socket

With this PR https://github.com/hotelbeds-sdk/hotel-api-sdk-php/pull/43, adds new parameter to constructor for customize adapter of httpclient. Example:

```
$apiClient = new HotelApiClient($cfgApi["url"],
    $cfgApi["apikey"],
    $cfgApi["sharedsecret"],
    new ApiVersion(ApiVersions::V1_0),
    $cfgApi["timeout"],
    "Zend\Http\Client\Adapter\Curl");
```

**Comment by albertomoreno** [comment]
Ok, thank you. @Zavierazo

**Comment by teenu12** [comment]
When i do so i get the following exception.

[2018-01-22 11:57:11] production.ERROR: exception 'hotelbeds\hotel_api_sdk\types\HotelSDKException' with message 'Bad Request: INVALID_DATA-2d1fd785-19d5-4425-b6cf-7e5aa914f098 Invalid data. Error at property stay: Check-in must be in the future.' in /var/www/html/FootballTicketPad/teenu/footballticketpad-staging/vendor/hotelbeds/hotel-api-sdk-php/src/HotelApiClient.php:181

Anybody got it work?

**Comment by vmavromatis** [comment]
Hello @teenu12, this error means that your Check-in/Check-out dates are set in the past. Please try to alter them into future values and execute the request again.

**Comment by teenu12** [comment]
Ok Thank you @vmavromatis  

Now i am getting following error
 
[2018-01-22 12:10:00] production.ERROR: exception 'hotelbeds\hotel_api_sdk\types\HotelSDKException' with message 'Forbidden: <h1>Developer Over Rate</h1>' in /var/www/html/FootballTicketPad/teenu/footballticketpad-staging/vendor/hotelbeds/hotel-api-sdk-php/src/HotelApiClient.php:178

Can you please check?

**Comment by vmavromatis** [comment]
Hello @teenu12, I'm afraid this means that you've exceeded your daily limit for the test environment (usually 50 queries per day). Here's a list of all errors, for your reference:

https://developer.hotelbeds.com/docs/read/API_Errors

**Comment by teenu12** [comment]
Hi, I got an exception during booking api

[2018-01-23 12:31:18] production.ERROR: exception 'hotelbeds\hotel_api_sdk\types\HotelSDKException' with message 'Bad Request: INVALID_REQUEST-cdb8a83d-4ff9-4646-a6b2-eef7d19f7c98 The request is not compliant with the specified version of the API. Error at property rooms->rateKey: Text ' 20180315' could not be parsed at index 0' in /var/www/html/FootballTicketPad/teenu/footballticketpad-staging/vendor/hotelbeds/hotel-api-sdk-php/src/HotelApiClient.php:181

Can you please check?
