### ISSUE TITLE
There is no "booking" info for bookingConfirm response

### ISSUE THREAD

**Issue by shiyukun** [hotelbeds-sdk/hotel-api-sdk-php#44]
Hi Team,

I have send a booking request. the request data is var_dump()
array(4) {
  ["holder"]=>
  array(2) {
    ["name"]=>
    string(9) "firstname"
    ["surname"]=>
    string(7) "surname"
  }
  ["rooms"]=>
  array(1) {
    [0]=>
    array(2) {
      ["rateKey"]=>
      string(98) "20161208|20161210|W|322|69616|DBT.SU|OFF-FIT-TACTICA|RO||1~1~0||N@1268BE6DBAF74045ADC6A9CEA6C07278"
      ["paxes"]=>
      array(0) {
      }
    }
  }
  ["clientReference"]=>
  string(9) "integrate"
  ["language"]=>
  string(3) "CAS"
}

and I get response from bookingConfirm api. but get empty at field "booking"
{"auditData":{"processTime":"1884","timestamp":"2016-09-17 11:38:26.523","requestHost":"54.254.134.101","serverId":"sa37AUX3ROLBLIS.env","environment":"[int]","release":"02ffe3b9dbb4009c2c42e592dc58d4ebd03c682e","internal":"tjwwq3gcbskrb86nhxxadps6|SG|03|HB|2|33|0|1|20|N||||||||||1"},"booking":{}}

And there is no error message.
Please help me to locate the issue.
Thanks
Thomas

**Comment by Zavierazo** [comment]
Hi @shiyukun, booking is a array, for print the content you must use this code:

`
		echo \Zend\Json\Json::encode($confirmRS->booking->toArray ());`

**Comment by shiyukun** [comment]
Thanks, fixed.
