### ISSUE TITLE
Error parsing the response body - Decoding failed

### ISSUE THREAD

**Issue by albertomoreno** [hotelbeds-sdk/hotel-api-sdk-php#45]
I have a decoding error in BookingConfirm response.
I check codification and it's utf-8 and I set CURL adapter with the HotelApiClient constructor's param.

A example of response body is:

{"auditData":{"processTime":"1878","timestamp":"2016-09-19 12:58:45.415","requestHost":"80.24.185.216","serverId":"sa3RKSJACHXE79K.env","environment":"[int]","release":"02ffe3b9dbb4009c2c42e592dc58d4ebd03c682e","internal":"uutyg5j76kqvsyznkudu6td2|UK|03|HC|6|10|3|1|1|N||null,null||||||||1"},"booking":{"reference":"149-177357","clientReference":"PHP_TEST_2","creationDate":"2016-09-19","status":"CONFIRMED","modificationPolicies":{"cancellation":true,"modification":true},"holder":{"name":"NAME","surname":"LASTNAME"},"hotel":{"checkIn":"2016-09-23","checkOut":"2016-09-24","code":92842,"name":"GHM Monte Gorbea","categoryCode":"1LL","categoryName":"1 LLAVE","destinationCode":"SRN","destinationName":"Sierra Nevada","zoneCode":1,"zoneName":"Pradollano","latitude":"37.092608","longitude":"-3.394927","rooms":[{"status":"CONFIRMED","id":1,"code":"STU.C4","name":"ESTUDIO CAPACIDAD 4","paxes":[{"roomId":1,"type":"AD"},{"roomId":1,"type":"AD"}],"rates":[{"rateClass":"NOR","net":"64.34","sellingRate":"75.00","hotelMandatory":true,"rateComments":"Recogida de llaves en la recepci�n del Hotel GHM Monachil. Entrega a partir de las 17.00 horas. Recepci�n 24 horas.\n\n","paymentType":"AT_WEB","packaging":false,"boardCode":"SC","boardName":"SOLO ALOJAMIENTO","cancellationPolicies":[{"amount":"64.34","from":"2016-09-19T23:59:00+02:00"}],"rooms":1}]}],"totalNet":"64.34","currency":"EUR","supplier":{"name":"HOTELBEDS PRODUCT,S.L.U.","vatNumber":"ESB38877676"}},"totalNet":64.34,"pendingAmount":64.34,"currency":"EUR"}}

Thanks.

**Comment by Zavierazo** [comment]
Hi @albertomoreno, what is the error exactly and the requests parameters

**Comment by albertomoreno** [comment]
Hi again @Zavierazo , I have other example. The error is decoding failed of the response body, for example: 
{"auditData":{"processTime":"1541","timestamp":"2016-10-04 09:25:13.100","requestHost":"80.24.185.216","serverId":"sa37AUX3ROLBLIS.env","environment":"[int]","release":"02ffe3b9dbb4009c2c42e592dc58d4ebd03c682e","internal":"uutyg5j76kqvsyznkudu6td2|UK|03|HC|5|6|3|1|1|N||null,null||||||||1"},"booking":{"reference":"149-177366","clientReference":"PHP_TEST_2","creationDate":"2016-10-04","status":"CONFIRMED","modificationPolicies":{"cancellation":true,"modification":true},"holder":{"name":"ALBERTO","surname":"MORENO"},"hotel":{"checkIn":"2016-10-19","checkOut":"2016-10-20","code":92842,"name":"GHM Monte Gorbea","categoryCode":"1LL","categoryName":"1 LLAVE","destinationCode":"SRN","destinationName":"Sierra Nevada","zoneCode":1,"zoneName":"Pradollano","latitude":"37.092608","longitude":"-3.394927","rooms":[{"status":"CONFIRMED","id":1,"code":"STU.C4","name":"ESTUDIO CAPACIDAD 4","paxes":[{"roomId":1,"type":"AD"},{"roomId":1,"type":"AD"}],"rates":[{"rateClass":"NOR","net":"64.34","sellingRate":"75.00","hotelMandatory":true,"rateComments":"Recogida de llaves en la recepci�n del Hotel GHM Monachil. Entrega a partir de las 17.00 horas. Recepci�n 24 horas.\n\n","paymentType":"AT_WEB","packaging":false,"boardCode":"SC","boardName":"SOLO ALOJAMIENTO","cancellationPolicies":[{"amount":"64.34","from":"2016-10-15T23:59:00+02:00"}],"rooms":1}]}],"totalNet":"64.34","currency":"EUR","supplier":{"name":"HOTELBEDS PRODUCT,S.L.U.","vatNumber":"ESB38877676"}},"totalNet":64.34,"pendingAmount":64.34,"currency":"EUR"}}

The code for the request is:

$rqBookingConfirm = new Booking();
$rqBookingConfirm->holder = new Holder("Alberto", "Moreno");
$rqBookingConfirm->language = "CAS";

$bookingRoom = new BookingRoom("20161019|20161020|W|149|92842|STU.C4|CG-TODOS|SC||1~2~0||N@0A74E67253554AD6B350DA2E7BCDB2CF");

$rqBookingConfirm->rooms = array($bookingRoom);

$rqBookingConfirm->clientReference = "PHP_TEST_2";
try {
	$confirmRS = $apiClient->BookingConfirm($rqBookingConfirm);
} catch (\hotelbeds\hotel_api_sdk\types\HotelSDKException $e) {
	echo "\n".$e->getMessage()."\n";
	die;
}

Thanks.

**Comment by alvmunoz** [comment]
Hi @albertomoreno , thank you, we identified the issue.
@Zavierazo , can you make a workaround for the PHP sdk to solve this? I think it will take time until the fix in the API makes it to INT.

**Comment by Zavierazo** [comment]
Ho @albertomoreno, added workaround for the PHP sdk in commit https://github.com/hotelbeds-sdk/hotel-api-sdk-php/commit/b97bac7e4108889dc68e80cbe0e60cb86a824b88

**Comment by albertomoreno** [comment]
OK. This solves my problem. Thanks.
