### ISSUE TITLE
Get no classes in model to add PaymentCard and ContactData information in "Booking Request"

### ISSUE THREAD

**Issue by CoreJADeveloper** [hotelbeds-sdk/hotel-api-sdk-php#46]
Hi!

Currently, I am making request to confirm booking a room. I see in helper there is a class file name Booking.php which handles `bookingRQ`. In model `PaymentData` class works with two validfields -

```
class PaymentData extends ApiModel
{
    public function __construct()
    {
        $this->validFields = [
            "paymentCard" => "array",
            "contactData" => "array"
        ];
    }
}
```

But I can't see model classes for these two validfields like the API handles `Tax, Pax etc`. So is there any other way to set these two validfields for `bookingRQ`?

**Comment by Zavierazo** [comment]
Fixed with https://github.com/hotelbeds-sdk/hotel-api-sdk-php/commit/23985fbd69d9f7f85b0b028ba772c9fbeb17f82c
