### ISSUE TITLE
Getting "Internal Server Error" when searching available hotels with adults and child number combination

### ISSUE THREAD

**Issue by CoreJADeveloper** [hotelbeds-sdk/hotel-api-sdk-php#49]
Last time I made search feature when there was only number of adults. Currently, I am enhancing the feature with adults, child and room number combination. 

With 2 adults, 1 child and 2 rooms I make a availability request with the reply [#48](https://github.com/hotelbeds-sdk/hotel-api-sdk-php/issues/48#issuecomment-252626945) in following way -

```
$occupancy = new Occupancy();
$occupancy->adults = $adults;
$occupancy->children = $children;
$occupancy->rooms = $hotel_room_number;

$paxes = [];

    for ($i = 0; $i < $adults; $i++) {
        $paxes[] = new Pax(Pax::AD, (30 + $i), generateRandomString(5), generateRandomString(2));
    }

    for ($i = 0; $i < $children; $i++) {
        $paxes[] = new Pax(Pax::CH, 10, generateRandomString(5), generateRandomString(2));
    }

$occupancy->paxes = $paxes;
$rqData->occupancies = [$occupancy];
```

I get following error now -

```
hotelbeds\hotel_api_sdk\types\HotelSDKException Object
(
    [auditData:hotelbeds\hotel_api_sdk\types\HotelSDKException:private] => hotelbeds\hotel_api_sdk\model\AuditData Object
        (
            [validFields:protected] => Array
                (
                    [processTime] => float
                    [timestamp] => string
                    [serverId] => string
                    [requestHost] => string
                    [environment] => string
                    [release] => integer
                )

            [fields:protected] => Array
                (
                    [processTime] => 17
                    [timestamp] => 2016-10-13 17:42:32.796
                    [requestHost] => 178.62.207.205
                    [serverId] => sa3RKSJACHXE79K.env
                    [environment] => [int]
                    [release] => c71dde3dff5b7361b72a269a2d41e85a1aa34be0
                )

        )

    [message:protected] => Internal Server Error: Internal server error
    [string:Exception:private] => 
    [code:protected] => 0
    [file:protected] => /srv/users/staging/apps/travelapi3/public/wp-content/themes/listable-child/composer/vendor/hotelbeds/hotel-api-sdk-php/src/HotelApiClient.php
    [line:protected] => 162
```

So what I am thinking, the paxes distribution is not matching with the API server. It would be great if you let me know the details about the paxes distribution.

**Comment by Zavierazo** [comment]
Hi @CoreJADeveloper, we will review it. Can you add this line on your code and send me the result?

`
	echo \Zend\Json\Json::encode ( $rqData );`

**Comment by CoreJADeveloper** [comment]
Here is the result -

`{"stay":{"checkIn":"2016-10-19","checkOut":"2016-10-21"},"hotels":{"hotel":["150571","139375","212965","6014","17138","","132469","6012","99014","134831","116464","213197","8797","185492","213342","165063","87510","84136","479861","180656","6017","367547","169113"]},"occupancies":[{"adults":2,"children":1,"rooms":2}]}`

**Comment by Zavierazo** [comment]
Hi @CoreJADeveloper, the problem is your sending a hotel code empty. 

"150571","139375","212965","6014","17138",

> ""

,"132469","6012","99014","134831","116464","213197","8797","185492","213342","165063","87510","84136","479861","180656","6017","367547","169113"

We will add validation to return a more descriptive message

**Comment by CoreJADeveloper** [comment]
Now there is no empty hotel code -

`{"stay":{"checkIn":"2016-10-25","checkOut":"2016-10-27"},"hotels":{"hotel":["150571","139375","212965","6014","17138","132469","6012","99014","134831","116464","213197","8797","185492","213342","165063","87510","84136","479861","180656","6017","367547","169113"]},"occupancies":[{"adults":2,"children":1,"rooms":2}]}`

Showing following exception -

`[message:protected] => Bad Request: INVALID_DATA-3ACF6E2C6F614BC59C5FE1302CCD3912 Invalid data. Error at property occupancies: The number of children is wrong`
