### ISSUE TITLE
$confirmRS = language

### ISSUE THREAD

**Issue by pralamo** [hotelbeds-sdk/hotel-api-sdk-php#5]
Como puedo añadir attribute a $rqBookingConfirm para que responda con language=CAS
segun la doc, acepta @language como parámetro

**$confirmRS = $apiClient->bookingConfirm($rqBookingConfirm);**

Gracias y un saludo

**Comment by tomeucapo** [comment]
Hola

Ya tienes el campo añadido, en principio se añade en el helper Booking.

Saludos

**Comment by pralamo** [comment]
Gracias, Eso es lo que estaba buscando...... pero....

PHP Fatal error:  Uncaught exception 'Zend\\Json\\Exception\\RuntimeException' with message '**Decoding failed**' in /var/www/html/SR.HB.V41.9/vendor/zendframework/zend-json/src/Json.php:70\nStack trace:\n#0 /var/www/html/SR.HB.V41.9/src/HotelApiClient.php(125): 
.....etc

parece que no le gusta

**Comment by pralamo** [comment]
¿Alguna idea?
En sandbox, el idioma es añadido como un atributo del nodo, no como un nodo hijo
En la especificación de estructuras XML, una @ significa siempre atributo del nodo anterior:
bookingRQ/@language --> <bookingRQ .... language="CAS">
En la api SDK como puedo añadir ese atributo a la clase BookingConfirm para que devuelva la respuesta en el idioma deseado?

**Comment by alvmunoz** [comment]
@pralamo , 
Respecto al error , probablemente da porque la respuesta que se retornaba esta vacía, y no se pudo decodificar.  Eso generalmente sucede cuando se da un Gateway Timeout, en cuyo caso no hay respuesta. Algo que puede ser común mientras desarrollas en el servidor de test. No debería de pasar en producción.

Respecto al uso de language para la confirmación, 
deberías de hacerlo usando el helper, de la siguiente manera: 

```
           $rqBookingConfirm = new \hotelbeds\hotel_api_sdk\helpers\Booking();
           $rqBookingConfirm->holder = new \hotelbeds\hotel_api_sdk\model\Holder("Tomeu TEST", "Capo TEST");
           $rqBookingConfirm->language="CAS";
```

**Comment by pralamo** [comment]
Buenas:
Así lo añado
$rqBookingConfirm = new \hotelbeds\hotel_api_sdk\helpers\Booking();
           $rqBookingConfirm->holder = new \hotelbeds\hotel_api_sdk\model\Holder("Tomeu TEST", "Capo TEST");
           $rqBookingConfirm->language="CAS";

pero sigue dando error. He seguido un poco la ejecución y falla la funcion adjunta debajo de este mensaje. Es en el decode del json. Realmente si recibe contenido, pero da error en la decodificación. 
##  throw new RuntimeException('Decoding failed').

Sin  $rqBookingConfirm->language="CAS"; la respuesta es correcta.

seguiremos investigando

Un saludo y gracias



public static function decode($encodedValue, $objectDecodeType = self::TYPE_OBJECT)
    {
        $encodedValue = (string) $encodedValue;
        if (function_exists('json_decode') && static::$useBuiltinEncoderDecoder !== true) {
            $decode = json_decode($encodedValue, $objectDecodeType);

            switch (json_last_error()) {
                case JSON_ERROR_NONE:
                    break;
                case JSON_ERROR_DEPTH:
                    throw new RuntimeException('Decoding failed: Maximum stack depth exceeded');
                case JSON_ERROR_CTRL_CHAR:
                    throw new RuntimeException('Decoding failed: Unexpected control character found');
                case JSON_ERROR_SYNTAX:
                    throw new RuntimeException('Decoding failed: Syntax error');
                default:
                    throw new RuntimeException('Decoding failed');
            }

            return $decode;
        }

**Comment by pralamo** [comment]
así hago. Pero nada.
Es problema de decodificación .

esta es la función donde falla. Recibe el body, pero no le gusta la 
sintaxis.
seguiremos investigando:

Gracias


public static function decode($encodedValue, $objectDecodeType = 
self::TYPE_OBJECT)
     {
         $encodedValue = (string) $encodedValue;
         if (function_exists('json_decode') && 
static::$useBuiltinEncoderDecoder !== true) {
             $decode = json_decode($encodedValue, $objectDecodeType);

             switch (json_last_error()) {
                 case JSON_ERROR_NONE:
                     break;
                 case JSON_ERROR_DEPTH:
                     throw new RuntimeException('Decoding failed: 
Maximum stack depth exceeded');
                 case JSON_ERROR_CTRL_CHAR:
                     throw new RuntimeException('Decoding failed: 
Unexpected control character found');
                 case JSON_ERROR_SYNTAX:
                     throw new RuntimeException('Decoding failed: Syntax 
error');
                 default:
   throw new RuntimeException('Decoding failed');
             }

             return $decode;
         }
