### ISSUE TITLE
Getting Internal Server Error at booking confirmation

### ISSUE THREAD

**Issue by CoreJADeveloper** [hotelbeds-sdk/hotel-api-sdk-php#51]
Hi, 

I send following request to book a room with 2 adults, 1 child and 2 rooms -

`{"holder":{"name":"Holder Name","surname":"Holder Surname"},"rooms":[{"rateKey":"20161026|20161028|W|197|17138|SUI.PT|CG FIT|BB||2~2~1|10|N@B797D573A7F74A308175053A15F16DF0","paxes":[{"age":30,"type":"AD","roomId":1,"name":"cmsds","surname":"jdodiuiowe"},{"age":30,"type":"AD","roomId":1,"name":"cmsdsffd","surname":"jdodiuiowevfsdaf"},{"age":30,"type":"AD","roomId":2,"name":"cmsds","surname":"jdodiuiowe"},{"age":30,"type":"AD","roomId":2,"name":"cmsdsffd","surname":"jdodiuiowevfsdaf"},{"age":10,"type":"CH","roomId":1,"name":"dsghrt","surname":"tuewgrt"},{"age":10,"type":"CH","roomId":2,"name":"dsghrt","surname":"tuewgrt"}]}],"paymentData":{"paymentCard":{"cardType":"VI","cardNumber":"4444333322221111","cardHolderName":"Holder name","expiryDate":"0615","cardCVC":"123"},"contactData":{"email":"integration@test.com","phoneNumber":"654654654"}},"clientReference":"My booking reference"}`

Getting following error -

`[message:protected] => Internal Server Error: SYSTEM_ERROR-292F315A3E614D239BFB10BB9F7573F5 Internal server error`

**Comment by Zavierazo** [comment]
Hi @CoreJADeveloper, your apikey is not configured for make confirmation with creditcard details. Only with CREDIT mode. Contant with apitude department if you wish to activate it.

**Comment by CoreJADeveloper** [comment]
Thank you for quick response :)

Can you please let me know is the request parameters are okay?

**Comment by alvmunoz** [comment]
Hi @CoreJADeveloper , the request parameters are okey, but you can only send paymentData when booking a rate with the     

            "paymentType": "AT_WEB",

**Comment by CoreJADeveloper** [comment]
Yes, in availability request I use the parameter.

Thank you
