### ISSUE TITLE
Documentation Missing - How to Configure $config variable

### ISSUE THREAD

**Issue by NitinPrakash** [hotelbeds-sdk/hotel-api-sdk-php#52]
How to configure this variable $config. I am NEW to Hotelbeds API and not able to config this PHP SDK

$config   = $reader->fromFile(**DIR**.'/HotelApiClient.ini');

please let me know the content of HotelApiClient.ini or parameters

$cfgApi["url"], $cfgApi["apikey"], $cfgApi["sharedsecret"],

**Comment by Zavierazo** [comment]
Hi @NitinPrakash, you must add file HotelApiClient.ini with apikey and secret at same level of your main php file. Example:

```
apiclient.url          = https://api.test.hotelbeds.com
apiclient.apikey       = ********************************
apiclient.sharedsecret = **********
apiclient.timeout      = 120
```
