### ISSUE TITLE
Client comments in BookingConfirm

### ISSUE THREAD

**Issue by albertomoreno** [hotelbeds-sdk/hotel-api-sdk-php#53]
Hi.
How do you add a client comment (remark) in a BookingConfirm?
There isn't any field for this.

Thanks.

**Comment by Zavierazo** [comment]
Hi @albertomoreno, added field "remark" with commit https://github.com/hotelbeds-sdk/hotel-api-sdk-php/commit/0e6e0f47f50137f4554f9c4b2b433582d2bf7881
