### ISSUE TITLE
 Class 'PHPUnit_Framework_TestCase' not found

### ISSUE THREAD

**Issue by hotelapitest** [hotelbeds-sdk/hotel-api-sdk-php#54]
Hello,
 I'm new in the API development using SDK. I'm getting **Fatal error: Class 'PHPUnit_Framework_TestCase' not found** in _hotel-api-sdk-php/tests/HotelApiClientTest.php_ file please help for this issue.

Thanks in advance.

![error2](https://cloud.githubusercontent.com/assets/23474067/20300211/22427d50-ab44-11e6-8d8e-46babbd0788d.jpg)

**Comment by Zavierazo** [comment]
Hi @hotelapitest , please follow the guide https://github.com/hotelbeds-sdk/hotel-api-sdk-php/wiki/Step-by-step-guide-to-start-from-scratch 

You trying to execute a internal php unit of the sdk. For execute this your need php unit framework libraries installed in your environment.

**Comment by hotelapitest** [comment]
Hello,
Thanks for your reply.
I've followed the steps now I'm getting **Fatal error: Call to a member function toArray() on a non-object in C:\wamp\www\vendor\test.php on line 44** error.

Thanks in advance.

**Comment by hotelapitest** [comment]
**_This is my code_**
<?php
//error_reporting(0);
require __DIR__ .'/autoload.php';

use hotelbeds\hotel_api_sdk\HotelApiClient;
use hotelbeds\hotel_api_sdk\model\Destination;
use hotelbeds\hotel_api_sdk\model\Occupancy;
use hotelbeds\hotel_api_sdk\model\Pax;
use hotelbeds\hotel_api_sdk\model\Rate;
use hotelbeds\hotel_api_sdk\model\Stay;
use hotelbeds\hotel_api_sdk\types\ApiVersion;
use hotelbeds\hotel_api_sdk\types\ApiVersions;
use hotelbeds\hotel_api_sdk\messages\AvailabilityRS;

$reader = new Zend\Config\Reader\Ini();
$config   = $reader->fromFile(__DIR__.'/HotelApiClient.ini');
$cfgApi = $config["apiclient"];

$apiClient = new HotelApiClient($cfgApi["url"],
                                $cfgApi["apikey"],
                                $cfgApi["sharedsecret"],
                                new ApiVersion(ApiVersions::V1_0),
                                $cfgApi["timeout"]);
//echo $apiClient;
$rqData = new \hotelbeds\hotel_api_sdk\helpers\Availability();
$rqData->stay = new Stay(DateTime::createFromFormat("Y-m-d", "2016-02-01"),
                         DateTime::createFromFormat("Y-m-d", "2016-02-10"));

$rqData->destination = new Destination("PMI");
$occupancy = new Occupancy();
$occupancy->adults = 2;
$occupancy->children = 1;
$occupancy->rooms = 1;

$occupancy->paxes = [ new Pax(Pax::AD, 30, "Mike", "Doe"), new Pax(Pax::AD, 27, "Jane", "Doe"), new Pax(Pax::CH, 8, "Mack", "Doe") ];
$rqData->occupancies = [ $occupancy ];

try {
    $availRS = $apiClient->Availability($rqData);
	print_r($availRS);
} catch (\hotelbeds\hotel_api_sdk\types\HotelSDKException $e) {
    $auditData = $e->getAuditData();
    error_log( $e->getMessage() );
    error_log( "Audit remote data = ".json_encode($auditData->toArray()));
    exit();
} catch (Exception $e) {
    error_log( $e->getMessage() );
    exit();
}

**Comment by Zavierazo** [comment]
Hi @hotelapitest , please use these command for download all required libraries to use hotel-api-sdk-php 

`composer require "hotelbeds/hotel-api-sdk-php:dev-master@dev"`

and use this line at start of your php code

`require __DIR__ .'/vendor/autoload.php';`

**Comment by hotelapitest** [comment]
Hello,
Thanks for your reply.

I've tried all the above but the error is same.

Thanks again.

**Comment by Zavierazo** [comment]
@hotelapitest, can you seed me your directory tree and php version used.

**Comment by hotelapitest** [comment]
Hello,

Thanks for reply.....

**_Directory Tree_**
![directory](https://cloud.githubusercontent.com/assets/23474067/20418926/04dbe928-ad78-11e6-98da-f2c4aa2d7d7f.png)
**_PHP Version_**
![php version](https://cloud.githubusercontent.com/assets/23474067/20418952/54c33e6e-ad78-11e6-883c-b3d1d948678f.png)

**Comment by hotelapitest** [comment]
**Complete Directory Tree**
![directory structure](https://cloud.githubusercontent.com/assets/23474067/20419862/51e7bf88-ad7f-11e6-928b-b4b490c674c0.png)

**Comment by hotelapitest** [comment]
Hello,
This is the error now
![error3](https://cloud.githubusercontent.com/assets/23474067/20421659/5e9c5a34-ad8b-11e6-857f-7831fea794a1.jpg)

**Comment by hotelapitest** [comment]
Dear Zavierazo,

What about the issue?
