### ISSUE TITLE
Error on Confirm Booking

### ISSUE THREAD

**Issue by alexanderdejong** [hotelbeds-sdk/hotel-api-sdk-php#55]
Hi, I'm getting an error when I try to confirm a booking. Please see the response below. 

`stdClass Object ( [auditData] => stdClass Object ( [processTime] => 1464 [timestamp] => 2016-11-17 16:09:00.248 [requestHost] => 178.62.207.205 [serverId] => sa3RKSJACHXE79K.env [environment] => [int] [release] => 9d9357403f319f3c3c75715d34a3133aa181546e [internal] => 0|BBAB7D32738C457CA627731BE07B609C|NL||1|0|||||||||||R|0|5||||||vzdfrhhehmap72cwqef63sxa|| ) [error] => stdClass Object ( [code] => SYSTEM_ERROR-117D27074D9941DDBA420CA261CA26BF [message] => Internal server error ) )`

**Comment by Zavierazo** [comment]
Hi @alexanderdejong, the problem is solved. Sorry for the inconveniences.
