### ISSUE TITLE
Error accessing API

### ISSUE THREAD

**Issue by hotelapitest** [hotelbeds-sdk/hotel-api-sdk-php#56]
I'm getting the error: **_Error accessing API: Unable to enable crypto on TCP connection api.test.hotelbeds.com: make sure the "sslcafile" or "sslcapath" option are properly set for the environment._** by accessing the test.php on wamp, my php version is 5.5.12. I've also uploaded the same code on a server having ssl certificate **(https://holidae.in/hotel/test.php)** still I'm getting the same error.

Please help me in this issue this is very urgent.

Thanks in advance.

**Comment by Zavierazo** [comment]
Hi @hotelapitest try to declare HotelApiClient like this:

`$apiClient = new HotelApiClient($cfgApi["url"],
    $cfgApi["apikey"],
    $cfgApi["sharedsecret"],
    new ApiVersion(ApiVersions::V1_0),
    $cfgApi["timeout"],
    "Zend\Http\Client\Adapter\Curl");`

**Comment by hotelapitest** [comment]
Hi Zavierazo,

Thanks for your reply.
Reply is helpful and it works. Thanks again.
