### ISSUE TITLE
ERROR 

### ISSUE THREAD

**Issue by mcorderoaraya** [hotelbeds-sdk/hotel-api-sdk-php#59]
Nice to meet

I have several questions that I need to ask.

1. How can I include hotel codes like intergeneration $ rqData-> hotels.
2. How can I do the same but in $ occupation-> paxes.

I have tried it the following way.

for($i = 0; $i < (int)$adtHabitacion; $i++){

	if((int)$adtHabitacion==$i+1){
		$div = "";
	}else{
		$div = ",";
	}
		
	$ad = 'AD';
	$adulto .= $ad.$div;

}

if((int)$chdHabitacion>0){
	for($i = 0; $i < (int)$chdHabitacion; $i++){

		$div = ",";
		$ch = 'CH';
		$nino .= $ch.$div;
	}
}

$occupancy->paxes = [ $adulto.$nino ];

No positive results.
You can help me please.

Thank you very much

GOOGLE TRANSLATE, SORRY

**Comment by alvmunoz** [comment]
Hola @mcorderoaraya , no estoy seguro de lo que intentas hacer. ¿puedes explicarte en castellano?

**Comment by mcorderoaraya** [comment]
Hola Alvmunoz

Lo que intento es pasar los arreglos pax de manera dinámica.

$occupancy->paxes = [ $adulto.$nino ]; donde $adulto contenga new Pax(Pax::AD, 30, "Mike", "Doe") y lo mismo con niño. Esto es por que los datos son dinámicos.

Me explico?

**Comment by Zavierazo** [comment]
Hola @mcorderoaraya , mira a ver si lo que comente en https://github.com/hotelbeds-sdk/hotel-api-sdk-php/issues/29 te sirve.
