### ISSUE TITLE
POST requests get 596 Error on dev environment

### ISSUE THREAD

**Issue by fartat** [hotelbeds-sdk/hotel-api-sdk-php#6]
Hi!

I was directed by the Comercial Department here to ask you about some issues we are experiencing with you API.

We are having a small issue with implementing the api in our website. All GET requests are working ok, but the POST ones give us the 596 Service not found error.

We tried with php curl, we tried with you php sdk, we tried xml and json. All of them return the 596 Service not found error when creating a POST request. With GET there is no problem. But with GET we can not perform an availability search, we must do that with POST.

Any other request we make with POST we get the same error. But if we do it with GET, we receive some reponse, but not an error.

Can you please help us? 
Thanks!
Alex

Here is our code:

$apiKey = ".......";
$sharedSecret = "........";

$signature = hash("sha256", $apiKey.$sharedSecret.time());

$endpoint = "https://api.test.hotelbeds.com/hotel-content-api/1.0/hotels";

$xml = '< availabilityRQ xmlns="http://www.hotelbeds.com/schemas/messages" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" >
	< stay checkIn="2016-09-19" checkOut="2016-09-21"/>
	< occupancies>
		< occupancy rooms="1" adults="1" children="1">
			< paxes>
				< pax type="AD" age="31"/>
				< pax type="CH" age="3"/> 
 			</ paxes>
		</ occupancy> 
	</ occupancies>
	< hotels>
       < hotel>1067</ hotel> 
       < hotel>1070</ hotel>
       < hotel>135813</ hotel> 
    </ hotels> 
</ availabilityRQ>';

$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $endpoint);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_ENCODING, "gzip");
curl_setopt($ch, CURLOPT_VERBOSE, 1);
curl_setopt($ch, CURLOPT_HEADER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
curl_setopt($ch, CURLOPT_POSTFIELDS, $xml);

$headers = array();
$headers[] = 'Api-Key: '.$apiKey;
$headers[] = 'X-Signature: '.$signature;
$headers[] = 'Content-Type: application/xml';
$headers[] = 'Accept: application/json';
$headers[] = 'Accept-Encoding: Gzip';

curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$server_output = curl_exec ($ch);

$header_size = curl_getinfo($ch, CURLINFO_HEADER_SIZE);
$header = substr($server_output, 0, $header_size);
$body = substr($server_output, $header_size);

curl_close ($ch);

echo $header;
echo $body;

An we are getting this: http://beta.infotour.ro/ws/hotelbeds/test.php

**Comment by alvmunoz** [comment]
@fartat , can you let the community know how did you fix it? 
Thanks,

**Comment by fartat** [comment]
The problem was on our dev server, the curl was somehow sending bad POST requests with bad headers...

**Comment by alvmunoz** [comment]
Ok, thank you very much : )
