### ISSUE TITLE
Does not answer anything

### ISSUE THREAD

**Issue by mcorderoaraya** [hotelbeds-sdk/hotel-api-sdk-php#60]
`
$xml = '<availabilityRQ xmlns="http://www.hotelbeds.com/schemas/messages" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" >
    <stay checkIn="2017-06-15" checkOut="2017-06-20" shiftDays="2"/>
    <occupancies>
        <occupancy rooms="1" adults="2" children="1">
            <paxes>
                <pax type="AD"/>
                <pax type="AD"/>
                <pax type="CH" age="8"/>
            </paxes>
        </occupancy>
    </occupancies>
    <hotels>
        <hotel>1067</hotel>
        <hotel>1070</hotel>
        <hotel>1075</hotel>
        <hotel>135813</hotel>
        <hotel>145214</hotel>
        <hotel>1506</hotel>
        <hotel>1508</hotel>
        <hotel>1526</hotel>
        <hotel>1533</hotel>
        <hotel>1539</hotel>
        <hotel>1550</hotel>
        <hotel>161032</hotel>
        <hotel>170542</hotel>
        <hotel>182125</hotel>
        <hotel>187939</hotel>
        <hotel>212167</hotel>
        <hotel>215417</hotel>
        <hotel>228671</hotel>
        <hotel>229318</hotel>
        <hotel>23476</hotel>
    </hotels>
</availabilityRQ>';
$apiKey = "xxxxxxxxxxxxxxxxxxxxxx";
$secret = "xxxxxxxxxx";
// Signature is generated by SHA256 (Api-Key + Secret + Timestamp (in seconds))
$signature = hash("sha256", $apiKey.$secret.time());
// Example of call to the API
$endpoint = "https://api.test.hotelbeds.com/hotel-api/1.0/hotels";

    try
    {

    //setting the curl parameters.
    $ch = curl_init($endpoint);

    curl_setopt($ch, CURLOPT_VERBOSE, 1); // set url to post to 
    curl_setopt($ch, CURLOPT_URL, $endpoint); // set url to post to 
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1); // return into a variable 
    curl_setopt($ch, CURLOPT_HTTPHEADER, array(
                    'Api-Key:'.$apiKey,
                    'X-Signature: '.$signature,
                    'Accept: application/xml',
                    'Content-Type: application/xml'
            ));
    curl_setopt($ch, CURLOPT_HEADER, 1); 
    curl_setopt($ch, CURLOPT_TIMEOUT, 40); // times out after 4s 
    curl_setopt($ch, CURLOPT_POSTFIELDS, $xml);
    curl_setopt($ch, CURLOPT_POST, 1); 

    $httpcode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    $response = curl_exec($ch);
    curl_close($ch);

    //Check status
    if ($httpcode != 200) {  
       printf("KO %s returned '%s' (%d)\n",$endpoint,$response,$httpcode);
    } else {
       printf("OK %s returned '%s' (%d)\n",$endpoint,$response,$httpcode);
    }

    } catch (Exception $ex) {
        printf("Error while sending request, reason: %s\n",$ex->getMessage());
    }`

What do I lack?

**Comment by alvmunoz** [comment]
What's your problem?

**Comment by mcorderoaraya** [comment]
Como paso un xml vía curl. Como en el ejemplo anterior, no se que malo tiene que no me responde nada.

**Comment by Zavierazo** [comment]
Hola @mcorderoaraya, para pasar un xml a través de curl te recomiendo que busques en google donde podrás encontrar mucha mas ayuda https://www.google.es/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=php+curl+post

Por otro lado, si lo que te interesa es usar el sdk para hotel booking api te recomiendo que sigas la siguiente guia https://github.com/hotelbeds-sdk/hotel-api-sdk-php/wiki/Step-by-step-guide-to-start-from-scratch. Esta te ayudara a empezar a usar nuestro sdk que ya tiene incorporado todos los modelos y helpers para facilitar tu trabajo.
