### ISSUE TITLE
How to test Hotel beds API

### ISSUE THREAD

**Issue by hotelapitest** [hotelbeds-sdk/hotel-api-sdk-php#63]
Hi,

I'm getting **Fatal error:** _Class 'PHPUnit_Framework_TestCase' not found in /home/wwwholid/public_html/hotel/hotelbeds/hotel-api-sdk-php/tests/BookingApiTest.php on line 32_

Please help me with this error of Test API and how to include the PHPUnit Framework.

Thanks in advance.
![error](https://cloud.githubusercontent.com/assets/23474067/21128256/7137e42c-c11f-11e6-881e-e721137bbc82.png)

**Comment by Zavierazo** [comment]
Hi @hotelapitest, please follow https://github.com/hotelbeds-sdk/hotel-api-sdk-php/wiki/Step-by-step-guide-to-start-from-scratch.
