### ISSUE TITLE
Class 'hotelbeds\hotel_api_sdk\helpers\Dest' not found

### ISSUE THREAD

**Issue by hotelapitest** [hotelbeds-sdk/hotel-api-sdk-php#65]
I'm trying to get all the destinations from the activity API. I'm getting 
**_Fatal error: Class 'hotelbeds\hotel_api_sdk\helpers\Dest' not found in /home/wwwholid/public_html/hotel/fetch.php on line 23_** error.

Can any one help please.

Thanks in advance.

**My code is:-**
<?php
require __DIR__ .'/autoload.php';
//require 'C:\vendor\autoload.php';

use hotelbeds\hotel_api_sdk\HotelApiClient;
use hotelbeds\hotel_api_sdk\types\ApiVersion;
use hotelbeds\hotel_api_sdk\types\ApiVersions;
use hotelbeds\hotel_api_sdk\model\Destination;
use hotelbeds\hotel_api_sdk\messages\DestinationRS;

$reader = new Zend\Config\Reader\Ini();
$config   = $reader->fromFile(__DIR__.'/HotelApiClient.ini');
$config   = $reader->fromFile('HotelApiClient.ini');
$cfgApi = $config["apiclient"];

$apiClient = new HotelApiClient($cfgApi["url"],
                                $cfgApi["apikey"],
                                $cfgApi["sharedsecret"],
                                new ApiVersion(ApiVersions::V1_0),
								$cfgApi["timeout"]);

$rqData = new \hotelbeds\hotel-api-sdk-php\helpers\Dest();

$rqData->destination = new Destination('All');

echo "<pre>";
print_r($rqData);
echo "</pre>";

/*echo "<pre>";
print_r($_POST);
echo "</pre>";
exit();*/

//This is where you send the request to the API for a response
try {
    $cityRS = $apiClient->destination();
	print_r($cityRS);
} catch (\hotelbeds\hotel_api_sdk\types\HotelSDKException $e) {
    $auditData = $e->getAuditData();
	print_r( $e->getMessage());
	//exit();
    error_log( $e->getMessage() );
    error_log( "Audit remote data = ".json_encode($auditData->toArray()));
    exit();
} catch (Exception $e) {
    error_log( $e->getMessage() );
    exit();
}

// Check Cities or Destinations is empty or not and print it out!
if (!$cityRS->isEmpty()) {
	echo "<pre>";
    //print_r($cityRS->hotels->toArray());
	print_r($cityRS->toArray());
	echo "</pre>";
} else {
   echo "There are no results!";
}

**Comment by Zavierazo** [comment]
Hi @hotelapitest, this sdk is only for Hotel Booking Api. https://developer.hotelbeds.com/docs/read/apitude_booking
