### ISSUE TITLE
Hotel By destination is not working

### ISSUE THREAD

**Issue by hotelapitest** [hotelbeds-sdk/hotel-api-sdk-php#66]
Hello,

On the search by destination and zone is not working, the error is **

> Warning: Creating default object from empty value in /home/wwwholid/public_html/hotel/fetch.php on line 28
> Bad Request: INVALID_DATA-1f240f8b-0bf0-41e2-8905-8bc95ce34514 Invalid data. Destination search is not available by default. Please contact with API Distribution Team

**

**Comment by Zavierazo** [comment]
Hi @hotelapitest, by default the destination search is not available. Please contact directly to API Distribution Team. https://developer.hotelbeds.com/contact

**Comment by hotelapitest** [comment]
Thanks for reply I've already done and they replied that the key is also upgraded but still getting the same error, what may be the issue with it.

**Comment by alvmunoz** [comment]
@hotelapitest  , since this is an issue in your account settings, please keep contact with the agents in apitude@hotelbeds.com to solve this.
Thanks.
