### ISSUE TITLE
Not Authorized

### ISSUE THREAD

**Issue by hotelapitest** [hotelbeds-sdk/hotel-api-sdk-php#67]
Hello,

Why I'm getting **Not Authorized** error on content-api:-
**My code:-**
>  $url = "https://api.test.hotelbeds.com/hotel-content-api/1.0/hotels/".$hotelcode."?language=ENG";

> $ch = curl_init();
> curl_setopt($ch, CURLOPT_URL, $url);
> curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
> curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
> curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true );
> curl_setopt($ch, CURLOPT_HTTPHEADER, array(
> 'Api-Key: m4nu2b489ba5qurgy-------',
> 'X-Signature: QK--------',
> 'Content-Type: application/json',
> 'Accept: application/json',
> 'Accept-encoding: Gzip'
> ));

> $resp = curl_exec($ch);
> curl_close($ch);
> echo $resp;

Please help to get the details of particular hotel like images, details etc.

Thanks in advance.

**Comment by alvmunoz** [comment]
please, if you are not using the SDK, send your query to apitude@hotelbeds.com .
thanks,
