### ISSUE TITLE
curl hotel details return always blank

### ISSUE THREAD

**Issue by bunwanli** [hotelbeds-sdk/hotel-api-sdk-php#69]
I want to tell you I don’t use your sdk library and use my own code.
Xml code I use is from your sandbox. It run smooth at sandbox but not in my code
I want to try get available list hotels but It always return blank

my source code 

$key = "9u***********";
                                $secret = "yM**********";
                                $signature = hash("sha256", $key.$secret.time());
                                $url = 'https://api.test.hotelbeds.com/hotel-api/1.0/hotels';
                                $httpHeader = array(
                                                "Api-Key: ".$key,
                                                "X-Signature: ".$signature,
            "Accept: application/xml",
                                                "Accept-Charset : utf-8",
                                                "Accept-Enconding : gzip, deflate",
                                                "Content-Type : application/xml"
        );
`$requestData2 = '<availabilityRQ xmlns="http://www.hotelbeds.com/schemas/messages" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" >
                                                                                                <stay checkIn="2017-06-15" checkOut="2017-06-20" shiftDays="2"/>
                                                                                                <occupancies>
                                                                                                                <occupancy rooms="1" adults="2" children="1">
                                                                                                                                <paxes>
                                                                                                                                                <pax type="AD"/>
                                                                                                                                                <pax type="AD"/>
                                                                                                                                                <pax type="CH" age="8"/>
                                                                                                                                </paxes>
                                                                                                                </occupancy>
                                                                                                </occupancies>
                                                                                                <hotels>
                                                                                                                <hotel>1067</hotel>
                                                                                                                <hotel>1070</hotel>
                                                                                                                <hotel>1075</hotel>
                                                                                                                <hotel>135813</hotel>
                                                                                                                <hotel>145214</hotel>
                                                                                                                <hotel>1506</hotel>
                                                                                                                <hotel>1508</hotel>
                                                                                                                <hotel>1526</hotel>
                                                                                                                <hotel>1533</hotel>
                                                                                                                <hotel>1539</hotel>
                                                                                                                <hotel>1550</hotel>
                                                                                                                <hotel>161032</hotel>
                                                                                                                <hotel>170542</hotel>
                                                                                                                <hotel>182125</hotel>
                                                                                                                <hotel>187939</hotel>
                                                                                                                <hotel>212167</hotel>
                                                                                                                <hotel>215417</hotel>
                                                                                                                <hotel>228671</hotel>
                                                                                                                <hotel>229318</hotel>
                                                                                                                <hotel>23476</hotel>
                                                                                                </hotels>
                                                                                </availabilityRQ>';`
                                
                                
                                $curl = curl_init();
                                
                                curl_setopt_array($curl, array(
                                                CURLOPT_RETURNTRANSFER => 1,
                                                CURLOPT_URL => $url,
                                                CURLOPT_HTTPHEADER => $httpHeader,
                                                CURLOPT_SSL_VERIFYPEER => false,
                                                CURLOPT_POSTFIELDS => $requestData2,
                                                CURLOPT_POST => 1,
                                                CURLOPT_ENCODING => "gzip",
                                ));
                                $httpcode = curl_getinfo($curl, CURLINFO_HTTP_CODE);
                                $curl_errno= curl_errno($curl);
                                $resp = curl_exec($curl);
                                
                                if($curl_errno!=0)
                                echo $curl_errno;
                                
                                if ($httpcode != 200) {  
                                   echo "KO ".$httpcode;
                                } else {
                                   echo "OK ".$httpcode;
                                }
                                
                                echo $resp;
                                
                                // Close request to clear up some resources
                                curl_close($curl);
What is lacking with my code?

**Comment by Zavierazo** [comment]
Hi @bunwanli, your code works fine. Contact with  apitude@hotelbeds.com with your apikey to check if is correctly configured.

**Comment by bunwanli** [comment]
thanks, problem solved.

**Comment by Ravindrage** [comment]
I am also getting same blank page . how you resolve the issue.
