### ISSUE TITLE
allowOnlyShift (boolean)

### ISSUE THREAD

**Issue by pralamo** [hotelbeds-sdk/hotel-api-sdk-php#7]
Segun la plataforma sandbox:
<stay checkIn="2016-06-15" checkOut="2016-06-20" shiftDays="2"/>

Depurando el código, en la clase availabily/stay aparece el campo  **allowOnlyShift **como campo válido. No lo he utilizado nunca porque no se lo que significa. Es boolean.
¿?
Gracias

**Comment by alvmunoz** [comment]
@pralamo , 
allowOnlyShift es para uso interno. No necesitas utilizarlo, razón por la que tampoco aparece en la documentación. 
Un saludo

**Comment by alvmunoz** [comment]
@pralamo ,  
Ya que lo tenemos disponible, hemos decidido hacerlo público. Te explico la funcionalidad:

allowOnlyShift = True -->  En caso de que la fecha para la que has buscado no tenga disponibilidad, se buscará disponibilidad en los shift days.

allowOnlyShift = False --> Si la fecha que has buscado no tiene disponibilidad, no se buscarán los shiftDays. 

Por defecto el valor será True si no se especifica.

**Comment by pralamo** [comment]
Gracias por la respuesta. Ahora me queda claro.



En relación al otro asunto (CAS) que me trae un poco de cabeza, no lo 
veo claro:

|$rqBookingConfirm = new \hotelbeds\hotel_api_sdk\helpers\Booking(); 
$rqBookingConfirm->holder = new 
\hotelbeds\hotel_api_sdk\model\Holder("Tomeu TEST", "Capo TEST"); 
$rqBookingConfirm->language="CAS";|



así hago. Pero nada.
Es problema de decodificación .

(Por cierto, ha desaparecido este hilo del GitHub)?????


esta es la función donde falla. Recibe el body, pero no le gusta la 
sintaxis.
seguiremos investigando:

Gracias

[json][zend]
public static function decode($encodedValue, $objectDecodeType = 
self::TYPE_OBJECT)
     {
         $encodedValue = (string) $encodedValue;
         if (function_exists('json_decode') && 
static::$useBuiltinEncoderDecoder !== true) {
             $decode = json_decode($encodedValue, $objectDecodeType);

             switch (json_last_error()) {
                 case JSON_ERROR_NONE:
                     break;
                 case JSON_ERROR_DEPTH:
                     throw new RuntimeException('Decoding failed: 
Maximum stack depth exceeded');
                 case JSON_ERROR_CTRL_CHAR:
                     throw new RuntimeException('Decoding failed: 
Unexpected control character found');
                 case JSON_ERROR_SYNTAX:
                     throw new RuntimeException('Decoding failed: Syntax 
error');
                 default:
   throw new RuntimeException('Decoding failed');
             }

             return $decode;
         }

El 30/03/2016 a las 14:13, Álvaro escribió:
>
> @pralamo <https://github.com/pralamo> ,
> Respecto al error , probablemente da porque la respuesta que se 
> retornaba esta vacía, y no se pudo decodificar. Eso generalmente 
> sucede cuando se da un Gateway Timeout, en cuyo caso no hay respuesta. 
> Algo que puede ser común mientras desarrollas en el servidor de test. 
> No debería de pasar en producción.
>
> Respecto al uso de language para la confirmación,
> deberías de hacerlo usando el helper, de la siguiente manera:
>
> |$rqBookingConfirm = new \hotelbeds\hotel_api_sdk\helpers\Booking(); 
> $rqBookingConfirm->holder = new 
> \hotelbeds\hotel_api_sdk\model\Holder("Tomeu TEST", "Capo TEST"); 
> $rqBookingConfirm->language="CAS"; |
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/hotelbeds-sdk/hotel-api-sdk-php/issues/5#issuecomment-203401398>
>


El 01/04/2016 a las 9:26, Álvaro escribió:
>
> @pralamo <https://github.com/pralamo> ,
>
> Ya que lo tenemos disponible, hemos decidido hacerlo público. Te 
> explico la funcionalidad:
>
> allowOnlyShift = True --> En caso de que la fecha para la que has 
> buscado no tenga disponibilidad, se buscará disponibilidad en los 
> shift days.
>
> allowOnlyShift = False --> Si la fecha que has buscado no tiene 
> disponibilidad, no se buscarán los shiftDays.
>
> Por defecto el valor será True si no se especifica.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/hotelbeds-sdk/hotel-api-sdk-php/issues/7#issuecomment-204288161>
>

**Comment by alvmunoz** [comment]
¿Puedes poner el caso de CAS en el issue de CAS y cerramos esto? 
Lo miramos.

**Comment by pralamo** [comment]
ok.
resubido

**Comment by alvmunoz** [comment]
gracias
