### ISSUE TITLE
Need help, Required request body is missing

### ISSUE THREAD

**Issue by bunwanli** [hotelbeds-sdk/hotel-api-sdk-php#70]
I want to tell you I don’t use your sdk library and use my own code.
Xml code i am used already test in sandbox. It run smooth at sandbox but not in my code
I try to booking but with my code i get response 

`<?xml version="1.0" encoding="UTF-8"?><bookingRS xmlns="http://www.hotelbeds.com/schemas/messages" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" schemaLocation="http://www.hotelbeds.com/schemas/messages"><auditData timestamp="2017-01-20 04:54:59.548" requestHost="182.253.44.155" serverId="sa37AUX3ROLBLIS.env" environment="[int]" release="b947c8c9f98970fbae11877a005ca86dba591acc" internal="0||||0|0||||||||||||0|||||||9u2tkxnqvwdmacfsc6gdq3zh||"/><error><code>INVALID_REQUEST-AA504721418D4D13BD9B3CD0F9C9D0C4</code><message>The request is not compliant with the specified version of the API. Required request body is missing</message></error></bookingRS>`

my source code

$key = "9u2t****";
		$secret = "yM*****";
		$signature = hash("sha256", $key.$secret.time());
		$url = 'https://api.test.hotelbeds.com/hotel-api/1.0/bookings';
		$httpHeader = array(
			"Api-Key: ".$key,
			"X-Signature: ".$signature,
            "Accept: application/xml",
			"Accept-Charset : utf-8",
			"Accept-Enconding : gzip, deflate",
			"Content-Type : application/xml",
			"X-Originating-Ip: ".$_SERVER['REMOTE_ADDR'],
        );
	
`$requestData2 = '<bookingRQ xmlns="http://www.hotelbeds.com/schemas/messages" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
						<holder name="iwan" surname="sugiarto"/>
						<clientReference>INV02363</clientReference>
						<rooms>
						<room rateKey="20170221|20170222|W|322|80187|DBT.DX|GS-ALL|RO||1~2~0||N@0D5ED70DD22F49B7991CE3D13AE41AC8">
						<paxes>
						<pax roomId="1" type="AD" age="30" name="iwan" surname="sugiarto"/>
						<pax roomId="1" type="AD" age="30" name="iwan" surname="sugiarto"/>
						</paxes>
						</room>
						<room rateKey="20170221|20170222|W|322|80187|DBT.DX|GS-ALL|RO||1~2~0||N@0D5ED70DD22F49B7991CE3D13AE41AC8">
						<paxes>
						<pax roomId="1" type="AD" age="30" name="mama" surname="mia"/>
						<pax roomId="1" type="AD" age="30" name="lezatos" surname="lezatos"/>
						</paxes>
						</room>
						</rooms>
						<remark>
						If possible please provide non smoking room,If possible please provide adjoining rooms
						</remark>
						</bookingRQ>';`

$curl = curl_init();
		curl_setopt_array($curl, array(
			CURLOPT_RETURNTRANSFER => 1,
			CURLOPT_URL => $url,
			CURLOPT_HTTPHEADER => $httpHeader,
			CURLOPT_SSL_VERIFYPEER => false,
			CURLOPT_POSTFIELDS => $requestData2,
			CURLOPT_POST => 1,
		));
		$httpcode = curl_getinfo($curl, CURLINFO_HTTP_CODE);
		$curl_errno= curl_errno($curl);
		$resp = curl_exec($curl);

if($curl_errno!=0)
		echo $curl_errno;
		
if ($httpcode != 200) {  
		   echo "KO ".$httpcode;
		} else {
		   echo "OK ".$httpcode;
		}
		
echo $resp;
		
// Close request to clear up some resources
curl_close($curl);

The problem is, why i get different response when i try in sandbox, and with my own code
What is lacking with my code?

**Comment by rv8820** [comment]
Hi,  How do I get the hotel details like the description and images?  DO you have a sample script for this?

**Comment by bunwanli** [comment]
I already contact apitude team. they say my xml code above have wrong code.
so i already fix my xml code, and send it to apitude and they say my xml code is correct.

the problem is, it's not work with my own code using CURL

$key = "9u2tkx*******";
$secret = "yM8******";
$signature = hash("sha256", $key.$secret.time());
$url = 'https://api.test.hotelbeds.com/hotel-api/1.0/bookings';
$httpHeader = array(
	"Api-Key: ".$key,
	"X-Signature: ".$signature,
	"Accept: application/xml",
	"Accept-Charset : utf-8",
	"Accept-Enconding : gzip, deflate",
	"Content-Type : application/xml",
	"X-Originating-Ip: ".$_SERVER['REMOTE_ADDR'],
);

`$requestData2 = '<bookingRQ xmlns="http://www.hotelbeds.com/schemas/messages" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
					<holder name="iwan" surname="sugiarto"/>
					<clientReference>INV02370</clientReference>
					<rooms>
					<room rateKey="20170419|20170420|W|322|140150|DBL.ST|GS-BAR COMMISSI|RO||2~2~0||N@D9C628AC9D37470B9A7DCCE509F42A40">
					<paxes>
					<pax roomId="1" type="AD" age="30" name="iwan" surname="sugiarto"/>
					<pax roomId="1" type="AD" age="30" name="iwan" surname="sugiarto"/>
					<pax roomId="2" type="AD" age="30" name="ali" surname="baba"/>
					<pax roomId="2" type="AD" age="30" name="gooo" surname="gole"/>
					</paxes>
					</room>
					</rooms>
					<remark>
					If possible please provide non smoking room,Please note client will arrive without voucher
					</remark>
					</bookingRQ>';`

$curl = curl_init();

curl_setopt_array($curl, array(
	CURLOPT_RETURNTRANSFER => 1,
	CURLOPT_URL => $url,
	CURLOPT_HTTPHEADER => $httpHeader,
	CURLOPT_SSL_VERIFYPEER => false,
	CURLOPT_POSTFIELDS => $requestData2,
	CURLOPT_POST => 1,
));
$httpcode = curl_getinfo($curl, CURLINFO_HTTP_CODE);
$curl_errno= curl_errno($curl);
$resp = curl_exec($curl);

$file = fopen(uniqid().'RQ.xml', 'w');
fwrite($file, str_replace('requestXML=','',$requestData2));
fclose($file);	

$file = fopen(uniqid().'RS.xml', 'w');
fwrite($file, $resp);
fclose($file);

if ($httpcode != 200) {  
   echo "KO ".$httpcode;
} else {
   echo "OK ".$httpcode;
}

// Close request to clear up some resources
curl_close($curl);

please answer me

**Comment by Zavierazo** [comment]
Hi @bunwanli , you can use 

`echo $resp;
`
for view full response of api.

**Comment by bunwanli** [comment]
the response is always return 'The request is not compliant with the specified version of the API. Required request body is missing'. but when i try at sandbox always work fine.

i am already ask apitude and get answer
 For this case we already check your key and make a booking as show in attach everything work normally. So in this case as it's in test environment sometimes have an connection issues and lead to cause an errors we suggest you to try again.

but i believe its not about connection issues, because its really work fine in sandbox.

`<bookingRS xmlns="http://www.hotelbeds.com/schemas/messages" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" schemaLocation="http://www.hotelbeds.com/schemas/messages">
<auditData timestamp="2017-01-31 06:24:35.812" requestHost="101.128.81.165" serverId="sa3RKSJACHXE79K.env" environment="[int]" release="b947c8c9f98970fbae11877a005ca86dba591acc" internal="0||||0|0||||||||||||0|||||||9u2tkxnqvwdmacfsc6gdq3zh||"/>
<error>
<code>INVALID_REQUEST-390978C6BDB949B6A2E4B022772B1856</code>
<message>
The request is not compliant with the specified version of the API. Required request body is missing
</message>
</error>
</bookingRS>`

**Comment by bunwanli** [comment]
I always get http code 400. but my code already use CURLOPT_SSL_VERIFYPEER => false
so what is wrong?

**Comment by alvmunoz** [comment]
Hi @bunwanli , 
I am sorry but in github we can only give support for the SDK. 
If you are using your own code, please contact apitude@hotelbeds.com

**Comment by bunwanli** [comment]
Apitude says that if i have a question about code, i must ask at github.
Ok, i will close this issues

thanks for all help

**Comment by alvmunoz** [comment]
@bunwanli I am sure that was a misunderstanding, they must have understood that you were using the SDK.

**Comment by Titya** [comment]
I also got this problem. I cannot continue do anything.
