### ISSUE TITLE
Error occurred on Confirm Booking

### ISSUE THREAD

**Issue by frankwangxin** [hotelbeds-sdk/hotel-api-sdk-php#73]
Hello, Hello, this is my own written code, I can not get the correct results in the confirmation of the reservation. This problem has troubled me for a long time, seriously affected the progress of my development. Please help me
<?xml version="1.0" encoding="UTF-8"?><bookingRS xmlns="http://www.hotelbeds.com/schemas/messages" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" schemaLocation="http://www.hotelbeds.com/schemas/messages"><auditData timestamp="2017-02-15 02:38:47.135" requestHost="101.95.166.54" serverId="sa3RKSJACHXE79K.env" environment="[int]" release="40f9476ebdaf2b1bf1ed6c31585d2f67765b40d3" token="83cf32df-d066-432c-855a-bddd390c9e2a" internal="0||||0|0||||||||||||0|||||||x595x2m5wqcwxp7shvayz9jn||"/><error><code>INVALID_REQUEST-83cf32df-d066-432c-855a-bddd390c9e2a</code><message>The request is not compliant with the specified version of the API. Required request body is missing</message></error></bookingRS>

$key = "****************";
        $Secret = "***********";
        $times = time();
        $signature = hash("sha256", $key.$Secret.$times);
        $url = 'https://api.test.hotelbeds.com/hotel-api/1.0/bookings';
        $httpHeader = array(
            "Api-Key: ".$key,
            "X-Signature: ".$signature,
            "Accept: application/xml",
            "Accept-Charset : utf-8",
            "Accept-Enconding : gzip, deflate",
            "Content-Type : application/xml",
            "X-Originating-Ip: ".$_SERVER['REMOTE_ADDR'],
        );
        $data  = "<bookingRQ xmlns=\"http://www.hotelbeds.com/schemas/messages \"
        schemaLocation=\"http://www.hotelbeds.com/schemas/messages\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">
    <holder name=\"NAME\" surname=\"SURNAAME\" />
    <clientReference>test test</clientReference>
    <rooms>
    <room rateKey=\"20170315|20170414|W|148|82390|SGL.ST|NRF-FIT-RO|RO||1~1~0||N@42AE251A88B54A08A1DDC3A51C5B17C0\">
      <paxes>
        <pax roomId=\"1\" type=\"AD\" age=\"30\" name=\"ADULTNAME\" surname=\"ADULTSURNAAME\" />
      </paxes>
    </room>
  </rooms>
    </bookingRQ>";

        $res = data_post($url,$httpHeader,$data);
        print_r($res);
 public function data_post($url,$httpHeader,$requestData2=null){
        $curl = curl_init();

        curl_setopt_array($curl, array(
            CURLOPT_RETURNTRANSFER => 1,
            CURLOPT_URL => $url,
            CURLOPT_HTTPHEADER => $httpHeader,
            CURLOPT_SSL_VERIFYPEER => false,
            CURLOPT_POSTFIELDS => $requestData2,
            CURLOPT_CONNECTTIMEOUT => 20,
            CURLOPT_POST => 1,
        ));
        //curl_setopt($curl, CURLOPT_HEADER, true);
        $resp = curl_exec($curl);
        return $resp;
        curl_close($curl);

    }

**Comment by Zavierazo** [comment]
please, if you are not using the SDK, send your query to apitude@hotelbeds.com .
thanks,
