### ISSUE TITLE
Extension for Hotel Details

### ISSUE THREAD

**Issue by Ravindrage** [hotelbeds-sdk/hotel-api-sdk-php#74]
Hello , 

How can I  improve SDK  to get all Hotel Details. 

I create a hotels.php  in helper like this 

class Hotels extends ApiHelper
{
    /**
     * Availability constructor.
     */
    public function __construct()
    {
        $this->validFields = [
                "fields" => "string",
               "language" => "string"
                ];
    }
}

and call this $rqData = new \hotelbeds\hotel_api_sdk\helpers\Hotels();

it show null data  ?

**Comment by hadyhallak** [comment]
You may use my clone of the repo here

https://github.com/hadyhallak/hotel-api-sdk-php

contains implementations for most hotel content-api endpoints.
