### ISSUE TITLE
Error occurred on Confirm Booking

### ISSUE THREAD

**Issue by Titya** [hotelbeds-sdk/hotel-api-sdk-php#75]
Hello, This is my own written code, I can not get the correct results in the confirmation of the reservation. And i alwasy got the message "The request is not compliant with the specified version of the API. Required request body is missing". This problem has troubled me for a long time, seriously affected the progress of my development. Please help me

$apiKey = "xxxxxxxxx";
$Secret = "xxxxxxxx";
$signature = hash("sha256", $apiKey.$Secret.time());
$curl = curl_init();
					
curl_setopt_array($curl, array(
CURLOPT_URL => "https://api.test.hotelbeds.com/hotel-api/1.0/bookings",
CURLOPT_RETURNTRANSFER => true,
CURLOPT_ENCODING => "",
CURLOPT_MAXREDIRS => 10,
CURLOPT_TIMEOUT => 30,
CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
CURLOPT_CUSTOMREQUEST => "POST",
CURLOPT_POSTFIELDS => "< bookingRQ xmlns="http://www.hotelbeds.com/schemas/messages" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
< holder name="Titya" surname="Lorn"/>
         < clientReference>001rtr003</clientReference><rooms><room rateKey="20170227|20170228|W|321|60711|TWN.SU|FIT-ASIA-TH-IL|BB||1~1~0||N@5819704BE9BC468DAD19D7B8CB9C351F">
			< paxes>
				< pax roomId="1" type="AD" age="30" name="Titya" surname="Lorn"/>
			< /paxes>
		< /room>
	< /rooms>
< /bookingRQ>",
					
     CURLOPT_HTTPHEADER => array(
	   "api-key: ".$apiKey,
	   "x-signature: ".$signature,
	   'Content-Type : application/xml',
	   'accept : application/xml'
    ),
));
					
$response = curl_exec($curl);
$err = curl_error($curl);
					
curl_close($curl);
     try {
	  echo $response;
    } catch (HttpException $ex) {
	  echo "cURL Error #:" . $err;
    }

**Comment by Zavierazo** [comment]
please, if you are not using the SDK, send your question to apitude@hotelbeds.com .
thanks,
