### ISSUE TITLE
API not responding 505 Error

### ISSUE THREAD

**Issue by shahzaib1616** [hotelbeds-sdk/hotel-api-sdk-php#79]
when I am using this class for checking availability:

`$availRS = $apiClient->Availability($rqData);`

getting error:

```
"www.rovenow.com is currently unable to handle this request.

HTTP ERROR 500"
```

**Comment by shahzaib1616** [comment]
can you please help us or not kindly reply if you can not so also tell us that you can't because we need quickly response.

**Comment by parischung** [comment]
http://www.rovenow.com/ is currently blank. Is it your company website?

**Comment by shahzaib1616** [comment]
https://www.rovenow.com/hotelapi/test.php this is the correct link.

**Comment by alvmunoz** [comment]
Hi, 
please check the server datetime is correct.

When you generate the x-signature , you use your system time. If the time is not correct, this will generate an invalid x-signature and hence return a "Not Authorized" error.

**Comment by vmavromatis** [comment]
Hello @shahzaib1616, I am trying to reproduce the error. Can you give me some more information please? Which request method are you applying (hotels/ geolocation / destination)? Which other classes are you using? If you use    

`var_dump($availRS->hotels->toArray());`

does the page print the response array?

**Comment by vmavromatis** [comment]
Another handy way to debug a '500 Internal Error' for POST requests in PHP is by using the function _getLastRequest_ of class _HotelApiClient_.

If you want the whole request:
`echo $lastRQ= $apiClient->getLastRequest()->toString();
`
Or if you only want the JSON:
`echo $lastRQ= $apiClient->getLastRequest()->getContent();
`

and check your request with a tool such as Postman. If you cannot get echo to work, you can connect a debugger and add a breakpoint. Let me know if you need any more help.
