### ISSUE TITLE
Model classes requiring "float" data type instead of "double"

### ISSUE THREAD

**Issue by andrewchak** [hotelbeds-sdk/hotel-api-sdk-php#80]
When we try to construct an availability search with filters, currently there is an issue with setting the `minRate` and `maxRate` fields of a `hotelbeds\hotel_api_sdk\model\Filter` object.

In `src/model/Filter.php`, it requires the data type of minRate and maxRate to be `float`. However, this will throw an exception **"Type error: Field minRate needs float type!"** from `src/generic/DataContainer.php` line 58, because `gettype($value)` will return `double` and not `float`. This is outlined in the official PHP documentation:

http://php.net/manual/en/function.gettype.php

which says `"double" (for historical reasons "double" is returned in case of a float, and not simply "float")`

So all model classes under src/model folder with data type requirements set to `float` needs to be changed to `double`. Affected files are:

- src/model/AuditData.php
- src/model/Booking.php
- src/model/CancellationPolicy.php
- src/model/DailyRate.php
- src/model/Filter.php
- src/model/Hotel.php
- src/model/Rate.php
- src/model/Tax.php

**Comment by vmavromatis** [comment]
@andrewchak Good find, flagging as Enhancement.

**Comment by nathanphan** [comment]
is it applied?

**Comment by vmavromatis** [comment]
@nathanphan not yet applied. If possible make the changes manually before we update this.

**Comment by vmavromatis** [comment]
Merge done. Let me know if there are any issues and we can re-open. Thanks!
