### ISSUE TITLE
Class 'hotelbeds\hotel_api_sdk\messages\checkRateRQ' not found 

### ISSUE THREAD

**Issue by eumanito** [hotelbeds-sdk/hotel-api-sdk-php#81]
I'm trying send Booking Confirmation and checkRate before, but "checkRateRQ" class is not found.

My code:

>         require __DIR__ .'/hotelbeds/vendor/autoload.php';
> 	use hotelbeds\hotel_api_sdk\HotelApiClient;
> 	use hotelbeds\hotel_api_sdk\messages\BookingConfirmRS;
> 	use hotelbeds\hotel_api_sdk\messages\CheckRateRS;
> 	use hotelbeds\hotel_api_sdk\model\Destination;
> 	use hotelbeds\hotel_api_sdk\model\Geolocation;
> 	use hotelbeds\hotel_api_sdk\model\Occupancy;
> 	use hotelbeds\hotel_api_sdk\model\Pax;
> 	use hotelbeds\hotel_api_sdk\model\Rate;
> 	use hotelbeds\hotel_api_sdk\model\Stay;
> 	use hotelbeds\hotel_api_sdk\types\ApiVersion;
> 	use hotelbeds\hotel_api_sdk\types\ApiVersions;
> 	use hotelbeds\hotel_api_sdk\messages\AvailabilityRS;
> 	use hotelbeds\hotel_api_sdk\messages\BookingListRS;
> 
> 
>         $reader = new Zend\Config\Reader\Ini();
> 	$config   = $reader->fromFile(__DIR__ .'/hotelbeds/HotelApiClient.ini');
> 	$cfgApi = $config["apiclient"];
> 
> 	$apiClient = new HotelApiClient($cfgApi["url"],
> 									$cfgApi["apikey"],
> 									$cfgApi["sharedsecret"],
> 									new ApiVersion(ApiVersions::V1_0),
> 									$cfgApi["timeout"]);
> 
>         $rqCheck = new \hotelbeds\hotel_api_sdk\helpers\CheckRate();
> 	$rqCheck->rooms = [ ["rateKey" => "MY RATEKEY HERE"] ];
> 	$apiClient->checkRate($rqCheck);

Can anybody help me?

**Comment by hadyhallak** [comment]
Make sure to call `CheckRate` with a capital `C` as below:

`$apiClient->CheckRate($rqCheck);`

**Comment by eumanito** [comment]
It's worked!
Very thanks!

**Comment by globatum** [comment]
@eumanito can you close this?
