### ISSUE TITLE
Error While trying to install with composer

### ISSUE THREAD

**Issue by fujael** [hotelbeds-sdk/hotel-api-sdk-php#82]
Hi,
I am trying to install php SDK in my server via composer. I have downloaded master.zip file and unzipped. Then-
cd hotel-api-sdk-php-master/
composer require "hotelbeds/hotel-api-sdk-php:dev-master@dev"
$ composer require "hotelbeds/hotel-api-sdk-php:dev-master@dev"
Problem 1
    - The requested package hotelbeds/hotel-api-sdk-php No version set (parsed as 1.0.0) is satisfiable by hotelbeds/hotel-api-sdk-php[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

Have any solution?

**Comment by vmavromatis** [comment]
@fujael you need to use composer init first. So type:

`composer init –vvv`

And in the following dialogs hit Enter, Enter, n, dev, Enter, Enter, yes, Enter, yes. Then use composer require normally as per the instructions.
In case you are using PHPStorm you may fire up the console by using Ctrl+Shift+X.

**Comment by vmavromatis** [comment]
Closing, please reopen if you have any more questions regarding the same issue.

**Comment by fujael** [comment]
Thank You So Much Buddy!
