### ISSUE TITLE
Do we have HotelCONTENTAPI in PHP?

### ISSUE THREAD

**Issue by eumanito** [hotelbeds-sdk/hotel-api-sdk-php#83]
I'm using this Hotel Api Sdk to request abailability, but I need request too more information. The APITUDE docs have a "HotelCONTENTAPI" to request more information.

I need this because the Hotelbeds have many options and types do request:
https://developer.hotelbeds.com/docs/read/apitude_content/types_operations

Anybody have a PHP Class to share?

**Comment by hadyhallak** [comment]
You may use my clone of the repo here

https://github.com/hadyhallak/hotel-api-sdk-php

contains implementations for most hotel content-api endpoints.

**Comment by ivanpuga** [comment]
Hi @hadyhallak can you please contact me by email? ivanpuga@outlook.com
