### ISSUE TITLE
Super Rich Content?

### ISSUE THREAD

**Issue by gmgint** [hotelbeds-sdk/hotel-api-sdk-php#85]
Dear HotelBeds Team,

accordin to your promo you provide so much information including **even bed type**... however we can't find the way to get this information using the API...
can you help us to understand how to get it?

http://c2n.me/3JHKBk1

thanks,
Vlad

**Comment by parischung** [comment]
Dear Vlad,
Thank you for your inquiry.
Bed Type does not exist for all hotels, but if there is, you will receive by either:

1. https://api.hotelbeds.com/hotel-content-api/1.0/types/rooms?fields=description%2CtypeDescription%2CcharacteristicDescription&language=ENG&from=1&to=100&useSecondaryLanguage=false 

Response:
{ 
"code": "APT-BR2", 
"characteristic": "1B-2T", 
"description": "APARTMENT 1 DOUBLE BED-TWO TWIN", 
"typeDescription": { 
"content": "APARTMENT" 
}, 
"characteristicDescription": { 
"content": "1 DOUBLE BED-TWO TWIN" 
} 

2. 
https://api.hotelbeds.com/hotel-content-api/1.0/hotels/1 
Response:
{ 
"roomCode": "DBT-E10", 
"description": "Double or Twin", 
"characteristic": { 
"code": "ST", 
"description": { 
"content": "STANDARD" 
} 
}

**Comment by vmavromatis** [comment]
Closing as issue appears to be resolved.
