### ISSUE TITLE
This apikey is not associated with a valid client

### ISSUE THREAD

**Issue by globatum** [hotelbeds-sdk/hotel-api-sdk-php#88]
We are having issues connecting to your API with our live credentials.

local.ERROR: hotelbeds\hotel_api_sdk\types\HotelSDKException: Server Error: PRODUCT_ERROR-a02d798e-04d4-4764-b8ec-32a37e0e3f50 ProductException(61693d47-a5dd-4cbb-b6b1-8868f9aa1b32, AVAILABILITY, This apikey is not associated with a valid client):

 in /home/forge/api.membershiptravel.com/vendor/hotelbeds/hotel-api-sdk-php/src/HotelApiClient.php:184

Are you able to help us understand what this means and how we can fix the issue?

**Comment by parischung** [comment]
Please email to apitude@hotelbeds.com with your API-Key (do not include your SECRET). We will check and get back to you. Thanks.

**Comment by parischung** [comment]
Please email your API-Key to apitude@hotelbeds.com (do not include SECRET). Hotelbeds Apitude Team will check for you. Thank you.

**Comment by nathanielasare** [comment]
Currently stuck because of this same issue. Kindly for my access key below

Key: ujhz5vh8mu42dh4dxr7wz6uw

**Comment by vmavromatis** [comment]
Hi @nathanielasare I manually updated the cache with your apikey - please try again.

Regards,
Vasilis

**Comment by nathanielasare** [comment]
Thanks Vasilis. We are back on track now. But is there a possibility of
cache having issues in production??

**Comment by vmavromatis** [comment]
Good to hear. 
> But is there a possibility of cache having issues in production??
No it should never be the case - all the issues we were facing were related to the test environment. 

Regards,
Vasilis

**Comment by nathanielasare** [comment]
Thanks once again. I really appreciate your help.

**Comment by amir201808** [comment]
Hello Friends,

I am facing the similar issue. I am using the sandbox details. It was working fine until yesterday at present getting the **This apikey is not associated with a valid client**  message for any api call of the hotelbeds.

Thanks !

**Comment by BrodriguezHbeds** [comment]
Hi @amir201808 ,

I checked and I could get results with your key. Can you try again?

Thanks,
Bruno Rodríguez

**Comment by amir201808** [comment]
Thank you Bruno.

*You Rock !! .Your solution works like a charm*

Thanks and Regards
Amir Mustafa
Virasat Solutions

**Comment by amir201808** [comment]
It worked. Now it is showing Developer overrate message. Can you please
guide me. Yesterday it showed me the same message and then
not associated with a valid client
message.
[image: Screenshot from 2019-08-20 17-18-10.png]
Thanks and Regards
Amir Mustafa
Virasat Solutions

**Comment by amir201808** [comment]
Hello,

Are there some limits for this API. Yesterday after 10 to 15 API calls
developer overate message came. It should have gone by today but is still
coming. How can I fix this issue?

Shall this be done every time after this message.

Thanks and Regards
Amir Mustafa
Virasat Solutions

**Comment by BrodriguezHbeds** [comment]
Hi @amir201808 ,

I just checked, your key is working again.

The user-created keys in the portal have a limit of 50 requests per day and 2 requests per second. I'll check why after 15 calls the limit appeared. In any case, in the response headers, you should be able to see at what time the quotas are reset (look for a header called "X-Plan-Quota-Reset").

Regards,
Bruno Rodríguez

**Comment by kjregan120** [comment]
Hello, 
I'm having the same problem, I can't access or use the sandbox. below is my API Key
APPKey - wyxvfmdshat536s45smm2srq
