### ISSUE TITLE
File '/vendor/hotelbeds/hotel-api-sdk-php/tests/HotelApiClient.ini' doesn't exist or not readable

### ISSUE THREAD

**Issue by globatum** [hotelbeds-sdk/hotel-api-sdk-php#89]
This is suddenly a problem after performing composer update.

`File '/vendor/hotelbeds/hotel-api-sdk-php/tests/HotelApiClient.ini' doesn't exist or not readable`

This happens when trying to view the checkout information right before booking a hotel

**Comment by globatum** [comment]
Why is the SDK referencing a file that does not exist on github? HotelApiClient.ini is not in the source

**Comment by vmavromatis** [comment]
@globatum, HotelApiClient.ini needs to be manually created, we will update the step-by-step guide to make sure that this information is highlighted. Furthermore, per popular request, we will include a working example that utilises HotelApiClient.ini.

**Comment by vmavromatis** [comment]
Added with #103.  You may also use the new demo folder.
