### ISSUE TITLE
Need help in starting from scratch

### ISSUE THREAD

**Issue by moumitadev** [hotelbeds-sdk/hotel-api-sdk-php#91]
I am not very familiar with API. I tried using curl but the API didn't work.
So, i went through the documentation process.
According to the documentation, i have used my API key and secret with this code - 
<?php

// Your API Key and secret
$apiKey = "yourApiKey";
$Secret = "yourSecret";

// Signature is generated by SHA256 (Api-Key + Secret + Timestamp (in seconds))
$signature = hash("sha256", $apiKey.$Secret.time());

// Example of call to the API
$endpoint = "https://api.test.hotelbeds.com/hotel-api/1.0/status";

$request = new http\Client\Request("GET",
    $endpoint,
    [ "Api-Key"     => $apiKey,
      "X-Signature" => $signature,
      "Accept"      => "application/xml" ]);
try
{

    $client = new http\Client;

    $client->enqueue($request)->send();

    // pop the last retrieved response

    $response = $client->getResponse();

    if ($response->getResponseCode() != 200) {  

       printf("%s returned '%s' (%d)\n",

           $response->getTransferInfo("effective_url"),

           $response->getInfo(),

           $response->getResponseCode()

       );

    } else {

       printf($response->getBody());

    }

} catch (Exception $ex) {

    printf("Error while sending request, reason: %s\n",$ex->getMessage());

}
?>
but i am getting this error - 
Fatal error:  Class 'http\Client\Request' not found

how do i get this class and include in my file? i am using Wordpress for my site.
Please reply its urgent.
Thanks.

**Comment by moumitadev** [comment]
I have achieved the hotel list through REST http client. 
I have used the GET method for Hotels request.
Using a PHP rest http client, this is my code:

<?php

$apiKey = "xxx";
$Secret = "xxx";

$signature = hash("sha256", $apiKey.$Secret.time());

require_once 'rest/autoload.php';

try {

    $api = new \OtherCode\Rest\Rest(new \OtherCode\Rest\Core\Configuration(array(
        'url' => 'https://api.test.hotelbeds.com/hotel-content-api/1.0/',
        'httpheader' => array(
            'Api-Key' => $apiKey,
            "X-Signature" => $signature,
        )
    )));
    $api->setDecoder("json");

    $response = $api->get("hotels?fields=all");
    echo "<pre>";print_r($response);

} catch (\Exception $e) {
  print $e->getMessage();
}
?>

I am getting a long hotel list. But the hotels which my client has listed with the API are not there.

**Comment by vmavromatis** [comment]
@moumitadev, apologies for the late response, have you managed to resolve the issue? Can you please repost your code as it's not pasted fully?

It is recommended that you use POST for the availability request as GET has become deprecated. Please refer to the API documentation https://developer.hotelbeds.com/docs/read/apitude_booking/Availability
There is also a working PHP example under /tests/HotelApiClientTest.php in public function testAvailRQ().

**Comment by vmavromatis** [comment]
Closing. If you have any more questions regarding the same issue, please re-open.
