### ISSUE TITLE
Unable to integrate hotelbeds api in php website

### ISSUE THREAD

**Issue by shawnnnn** [hotelbeds-sdk/hotel-api-sdk-php#93]
Good evening
skype- roadroostertr

 I am a online travel agent in Thailand. i am trying to setup hotel booking through http://hotebeds.com  on my site. My programmer is facing big difficulty in integrating this hotelbooking only api. When we contacted the hotelbeds team here locally, they couldnt help us, as informed us that they can assist only in the xml level. I have attached the screenshot sent by my programmer where the error pops up. He alreaady installed PECL and SDK toolkit.Kindly review the screenshot below;
![error2](https://user-images.githubusercontent.com/29736870/27601234-ca73ffbc-5b98-11e7-9c8f-500e9f552354.jpg)
![errore1](https://user-images.githubusercontent.com/29736870/27601243-cf6373c2-5b98-11e7-97c8-fa428ca7741f.jpg)

**Comment by davidgv88** [comment]
Hi @shawnnnn 

You have to see the server error Log.

Maybe CURL not installed in the server

**Comment by vmavromatis** [comment]
@shawnnnn,  to add to the above, you can check if you have cURL installed by entering:
```
<? php
phpinfo();
?>
```
and scrolling to the cURL section. If it works you should see something like this:

```
cURL support        enabled
cURL Information    7.54.1

```

**Comment by vmavromatis** [comment]
Closing. If you have any more questions regarding the same issue, please re-open.
