### ISSUE TITLE
There is no way to get hotel images.

### ISSUE THREAD

**Issue by disapamok** [hotelbeds-sdk/hotel-api-sdk-php#95]
I tried to check availability by sending required parameters, This gave me the right response but without hotel images. Is there a way to get hotel images?

`
$rqData = new \hotelbeds\hotel_api_sdk\helpers\Availability();
$rqData->stay = new Stay(DateTime::createFromFormat("Y-m-d", $checkinDate), DateTime::createFromFormat("Y-m-d", $checkOutDate));

$geoLocation = new \hotelbeds\hotel_api_sdk\model\Geolocation();
$geoLocation->longitude = 116.40;
$geoLocation->latitude = 39.90;
$geoLocation->radius = 5.0;
$geoLocation->unit = \hotelbeds\hotel_api_sdk\model\Geolocation::KM;

$rqData->geolocation = $geoLocation;

$occupancy = new Occupancy();
$occupancy->adults = $adultCount;
$occupancy->children = $childrenCount;
$occupancy->rooms = $roomsCount;

$paxesArray = array();
for ($index = 0; $index < $childrenCount; $index++) {
    array_push($paxesArray, new Pax(Pax::CH, 8));
}
$occupancy->paxes = $paxesArray;
$rqData->occupancies = [$occupancy];
`

**Comment by chinext** [comment]
Hotel images, description, facilities and some other information about any hotel are part of ContentAPI not BookingAPI, this SDK supports only BookingAPI. 
You have to download the all Hotelbed Content & save in your database.
Then you can map Availability result with your saved content to add the images, description etc

**Comment by disapamok** [comment]
Yeah, Thanks. I used hotel-beds API to get the content.
