### ISSUE TITLE
SDK working fine on local-server but one i upload SDK on an online server i got this error

### ISSUE THREAD

**Issue by becology1100** [hotelbeds-sdk/hotel-api-sdk-php#99]
SDK working fine on local-server but one i upload SDK on an online server i
got this error

<br />
<b>Fatal error</b>:  Uncaught ZendConfigExceptionRuntimeException:
File 'http://hoscobeds.com/hotelbedsAPI/vendor/hotelbeds/hotel-api-sdk-php/tests/config/Common.ini'
doesn't exist or not readable in
/home/hoscobeds/public_html/hotelbedsAPI/vendor/zendframework/zend-config/src/Reader/Ini.php:66
Stack trace:
#0 /home/hoscobeds/public_html/hotelbedsAPI/search.php(19):
ZendConfigReaderIni-&gt;fromFile('http://hoscobed...')
#1 {main}
  thrown in <b>/home/hoscobeds/public_html/hotelbedsAPI/vendor/zendframework/zend-config/src/Reader/Ini.php</b>
on line <b>66</b><br />

do you have an answer?

**Comment by vmavromatis** [comment]
Hi @becology1100, apologies for the late response. I am able to access 'http://hoscobeds.com/hotelbedsAPI/vendor/hotelbeds/hotel-api-sdk-php/tests/config/Common.ini' directly, so the file is definitely there. Please make sure that your PHP code is looking for the **relative** path as such:
```
$reader = new Zend\Config\Reader\Ini();
$config = $reader->fromFile(__DIR__.'/HotelApiClient.ini');
```
Also, it's recommended that you create your own .ini file and place it in the parent folder as it's pointed out in the [step-by-step guide](https://github.com/hotelbeds-sdk/hotel-api-sdk-php/wiki/Step-by-step-guide-to-start-from-scratch). Config.ini is ideally meant to be used for unit testing.
Please let me know if you need any more help or guidance.

**Comment by becology1100** [comment]
Hello, PHP code is looking for the relative path as you show .. the current issue is SDK working fine on local-server but online server return that error
Fatal error: Uncaught ZendConfigExceptionRuntimeException: File 'http://hoscobeds.com/hotelbedsAPI/vendor/hotelbeds/hotel-api-sdk-php/tests/config/Common.ini' doesn't exist or not readable in /home/hoscobeds/public_html/hotelbedsAPI/vendor/zendframework/zend-config/src/Reader/Ini.php:66 Stack trace: #0 /home/hoscobeds/public_html/hotelbedsAPI/search.php(19): ZendConfigReaderIni->fromFile('http://hoscobed...') #1 {main} thrown in /home/hoscobeds/public_html/hotelbedsAPI/vendor/zendframework/zend-config/src/Reader/Ini.php on line 66

**Comment by vmavromatis** [comment]
This sounds like a permissions issue. As a general rule, please make sure your .ini file and/or folders have the correct permissions. What is your server type and OS? For example have a look at the following for setting the correct permissions under Linux/Apache.

https://askubuntu.com/a/64894

> If your server documents are in /home/$USER/public_html directory you need to run
> 
> sudo chown -R www-data:www-data /home/$USER/public_html
> to give ownership of the DocumentRoot folder to the user www-data and group www-data.
> 
> Then you can add yourself to the group www-data
> 
> sudo adduser $USER www-data
> Finally, you need to make the DocumentRoot folder writable by owner (www-data user) and to your self (as part of the www-data group):
> 
> sudo chmod -R 775 /home/$USER/public_html

where $USER is hoscobeds or whichever username you want to use.

**Comment by vmavromatis** [comment]
Closing. Feel free to re-open, if you come accross any more related problems.
